### ISSUE TITLE
Mention copyright in speaker instructions

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#1]
Since we are going to publish the recordings and preferably slides, we should request that the speakers do not include materials that they may not publish in their presentation.

We'll probably also need to explain a bit about fair use.

**Comment by akhmerov** [comment]
More notes:

- We should explain that it's not OK to grab an image from the internet, and recommend to use either google image search with copyright filter, or wikimedia commons.
- We should mention fair use and how it might apply to academic presentations.

**Comment by everthemore** [comment]
I expect that having the copyright filter in Google image search may already take care of a majority of copyright breaches. Good idea!

**Comment by vfatemi** [comment]
I've edited to mention the copyright filter for images, but I'm not sure what is the right language regarding discussion of fair use here.

**Comment by akhmerov** [comment]
Already done.
