### ISSUE TITLE
VSF organizational meeting 9th June 2020

### ISSUE THREAD

**Issue by akamra47** [virtualscienceforum/virtualscienceforum#103]
Here's the [zoom link](https://zoom.us/j/97339120210). We've enabled waiting room there, so please reply here if you would like to join (and if I don't already know you).

Here a [hackmd](https://hackmd.io/JOQSYYthSWenpULyXQqujQ?edit) document for the minute notes.

Proposed agenda:

+ Finalizing the participants for chat with the speaker
+ Final checks on upcoming Long range colloquium
+ Speaker for the next colloquium and further speakers
+ Update on scanning probe microscopy conference
+ Next week's chair

Comment on this issue to add more items to the agenda.

**Comment by akhmerov** [comment]
The first two items fall through because we've postponed the event.

I propose additioinal items instead:

- Code show and tell (I'll explain roughly how my machinery works, #102)
- Further updates on writing
- Decision on how to announce the colloquium in 2 weeks.

**Comment by akamra47** [comment]
Thanks. I have updated the agenda accordingly. 

However, I have fallen ill and cannot make it to the meeting. Sorry. I guess anyone with the VSF account can be the host and chair the meeting.

**Comment by akamra47** [comment]
Meeting was cancelled.
