### ISSUE TITLE
Email reminder to participants of SPM workshop

### ISSUE THREAD

**Issue by giulia-pacchioni** [virtualscienceforum/virtualscienceforum#108]
Hi @akhmerov,

Here is a draft of the message we would like to send to participants ahead of tomorrow's meeting. After yesterday's awesome demonstration of Mail Gun I wonder if you can include the personalized Zoom link for the meeting? Also let me know if you can fish the participant list from Zoom or if I should send it to you by email.

Thanks!!!
Giulia

Dear %recipient_name%
 
This is a reminder that [Virtual SPM](https://sites.google.com/view/virtualspm/home) kicks-off tomorrow at 9:00 AM CEST. We are looking forward to seeing you there!
 
Here is the link to access the talks: %recipient.join_url%.
 
For the poster session, each poster presenter set up a Zoom room for a live discussion. The links are listed in this [private page](...). Many presenters have also prepared a video teaser for their poster, so pop in to have a look even before the poster session starts!
 
In the private page you will also find three Zoom links to ‘chat rooms’ that will be available to all participants during the coffee break and poster session to meet and have a virtual break together.
 
Best wishes,
Virtual SPM organizers
 
Fabio Donati
Fabian Natterer
Giulia Pacchioni
Marina Pivetta
Aparajita Singha

**Comment by akhmerov** [comment]
If all worked well, you should get the link now. I also edited out the link from the issue description.
