### ISSUE TITLE
VSF organizational meeting 23rd June 2020, 7 pm (CEST)

### ISSUE THREAD

**Issue by greplova** [virtualscienceforum/virtualscienceforum#109]
Zoom link to the meeting is [here](https://virtualscienceforum-org.zoom.us/j/97339120210), document with agenda and minutes is [here](https://hackmd.io/zLpnjFUMSUeFyLvfwcb-eQ).

The waiting room for the meeting is enabled, please comment below if you would like to join. 

Proposed agenda:

- debrief on the "chat with the speaker" colloquium feature
- final checks for the upcoming Long Range Colloquium
- summer colloquium schedule
- update on status of manual rewrites
- next week's chair

If you would like to add to the agenda, please comment below.

**Comment by akhmerov** [comment]
If @giulia-pacchioni is attending, SPM debrief would be great.

**Comment by babaks77** [comment]
I'll join.

**Comment by giulia-pacchioni** [comment]
I'm coming :)

**Comment by akamra47** [comment]
I will join as well :)

**Comment by greplova** [comment]
The notes are available at the [WIKI](https://github.com/virtualscienceforum/virtualscienceforum/wiki/VSF-Organization-Meeting-06-23-2020).
