### ISSUE TITLE
VSF organizational meeting 30rd June 2020, 7 pm (CEST)

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#113]
Zoom link to the meeting is [here](https://virtualscienceforum-org.zoom.us/j/97339120210), document with agenda and minutes is [here](https://hackmd.io/kEJmRWBeT_aXMxpwYe0Gdw).

The waiting room for the meeting is enabled, please comment below if you would like to join (and you don't already have access).

Proposed agenda:

- Website update (guides, branding)
- LRC speaker selection
- Search for new events (e.g. schools)
- Data workshop, quantum transport mini-course

If you would like to add to the agenda, please comment below.

**Comment by everthemore** [comment]
I've been out for a while, but I'm happy to see if I can contribute again!

**Comment by akhmerov** [comment]
Notes: https://github.com/virtualscienceforum/virtualscienceforum/wiki/VSF-organizational-meeting-2020-06-30
