### ISSUE TITLE
VSF organizational meeting 21 July 2020, 7pm CEST / 1pm EST

### ISSUE THREAD

**Issue by vfatemi** [virtualscienceforum/virtualscienceforum#127]
Zoom link: https://virtualscienceforum-org.zoom.us/j/97339120210

Hackmd link for meeting minutes forthcoming. 

Proposed agenda: 
- Check if everyone can see the registration form on their browser
- Registration / advertising discussion for Long Range Colloquium
- Anyon mini-conference
- "twisted tips and tricks" update
- Ideas for next LRC speaker

**Comment by akhmerov** [comment]
https://hackmd.io/AQvXPNC1R5KOiMlAbEWs6Q
