### ISSUE TITLE
update pre-colloquium checklist

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#128]
May also include items for during the talk

**Comment by vfatemi** [comment]
This is old and doesn't specify anything. We've also recently updated it. Is there something missing from the checklist implied here @akhmerov ?

**Comment by akhmerov** [comment]
Looking at the [notes from the same day](https://hackmd.io/AQvXPNC1R5KOiMlAbEWs6Q), it seems that the issue was about checking whether the room capacity should be increased. We have now removed that item from the checklist.
