### ISSUE TITLE
Observing Anyons 2020

### ISSUE THREAD

**Issue by babaks77** [virtualscienceforum/virtualscienceforum#135]
## Organizers

- Maissam Barkeshli
- Valla Fatemi
- Babak Seradjeh

## Description

This year two experimental groups reported observations indicating fractional statistics of quasiparticles in a quantum Hall state. Such observations are long awaited since the first observations in the 1990s of fractional charge in the same type of state. These observations are both important and recent, but the experiments, theory, and historical context are rather involved, even for condensed matter physicists who are not subject matter experts. We wish to present and contextualize both works for the broader physics community. Hence we propose the following structure (also reflected in the potential speaker list below) that we believe will help the audience to develop a deeper understanding and appreciation for the results and their nuances.

1. Pedagogical introduction by an expert not involved in the experimental work
2. Speaker from the first experimental work
3. Speaker from the second experimental work
4. Panel discussion and Q&A with a moderator involving all three speakers as well as three other subject-matter experts.

## List of potential speakers 

- Steve Simon, general introduction (confirmed)
- Gwendal Fève, PI from the Paris experiment (confirmed)
- A speaker from the Purdue experiment
- Panel (to be finalized in consultation with the moderator):
  - Moderator: Steve Simon
  - 1 member of each experimental team
  - 1 third-party experimentalist: Moty Heiblum, Mitali Banerjee 
  - 2 theorists: 
    - Bert Halperin (or Ady Stern),
    - Bernd Rosenow
    - Steve Kivelson,
    - Smitha Vishveshwara,
    - Sankar Das Sarma, 
    - Steve Girvin, 
    - Xiao-Gang Wen, 
    - Chetan Nayak, 
    - Frank Wilczek, 
    - Xie Chen

## Preferred date and time slot

A day in the first week of October, Oct 5-9, possibly from 12-3pm EDT

**Comment by babaks77** [comment]
Mike Manfra and James Nakamura from the Purdue experiment have confirmed participation.

**Comment by babaks77** [comment]
Moty Heiblum is confirmed as panelist.

**Comment by babaks77** [comment]
Bert Halperin is confirmed as panelist.

**Comment by babaks77** [comment]
Smitha Vishveshwara confirmed.

**Comment by babaks77** [comment]
Bernd Rosenow confirmed as panelist.

**Comment by vfatemi** [comment]
Started VSF website: #142

**Comment by akhmerov** [comment]
With the conference page being up, the next step is announcing it via email & twitter, right? Do you have an announcement text we could use in the email?

**Comment by babaks77** [comment]
Twitter announcement is posted. We haven't composed an email announcement yet. Will work on it today.

**Comment by babaks77** [comment]
**Email Announcement**

From: anyons2020@virtualscienceforum.org
Subject: Observing Anyons 2020 mini-conference

Dear *****,

We would like to invite you to attend [Observing Anyons 2020](https://virtualscienceforum.org/#/Observing_Anyons_2020) on Oct 5, 2020, a [Virtual Science Forum](https://virtualscienceforum.org/) mini-conference on the latest advances on observing anyons in nature. The focus of the conference is on two experimental efforts in 2020, led by Gwendal Fève at École normale supérieure and by Michael Manfra at Purdue University, reporting the first observation of fractional statistics in fractional quantum Hall devices. The conference features a pedagogical introduction to the subject by Steven Simon, presentations by each experimental group, and a moderated expert panel discussion of the implications and outlook of these findings. Our confirmed panelists are: 

> Gwendal Fève, École normale supérieure (France)
> Bertrand Halperin, Harvard University (USA)
> Moty Heiblum, Weizmann Institute of Science (Israel)
> Michael J. Manfra, Purdue University (USA)
> James Nakamura, Purdue University (USA)
> Bernd Rosenow, Leipzig University (Germany)
> Smitha Vishveshwara, University of Illinois at Urbana-Champaign (USA)

For more information on the conference, including the program and free registration, please visit: https://virtualscienceforum.org/#/Observing_Anyons_2020.

Best regards,
Organizers

Maissam Barkeshli, University of Maryland (USA)
Valla Fatemi, Yale University (USA)
Babak Seradjeh, Indiana University at Bloomington (USA)

**Comment by vfatemi** [comment]
- [ ] Reminder email ~2 hours in advance. @akhmerov @babaks77 

Dear [name],

Thank you for registering for Observing Anyons 2020! The event will begin in 2 hours (9:30 AM ET / 3:30 PM CEST). 

You can join using your registration link.

If you would like to submit questions for the panel discussion in advance, please submit them to  @anyons2020@virtualscienceforum.org.

Best regards,
The organizers

**Comment by akhmerov** [comment]
I scheduled it to be sent. I think those that register between now and tomorrow don't need a reminder.

**Comment by akhmerov** [comment]
For the recording please specify the title as well as start and end timestamps for each talk `[hh:]mm:ss[.ms]`. If there's a segment that needs to be cut out in the middle, list the cut timestamps in the same order.

**Comment by babaks77** [comment]
> For the recording please specify the title as well as start and end timestamps for each talk `[hh:]mm:ss[.ms]`. If there's a segment that needs to be cut out in the middle, list the cut timestamps in the same order.

Do you mean timestamps taking the start of the event as reference or timestamp in UTC?

**Comment by akhmerov** [comment]
Timestamps from the start of the recording.

**Comment by babaks77** [comment]
We're going to have separate video clips for each talk. What is timestamping needed for? CC?

**Comment by babaks77** [comment]
And what software do you use for clipping/editing the recordings? I find QuickTime and iMovie on my Mac rather clunky.

**Comment by akhmerov** [comment]
> We're going to have separate video clips for each talk. What is timestamping needed for? CC?

Ah, were you stopping and restarting the recordings? The timestamps are to remove the parts of the recording before the event begins, so that there isn't awkward silence/speaker opening their slides, etc. Same about the ends.

---

I'm using ffmpeg. It's command line, but I can script it to my heart's content. In fact, I'm working on virtualscienceforum/automation#11 that would read the timestamps and cut the video.

**Comment by babaks77** [comment]
Yeah, we were stopping the recording. I'm doing a bit of trimming on the videos and they should be ready soon. For some reason the panel recording is a very big file with no apparent better quality.

>I'm using ffmpeg. It's command line, but I can script it to my heart's content. In fact, I'm working on virtualscienceforum/automation#11 that would read the timestamps and cut the video. 

That's nice. I worked a bit with ffmpeg some years ago (feels like a previous lifetime) but I think I'll have to start at the bottom of the learning curve for it again.

**Comment by akhmerov** [comment]
> Yeah, we were stopping the recording. I'm doing a bit of trimming on the videos and they should be ready soon. For some reason the panel recording is a very big file with no apparent better quality.

Ah OK. My stuff isn't ready yet (mostly in the starting phase) so if you have it—please go ahead.

**Comment by babaks77** [comment]
Hmm. For some reason the panel recording has a much bigger screen size, which I think is why the file is so much bigger. Looking for an easy way to size it down.

**Comment by akhmerov** [comment]
If your computer manages the whole thing, you can just let youtube compress it.

**Comment by babaks77** [comment]
Ah, good. Thanks!

**Comment by vfatemi** [comment]
@akhmerov  Post-conference email to registrants of Observing Anyons 2020: 

Subject: Observing Anyons 2020 – Recordings Now Online

Dear %recipient_name%, 
 
Thank you for helping to make Observing Anyons 2020 a successful event! We had over 550 registration and over 350 live participants from all over the world. 

The recordings of the talks are now online on the [conference webpage](https://virtualscienceforum.org/#/Observing_Anyons_2020). Alternatively, you can watch them on Virtual Science Forum’s [YouTube channel](https://www.youtube.com/channel/UCvQEx4iW7u_x3jX742kUZLw). Please [click here](https://www.youtube.com/playlist?list=PLqJ4D_Db7W_qtwTbN1dSAccyffU3xVz2R) to go directly to the playlist. 
 
Best regards,
Organizers
 
Maissam Barkeshli, University of Maryland (USA)
Valla Fatemi, Yale University (USA)
Babak Seradjeh, Indiana University at Bloomington (USA)

**Comment by akhmerov** [comment]
Scheduled for this to be sent tomorrow. Should we close the issue?

**Comment by babaks77** [comment]
Sounds good. Yes, I think we have finished all post-event tasks.
