### ISSUE TITLE
"Speakers' corner" seminar series

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#138]
I get a bit of an impression that online talks are becoming much like offline talks: you see all the same faces. Moreover since only little travel is involved higher profile speakers dominate even more. Additionally the bad tradition of reiterating same talks carries on.

To improve on that I propose to start a new seminar series that would work as follows:

- Anybody may present (following a minimal review)
- We automate everything as much as possible (making pages, recording videos, announcements)
- We provide some basic framework (e.g. recommend 30 minutes talk + long Q&A)
- We recommend to the speaker to bring their own audience, so that the events aren't very silent.

What do you think @virtualscienceforum?

**Comment by vfatemi** [comment]
I think this is a great idea. 

Perhaps part of the automated on-boarding process can be for the speaker to provide names and emails of those they wish to invite, so that VSF can (also) send out an invitation that includes a link to sign up for our mailing list.

**Comment by akhmerov** [comment]
I'll start outlining some technical details.

In order to run everything smoothly, we'd want to minimize human intervention. There are several things I imagine we will need to do:

- A separate mailing list and form-based mailing list sign-ups:
  - A cloudflare worker that stores mailgun API key in secrets, validates captcha, adds users to the list, and sends a welcome message.
  - A form embedded in the website that allows the users to sign up.
- Automation of the talk creation:
  - An issue template, that serves as a request for creating the talk and has all the necessary information.
  - Once all the information in the issue description is correct, a team member adds an "approved" label, and github actions triggers creating a zoom room and opening the pull request that updates the website page.
  - Once the pull request is merged, we schedule the mailing list announcement from the github action, possibly schedule a tweet, and notify the talk organizers with private information (here I'm not sure where we could obtain a way to contact the talk creator.
  - We then also schedule another action to obtain the recording credentials from zoom, send the author for approval, and publish to youtube.

So most of this relies on github actions to communicate with external services. Workers only maintain the mailing list.

**Comment by akhmerov** [comment]
@everthemore and I finished the mailing list sign-ups. The next steps are:

- The landing page #152 
- The applications template #153

**Comment by akhmerov** [comment]
Workflow:

---
Running the talk

- Applicant opens an issue
- Bot edits the issue description (checks arxiv preprint, adds extra data), and replies with validation check result
- Team member either responds with requests for changes, or adds an "approved" label
- Bot:
  - Creates a zoom meeting
  - Extends a yml file in the repository with a new entry corresponding to the talk
  - Updates the speaker's corner page base on the yaml with the talk info (by rendering a jinja2 template)
  - Responds to the issue with a checklist for the talk
  - Emails the applicant the host key for the talk
- Applicant runs the presentation
- Once the cloud recording is ready, bot:
  - Emails the recording link + password to the applicant
  - Responds in the issue with a request for publication approval and a request for time codes to cut off
- The applicant replies and approves the publication
- Bot:
  - Closes the issue
  - Edits and publishes the video on youtube
  - deletes the video on zoom
  - Updates the yaml with a recording link
  - Rebuilds the pages linking the recording

---

Updating host keys:

- The keys are generated by hashing account + date/time with long salt stored in automation secrets
- Bot runs a regular gh action to update the keys

---

Emailing

- A scheduled gh action reads the yaml, filters by date, renders another j2 template and sends an email to the mailing list.

**Comment by akhmerov** [comment]
The above is maximally automated, we should start with highest priority items (those that require most clicks).

**Comment by akhmerov** [comment]
We are going to keep iframe registration forms for now, but later we should switch to our own that use workers.

**Comment by akhmerov** [comment]
We should add tweeting with a hashtag and mentioning VSF, and VSF would retweet those tweet.

**Comment by everthemore** [comment]
Apart from adding the above to the speakerscorner page, we should decide on a good hashtag. Perhaps #speakerscornertalk to prevent general tweets about the #vsfspeakerscorner from being retweeted through the twitter bot?

**Comment by vfatemi** [comment]
Several times presenters forgot to claim host using the key. How to improve on that?
        * Send a short reminder email at t-2 hours
        * Explain why claiming host is important in the instructions (necessary to share screen). Include the need for an affirmative response that they must claim host and understand why.

**Comment by akhmerov** [comment]
I moved this to an issue of its own (this is the initial "meta" issue)

**Comment by akhmerov** [comment]
OK, this is finally done. Research seminars are still broken, but we track this in the automation repository.
