### ISSUE TITLE
VSF Organizational Meeting 15-09-2020 7pm CEST / 1pm EST

### ISSUE THREAD

**Issue by greplova** [virtualscienceforum/virtualscienceforum#148]
Zoom link:  https://virtualscienceforum-org.zoom.us/j/97339120210

Hackmd link for meeting minutes: https://hackmd.io/NZ0xRPthRDmavT_RP_hPUg

Proposed agenda:

- LRC Michel Devoret final checks
- LRC Pedram Roushan updates
- upcoming LRC invitations for 1 - 2 speakers
- Anyons 2020 updates
- Anyons 2020 align advertisement schedule (Q: should we develop standardised advert approach for conferences?)
- VSF Speaker's Corner updates
- next chair

Checklist:
- [x] Start recording on Zoom
- [x] Copy paste meeting notes to Wiki, title "YYYY-MM-DD Org Meeting"
- [x] Post Zoom recording to [YouTube channel](https://www.youtube.com/channel/UCvQEx4iW7u_x3jX742kUZLw) (use title "Organizational meeting YYYY-MM-DD" and add to the "Organizational meetings" playlist)
- [x] Close this issue

**Comment by vfatemi** [comment]
@greplova pinging you to put this one online.

**Comment by greplova** [comment]
thank you! couple of months too late but done :D
