### ISSUE TITLE
VSF Organizational Meeting 2020-09-29 7pm CEST / 1pm EST

### ISSUE THREAD

**Issue by everthemore** [virtualscienceforum/virtualscienceforum#154]
Zoom link:  https://virtualscienceforum-org.zoom.us/j/97339120210

Hackmd link for meeting minutes: https://hackmd.io/dCpnwU3qQfmadgTqyV5OIw

Proposed agenda:

* LRC Pedram Roushan final checks
* LRC future speakers
* Anyons 2020 update
    * Zoom room capacity
* Speaker's corner update
* Varia
    * AMA [#151](https://github.com/virtualscienceforum/virtualscienceforum/pull/151)
    * Zoom transcription test
    * Quantum transport mini-course
* Next chair

Checklist:
- [x] Start recording on Zoom
- [x] Copy paste meeting notes to Wiki, title "YYYY-MM-DD Org Meeting"
- [x] Post Zoom recording to [YouTube channel](https://www.youtube.com/channel/UCvQEx4iW7u_x3jX742kUZLw) (use title "Organizational meeting YYYY-MM-DD" and add to the "Organizational meetings" playlist)
- [x] Close this issue

**Comment by akhmerov** [comment]
@everthemore please use the VSF zoom (BTW you have admin right on VSF zoom account)

**Comment by everthemore** [comment]
I am sorry, I was unable to successfully process your data.
Please amend the following issues:

**Comment by everthemore** [comment]
I am sorry, I was unable to successfully process your data.
Please amend the following issues:

**Comment by everthemore** [comment]
I am sorry, I was unable to successfully process your data.
Please amend the following issues:

**Comment by everthemore** [comment]
I am sorry, I was unable to successfully process your data.
Please amend the following issues:

**Comment by everthemore** [comment]
I am sorry, I was unable to successfully process your data.
Please amend the following issues:

**Comment by everthemore** [comment]
I am sorry, I was unable to successfully process your data.
Please amend the following issues:

**Comment by babaks77** [comment]
I'd like to add "Zoom room capacity" under Anyons 2020.

**Comment by akhmerov** [comment]
> I'd like to add "Zoom room capacity" under Anyons 2020.

Oh... :)

**Comment by everthemore** [comment]
I can't access the cloud recordings to finish the checklist; is anyone able to help out with this?

**Comment by akhmerov** [comment]
You can do so via admin options, but you wouldn't be able to add it to youtube unless you also have access there. I'll do the upload.
