### ISSUE TITLE
Form validation action

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#157]
When an issue is opened from the speaker's corner template we should:

- Check that a preprint exists
- Grab all data from arxiv API
- Validate the date: sufficiently far into the future, no scheduling conflicts
- Grab the title and abstract, edit the issue description
- Grab all the authors, edit the issue description
- Reply to the issue with the validation results (reporting any potential problems)
- If the validation passes, open a checklist for the team member to confirm
- If the yaml has a zoom link, add a checklist for running the seminar (for the applicant)

---
Should run on:

- Issue opened / updated
- yaml with talks updated

**Comment by everthemore** [comment]
I would propose that this action runs a python or js script, which in turn uses the REST API of github to update the issue. It will need access to the repository to do so however. Alternatives would be external GitHub Apps. What say you @akhmerov?

**Comment by akhmerov** [comment]
Correct. We'll need to create a bot user, store its personal access token in the repository, and indeed use that token to interact with the API. However we wouldn't use the rest API directly, but rather https://github.com/PyGithub/PyGithub or any similar project.

I suggest to keep all our actions in Python—much easier to maintain than JS.
