### ISSUE TITLE
Testing Speakers' Corner [Babak - Take 3]

### ISSUE THREAD

**Issue by babaks77** [virtualscienceforum/virtualscienceforum#172]
## Name

Babak Seradjeh

## Email

babaks@indiana.edu

## Preprint ID

1908.06111

## Title

Dynamically Induced Topology and Quantum Monodromies in a Proximity
  Quenched Gapless Wire

## Abstract

We study the quench dynamics of a topologically trivial one-dimensional
gapless wire following its sudden coupling to topological bound states. We find
that as the bound states leak into and propagate through the wire, signatures
of their topological nature survive and remain measurable over a long lifetime.
Thus, the quench dynamically induces topological properties in the gapless
wire. Specifically, we study a gapless wire coupled to fractionally charged
solitons or Majorana fermions and characterize the dynamically induced topology
in the wire, in the presence of disorder and short-range interactions, by
analytical and numerical calculations of the dynamics of fractional charge,
fermion parity, entanglement entropy, and fractional exchange statistics. In a
dual effective description, this phenomenon is described by correlators of
boundary changing operators, which, remarkably, generate topologically
non-trivial monodromies in the gapless wire, both for abelian and non-abelian
quantum statistics of the bound states.

## Authors

Daniel Dahan, Eytan Grosfeld, Babak Seradjeh

## Time slot

2020-10-15 16:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speaker's corner seminar

**Comment by babaks77** [comment]
Thanks, vsf-bot!

**Comment by akhmerov** [comment]
approve publication (disregard this, just testing)

**Comment by akhmerov** [comment]
prove publication
