### ISSUE TITLE
Landau Quasiparticles in Weak Power-Law Liquids

### ISSUE THREAD

**Issue by jtheath** [virtualscienceforum/virtualscienceforum#175]
## Name

Joshuah T. Heath

## Affiliation

Boston College

## Email

heathjo@bc.edu

## Preprint ID

2001.08230

## Title

Landau Quasiparticles in Weak Power-Law Liquids

## Abstract

The failure of Landau-Fermi liquid theory is often considered a telltale sign
of universal, scale-invariant behavior in the emergent field theory of
interacting fermions. Nevertheless, there exist borderline cases where weak
scale invariance coupled with particle-hole asymmetry can coexist with the
Landau quasiparticle paradigm. In this letter, I show explicitly that a
Landau-Fermi liquid can exist for weak power-law scaling of the retarded
Green's function. Such an exotic variant of the traditional Fermi liquid,
although exhibiting a finite quasiparticle weight and large quasiparticle
lifetime, is shown to always be incompatible with Luttinger's theorem for any
non-trivial scaling. This result yields evidence for a Fermi liquid-like ground
state in the high-field, underdoped pseudogap phase of the high-temperature
cuprate superconductors.

## Authors

Joshuah T. Heath

## Time slot

2020-11-17 15:00 UTC

## Notes

Paper recently published in J. Low Temp Phys: https://link.springer.com/article/10.1007%2Fs10909-020-02515-1

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speaker's corner seminar

**Comment by akhmerov** [comment]
:tada: you're the first applicant! :tada: 

All looks good! We're finishing the rest of the infrastructure, and will return to you with the next steps. Cheers!

**Comment by akhmerov** [comment]
We've added your talk to the schedule :tada:!

Below please find a checklist for your presentation.  
Please read it carefully and confirm that everything is clear.  
Good luck with your talk!

## Before your meeting

- We will send you an email containing the meeting key and your join URL in a moment.
  **Confirm that you received the meeting key and URL by responding in this issue.**
- Install a [Zoom client](https://zoom.us/download). This is required for registration-only meetings.
- Test your setup on your own: check that your sound, video, and slide-sharing work.
- Announce the meeting to your colleagues: you know best who may be interested.

## During the meeting

- The meeting will be open for joining 5 minutes before the talk starts. Join at that time using the personal link we sent (don't be late!).
- Claim meeting host by using the host key that is in your email.
- Start the cloud recording by pressing the "record" button. 
- Start your presentation.
- Aim for a 40 minute presentation followed by 15 minutes discussion.
    - If another Speakers' Corner talk is scheduled immediately after your talk, your meeting will be shut down at 55 minutes on the hour.
    - If there isn't, you are free to use your time for up to 2 hours.

## After the meeting

- Once the recording is ready, we share a link to it and ask for your approval. 
- Once approved, the recording will be published at [the Speakers' Corner YouTube page](https://www.youtube.com/channel/UCvQEx4iW7u_x3jX742kUZLw)

**Comment by jtheath** [comment]
I confirm that I have received the Host key and the Zoom link for my talk on Tuesday, Nov. 17th, 2020 @ 15:00 UTC (11 a.m. EST)

**Comment by akhmerov** [comment]
Hey @jtheath!

I've a quick recommendation that we will include in the instructions to everyone: while the announcements are already in the mailing list, and on twitter, we also recommend to directly approach the colleagues that you think will be interested to hear your talk. This applies both to your local colleagues and people elsewhere who did relevant work.

The coverage of the mailing list and twitter isn't anywhere near complete, plus people always appreciate a personal touch.

Good luck with your tomorrow's talk!

**Comment by jtheath** [comment]
I approve publishing of the recording. Talk start is 00:00:00, talk end is 01:03:59.

**Comment by akhmerov** [comment]
The video is published, thank you for your contribution!
