### ISSUE TITLE
Conductance asymmetries in mesoscopic superconducting devices due to finite bias

### ISSUE THREAD

**Issue by andrenmelo** [virtualscienceforum/virtualscienceforum#176]
## Name

André Melo

## Affiliation

Kavli Institute of Nanoscience, Delft University of Technology

## Email

am@andremelo.org

## Preprint ID

2008.01734

## Title

Conductance asymmetries in mesoscopic superconducting devices due to
  finite bias

## Abstract

Tunneling conductance spectroscopy in normal metal-superconductor junctions
is an important tool for probing Andreev bound states in mesoscopic
superconducting devices, such as Majorana nanowires. In an ideal
superconducting device, the subgap conductance obeys specific symmetry
relations, due to particle-hole symmetry and unitarity of the scattering
matrix. However, experimental data often exhibits deviations from these
symmetries or even their explicit breakdown. In this work, we identify a
mechanism that leads to conductance asymmetries without quasiparticle
poisoning. In particular, we investigate the effects of finite bias and include
the voltage dependence in the tunnel barrier transparency, finding significant
conductance asymmetries for realistic device parameters. It is important to
identify the physical origin of conductance asymmetries: in contrast to other
possible mechanisms such as quasiparticle poisoning, finite-bias effects are
not detrimental to the performance of a topological qubit. To that end we
identify features that can be used to experimentally determine whether
finite-bias effects are the source of conductance asymmetries.

## Authors

André Melo, Chun-Xiao Liu, Piotr Rożek, Tómas Örn Rosdahl, Michael Wimmer

## Time slot

2020-11-20 15:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
Looks good! We're finishing the rest of the infrastructure, and will return to you with the next steps. Cheers!

**Comment by akhmerov** [comment]
We've added your talk to the schedule :tada:!

Below please find a checklist for your presentation.  
Please read it carefully and confirm that everything is clear.  
Good luck with your talk!

## Before your meeting

- We will send you an email containing the meeting key and your join URL in a moment.
  **Confirm that you received the meeting key and URL by responding in this issue.**
- Install a [Zoom client](https://zoom.us/download). This is required for registration-only meetings.
- Test your setup on your own: check that your sound, video, and slide-sharing work.
- Announce the meeting to your colleagues: you know best who may be interested.

## During the meeting

- The meeting will be open for joining 5 minutes before the talk starts. Join at that time using the personal link we sent (don't be late!).
- Claim meeting host by using the host key that is in your email.
- Start the cloud recording by pressing the "record" button. 
- Start your presentation.
- Aim for a 40 minute presentation followed by 15 minutes discussion.
    - If another Speakers' Corner talk is scheduled immediately after your talk, your meeting will be shut down at 55 minutes on the hour.
    - If there isn't, you are free to use your time for up to 2 hours.

## After the meeting

- Once the recording is ready, we share a link to it and ask for your approval. 
- Once approved, the recording will be published at [the Speakers' Corner YouTube page](https://www.youtube.com/channel/UCvQEx4iW7u_x3jX742kUZLw)

**Comment by akhmerov** [comment]
@andrenmelo please confirm if you received the email with the login link and the host key.

**Comment by andrenmelo** [comment]
@akhmerov Yes, got the email.

**Comment by andrenmelo** [comment]
I approve publishing of the recording. Talk start is 00:00:10, talk end is 00:39:00.

**Comment by akhmerov** [comment]
The video is published, thank you for your contribution!
