### ISSUE TITLE
Speakers' corner speaker checklist

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#179]
Once the talk is approved, the bot should respond to the speaker with a standard checklist of actions that explains how everything works.

I'll start writing some notes here, please chip in.

**Comment by akhmerov** [comment]
- You should receive an email with the link for you to join the meeting and the host key. **Let us know if you didn't**.
- You will be able to join the meeting around 5 minutes before its start.
- As soon as you join, claim the meeting host using the host key you received via email. "Claim host" option is available via the participants list.
- The meeting is recorded automatically, don't stop the recording. After the meeting you will be able to provide the timestamps in the recording that have to be removed before publication.
- We strongly recommend to limit your presentation to 40 minutes. The meeting will be closed automatically at 55' or after about 2 hours if the next reserved slot is free.

**Comment by everthemore** [comment]
As discussed during the organizational meeting on Oct 6th, a suggested change:

> * You should receive an email with the link for you to join the meeting and the host key. **Let us know if you didn't**.
> * You will be able to join the meeting around 5 minutes before its start.
> * As soon as you join, claim the meeting host using the host key you received via email. "Claim host" option is available via the participants list.
> * The meeting is recorded automatically, don't stop the recording. After the meeting you will be able to indicate sections that you would like to cut out before we proceed to publication of the video.
> * We strongly recommend to limit your presentation to 40 minutes. The meeting will be closed automatically at 55' or after about 2 hours if the next reserved slot is free.

We would then have the bot post another message with more details (e.g. the format of timestamps) about the cutting after the recording.
