### ISSUE TITLE
VSF Organizational Meeting 06-10-2020 7pm CEST / 1pm EST

### ISSUE THREAD

**Issue by giulia-pacchioni** [virtualscienceforum/virtualscienceforum#181]
Zoom link:  https://virtualscienceforum-org.zoom.us/j/97339120210

Hackmd link for meeting minutes: https://hackmd.io/0Puq-A-_SAKKt_H_2dTHuA

Proposed agenda:

- Debriefing on anyons mini conference
- Update on Brian's colloquium 
- Speaker's corner update
- Any other businness
- Next chair

Checklist:
- [x] Start recording on Zoom
- [x] Copy paste meeting notes to Wiki, title "YYYY-MM-DD Org Meeting"
- [x] Post Zoom recording to [YouTube channel](https://www.youtube.com/channel/UCvQEx4iW7u_x3jX742kUZLw) (use title "Organizational meeting YYYY-MM-DD" and add to the "Organizational meetings" playlist)
- [x] Close this issue

**Comment by babaks77** [comment]
For Speakers' Corner: Can we automate pushing announcements to researchseminars.org?

**Comment by akhmerov** [comment]
Thanks, I forgot to open an issue for that, fixed now: https://github.com/virtualscienceforum/automation/issues/19
