### ISSUE TITLE
Using skyrmionic racetracks for unconventional computing

### ISSUE THREAD

**Issue by fgen-avik** [virtualscienceforum/virtualscienceforum#182]
## Name

Hamed Vakili

## Affiliation

Dept. of Physics
University of Virginia

## Email

hv8rf@virginia.edu

## Preprint ID

2005.10704

## Title

Using skyrmionic racetracks for unconventional computing

## Abstract

Skyrmions are topological excitations in thin magnetic films with broken spatial symmetry, and can be driven at high speeds along magnetic racetracks using modest currents in heavy metal underlayers. However, they suffer strong Magnus forces arising from their vorticity. Eliminating these Magnus forces requires precise tuning of parameters that are hard to execute during fabrication. We show how Heusler ferrimagnetic racetracks can achieve high speeds and low damping. Instead of eliminating Magnus forces, we show how designing a spatially varying magnetic parameter, such as a graded PtxW1-x alloy, creates a moving skyrmion that keeps evolving into a growing hybrid between Bloch and Neel until it reaches an automatic compensation line where it self-converges into a racetrack. We can further tune the compensation line using a combination of static and gate-controlled dynamic magnetic anisotropy. Finally, we describe how the position of skyrmions along racetracks can be used as a native memory for temporal race logic that can be used for solving large graph theoretical problems.

## Authors

Hamed Vakili, Mohammad Nazmus Sakib, Samiran Ganguly, Mircea Stan, Matthew W. Daniels, Advait Madhavan, Mark D. Stiles, Avik W. Ghosh

## Time slot

2020-11-10 18:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
Ah, sorry, the bot is simple-minded and got confused by "arxiv:"

**Comment by akhmerov** [comment]
Already fixed.

**Comment by fgen-avik** [comment]
Thanks. Keeping the recommended author in the loop – Hamed, I signed you up for a potential talk on November 10 at 18:00 UTC
(2pm EDT).


Avik

--
Avik Ghosh
Professor
Dept of Electrical and Computer Engineering
Dept of Physics
University of Virginia
Ph: 434-243-2347 Fax: 434-924-8818
http://people.virginia.edu/~ag7rq/
https://engineering.virginia.edu/virginia-nano-computing-group-vino

**Comment by fgen-avik** [comment]
Thanks!!

--
Avik Ghosh
Professor
Dept of Electrical and Computer Engineering
Dept of Physics
University of Virginia
Ph: 434-243-2347 Fax: 434-924-8818
http://people.virginia.edu/~ag7rq/
https://engineering.virginia.edu/virginia-nano-computing-group-vino

**Comment by akhmerov** [comment]
We've added your talk to the schedule :tada:!

Below please find a checklist for your presentation.  
Please read it carefully and confirm that everything is clear.  
Good luck with your talk!

## Before your meeting

- We will send you an email containing the meeting key and your join URL in a moment.
  **Confirm that you received the meeting key and URL by responding in this issue.**
- Install a [Zoom client](https://zoom.us/download). This is required for registration-only meetings.
- Test your setup on your own: check that your sound, video, and slide-sharing work.
- Announce the meeting to your colleagues: you know best who may be interested.

## During the meeting

- The meeting will be open for joining 5 minutes before the talk starts. Join at that time using the personal link we sent (don't be late!).
- Claim meeting host by using the host key that is in your email.
- Start the cloud recording by pressing the "record" button. 
- Start your presentation.
- Aim for a 40 minute presentation followed by 15 minutes discussion.
    - If another Speakers' Corner talk is scheduled immediately after your talk, your meeting will be shut down at 55 minutes on the hour.
    - If there isn't, you are free to use your time for up to 2 hours.

## After the meeting

- Once the recording is ready, we share a link to it and ask for your approval. 
- Once approved, the recording will be published at [the Speakers' Corner YouTube page](https://www.youtube.com/channel/UCvQEx4iW7u_x3jX742kUZLw)

**Comment by akhmerov** [comment]
@fgen-avik I'd like to check back: did the speaker receive the recording link? If so, does he approve the publication of the recording?

**Comment by fgen-avik** [comment]
Hamed, can you respond to Prof. Akhmerov below?

Thanks,
Avik
--
Avik Ghosh
Professor
Dept of Electrical and Computer Engineering
Dept of Physics
University of Virginia
Ph: 434-243-2347 Fax: 434-924-8818
http://people.virginia.edu/~ag7rq/
https://engineering.virginia.edu/virginia-nano-computing-group-vino




From: Anton Akhmerov <       >
Reply-To: virtualscienceforum/virtualscienceforum <reply@reply.github.com>
Date: Monday, December 7, 2020 at 5:44 AM
To: virtualscienceforum/virtualscienceforum <virtualscienceforum@noreply.github.com>
Cc: "Ghosh, Avik (ag7rq)" <ag7rq@virginia.edu>, Mention <mention@noreply.github.com>
Subject: Re: [virtualscienceforum/virtualscienceforum] Using skyrmionic racetracks for unconventional computing (#182)


@fgen-avik<https://github.com/fgen-avik> I'd like to check back: did the speaker receive the recording link? If so, does he approve the publication of the recording?

**Comment by hamedvakili** [comment]
I approve publishing of the recording. Talk start is 00:00:10, talk end is 00:48:53.

**Comment by akhmerov** [comment]
The video is published, thank you for your contribution!

**Comment by fgen-avik** [comment]
Thank u Anton

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
