### ISSUE TITLE
Antonio Manesco - arXiv:2003.05163

### ISSUE THREAD

**Issue by antoniolrm** [virtualscienceforum/virtualscienceforum#188]
## Name

Antonio Manesco

## Affiliation

University of São Paulo

## Email

antoniolrm@usp.br

## Preprint ID

2003.05163

## Title

Correlations in the elastic Landau level of spontaneously buckled graphene

## Abstract

Electronic correlations stemming from nearly flat bands in van der Waals materials have demonstrated to be a powerful playground to engineer artificial quantum matter, including superconductors, correlated insulators and topological matter. This phenomenology has been experimentally observed in a variety of twisted van der Waals materials, such as graphene and dichalcogenide multilayers. Here we show that spontaneously buckled graphene can yield a correlated state, emerging from an elastic pseudo Landau level. Our results build on top of recent experimental findings reporting that, when placed on top of hBN or NbSe$_2$ substrates, wrinkled graphene sheets relax forming a periodic, long-range buckling pattern. The low-energy physics can be accurately described by electrons in the presence of a pseudo-axial gauge field, leading to the formation of sublattice-polarized Landau levels. Moreover, we verify that the high density of states at the zeroth Landau level leads to the formation of a periodically modulated ferrimagnetic groundstate, which can be controlled by the application of external electric fields. Our results indicate that periodically strained graphene is a versatile platform to explore emergent electronic states arising from correlated elastic Landau levels.

## Authors

Antonio L. R. Manesco, Jose L. Lado, Eduardo V. S. Ribeiro, Gabrielle Weber, Durval Rodrigues Jr

## Time slot

2020-11-09 15:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by antoniolrm** [comment]
Date added to the [schedule](https://virtualscienceforum.org/#/speakers-corner?id=schedule) is not right.

**Comment by akhmerov** [comment]
Already fixed. Was a visual bug (I was showing the day of the week and not the day of the month :D).

**Comment by antoniolrm** [comment]
Thanks!

**Comment by akhmerov** [comment]
We've added your talk to the schedule :tada:!

Below please find a checklist for your presentation.  
Please read it carefully and confirm that everything is clear.  
Good luck with your talk!

## Before your meeting

- We will send you an email containing the meeting key and your join URL in a moment.
  **Confirm that you received the meeting key and URL by responding in this issue.**
- Install a [Zoom client](https://zoom.us/download). This is required for registration-only meetings.
- Test your setup on your own: check that your sound, video, and slide-sharing work.
- Announce the meeting to your colleagues: you know best who may be interested.

## During the meeting

- The meeting will be open for joining 5 minutes before the talk starts. Join at that time using the personal link we sent (don't be late!).
- Claim meeting host by using the host key that is in your email.
- Start the cloud recording by pressing the "record" button. 
- Start your presentation.
- Aim for a 40 minute presentation followed by 15 minutes discussion.
    - If another Speakers' Corner talk is scheduled immediately after your talk, your meeting will be shut down at 55 minutes on the hour.
    - If there isn't, you are free to use your time for up to 2 hours.

## After the meeting

- Once the recording is ready, we share a link to it and ask for your approval. 
- Once approved, the recording will be published at [the Speakers' Corner YouTube page](https://www.youtube.com/channel/UCvQEx4iW7u_x3jX742kUZLw)

**Comment by antoniolrm** [comment]
Everything is clear and I received the URL. Thanks!

**Comment by antoniolrm** [comment]
I approve publishing of the recording. Talk start is 00:00:03, talk end is 00:31:45.

**Comment by akhmerov** [comment]
The video is published, thank you for your contribution!
