### ISSUE TITLE
Topological Band Structures in the Offset-Parameter-Dependence of Small Josephson Circuits

### ISSUE THREAD

**Issue by vfatemi** [virtualscienceforum/virtualscienceforum#193]
## Name

Valla Fatemi

## Affiliation

Yale University

## Email

valla.fatemi@yale.edu

## Preprint ID

2008.13758

## Title

Topological Band Structures in the Offset-Parameter-Dependence of Small Josephson Circuits

## Abstract

We introduce Weyl Josephson circuits: small Josephson junction circuits that simulate Weyl band structures. We first formulate a general approach to design circuits that are analogous to Bloch Hamiltonians of a desired dimensionality and symmetry class. We then construct and analyze a six-junction device that produces a 3D Weyl Hamiltonian with broken inversion symmetry and in which topological phase transitions can be triggered \emph{in situ}. We argue that currently available superconducting circuit technology allows experiments that probe topological properties inaccessible in condensed matter systems.

## Authors

Valla Fatemi, Anton R. Akhmerov, Landry Bretheau

## Time slot

2020-11-17 17:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
We've added your talk to the schedule :tada:!

Below please find a checklist for your presentation.  
Please read it carefully and confirm that everything is clear.  
Good luck with your talk!

## Before your meeting

- We will send you an email containing the meeting key and your join URL in a moment.
  **Confirm that you received the meeting key and URL by responding in this issue.**
- Install a [Zoom client](https://zoom.us/download). This is required for registration-only meetings.
- Test your setup on your own: check that your sound, video, and slide-sharing work.
- Announce the meeting to your colleagues: you know best who may be interested.

## During the meeting

- The meeting will be open for joining 5 minutes before the talk starts. Join at that time using the personal link we sent (don't be late!).
- Claim meeting host by using the host key that is in your email.
- Start the cloud recording by pressing the "record" button. 
- Start your presentation.
- Aim for a 40 minute presentation followed by 15 minutes discussion.
    - If another Speakers' Corner talk is scheduled immediately after your talk, your meeting will be shut down at 55 minutes on the hour.
    - If there isn't, you are free to use your time for up to 2 hours.

## After the meeting

- Once the recording is ready, we share a link to it and ask for your approval. 
- Once approved, the recording will be published at [the Speakers' Corner YouTube page](https://www.youtube.com/channel/UCvQEx4iW7u_x3jX742kUZLw)

**Comment by vfatemi** [comment]
I have received the meeting key and URL.

**Comment by vfatemi** [comment]
I approve publishing of the recording. Talk start is 00:00:03, talk end is 00:49:33.

**Comment by akhmerov** [comment]
The video is published, thank you for your contribution!
