### ISSUE TITLE
LRC page cleanup

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#195]
We accumulate a lot of colloquia over time; we should think of how to reorganize the page so that it stays usable.

**Comment by vfatemi** [comment]
Perhaps archive by calendar year.

**Comment by akhmerov** [comment]
Maybe remove old talks from the schedule and have a separate table linking to recordings (the recordings themselves would be on a separate page to avoid long scrolling etc)?

**Comment by vfatemi** [comment]
I was thinking more of subpages archiving each calendar year. The subpages could be in essentially the same format as the current page with the compact table at the top which links to the embedded videos below.

**Comment by vfatemi** [comment]
Should also update YouTube videos to include talk titles and abstracts.

**Comment by giulia-pacchioni** [comment]
I have added titles and abstracts to both the YouTube channel and to the colloquium page, which is ready to become our 2020 archive page. For next year, I suggest listing talks in reverse temporal order, with the oldest ones at the bottom of the page both in the table and in the recordings list.

**Comment by akhmerov** [comment]
closed via #274
