### ISSUE TITLE
"add LRC seminar listing to researchseminars.org" as LRC checklist item

### ISSUE THREAD

**Issue by vfatemi** [virtualscienceforum/virtualscienceforum#201]
See title. I haven't done this before so I don't know what it entails. The checklist item should include instructions or a link to instructions. I've assigned Babak and Anton since I believe they have interacted with this website before.

**Comment by akhmerov** [comment]
For a reference, all the issue templates are in this folder: https://github.com/virtualscienceforum/virtualscienceforum/tree/master/.github/ISSUE_TEMPLATE, and this is the one in question: https://github.com/virtualscienceforum/virtualscienceforum/blob/master/.github/ISSUE_TEMPLATE/PresentationChecklist.md

**Comment by babaks77** [comment]
I made the change.
