### ISSUE TITLE
draft general announcement email for Speakers' Corner

### ISSUE THREAD

**Issue by vfatemi** [virtualscienceforum/virtualscienceforum#202]
subject: "Launch of the self-invited seminar series: Speakers' Corner"
from: VSF team <no-reply@mail.virtualscienceforum.org>
to: speakers_corner
---

Dear %recipient_name%, 

We are launching a new initiative called Speakers' Corner. Named after the renowned corner of Hyde Park in London, the Speakers' Corner seminars are a platform for everyone who would like to share their research—in a way it is arXiv for talks. Do you or someone you know have a new preprint and want to create an accompanying video lecture or just share a new result with the community?

Speakers' Corner allows you to create, advertise, record, and share your talk via the Virtual Science Forum platform on a "self-invited" basis. To learn more, apply to give a talk, or register for one of the upcoming seminars, please visit the [Speakers' corner page](https://virtualscienceforum.org/#/speakers-corner).

Our first upcoming talks are:
{% for talk in talks | sort(attribute="time")%}
- {{ talk.time.strftime("%B %-d") }}: *{{ talk.title }}* by {{ talk.speaker_name }} ({{ talk.speaker_affiliation }})  
{%- endfor %}

Because you indicated that you are interested in hearing about VSF events, we have signed you up for a weekly announcement of the Speakers' corner talks. If you wish to opt-out from weekly updates, you may do so [here](%mailing_list_unsubscribe_url%). 

Best regards,  
The VSF Organizers

**Comment by giulia-pacchioni** [comment]
Looks very good to me!

**Comment by akhmerov** [comment]
Indeed, looks godd. A few suggestions:

- mention the email update frequency
- add a section with the talks already planned. I'll add the talks based on data, but please add the text describing this
- use `%recipient_name% for name, and `%mailing_list_unsubscribe_url%` for unsubscribe link.
- add a bullet list with email subject and "from" field.

Also in order to make this more similar to the automated email workflow, please move the email text in the top level issue description and move all comments about the content to the comments below (so that the issue description only has the email itself).

**Comment by vfatemi** [comment]
What specifically should I write in the "from" field?

**Comment by vfatemi** [comment]
Is the unsubscribe link specific to speakers' corner, or general VSF mailing lists?

**Comment by vfatemi** [comment]
Could use some suggestions for the subject line.

**Comment by akhmerov** [comment]
> Is the unsubscribe link specific to speakers' corner, or general VSF mailing lists?

The unsubscribe link is specific to the mailing list that receives the email (and doesn't mean anything if the email is sent to meeting registrants).

> What specifically should I write in the "from" field?

It may be anything really, for an event announcement it could be the event email. But here the default is quite fine.

> Could use some suggestions for the subject line.

Yours looks good. Can also do something like "Launch of the self-invited seminar series: Speakers' Corner".

**Comment by vfatemi** [comment]
I like the subject line you suggested and have implemented it.

**Comment by akhmerov** [comment]
Let's add a note that they are also welcome to invite others to present.

**Comment by akhmerov** [comment]
Done, and also mentioned "arxiv for talks"
