### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by bp432** [virtualscienceforum/virtualscienceforum#212]
## Name

Bo Peng

## Affiliation

Cavendish Laboratory, University of Cambridge

## Email

bp432@cam.ac.uk

## Preprint ID

arXiv:2011.06269

## Title

Topological phonons in oxide perovskites controlled by light

## Abstract

Perovskite oxides exhibit a rich variety of structural phases hosting different physical phenomena that generate multiple technological applications. We find that topological phonons – nodal rings, nodal lines, and Weyl points – are ubiquitous in oxide perovskites in terms of structures (tetragonal, orthorhombic, and rhombohedral), compounds (BaTiO3, PbTiO3, and SrTiO3), and external conditions (photoexcitation, strain, and temperature). In particular, in the tetragonal phase of these compounds all types of topological phonons can simultaneously emerge when stabilized by photoexcitation, whereas the tetragonal phase stabilized by thermal fluctuations only hosts a more limited set of topological phonon states. In addition, we find that the photoexcited carrier concentration can be used to tune the topological phonon states and induce topological transitions even without associated structural phase changes. Overall, we propose oxide perovskites as a versatile platform in which to study topological phonons and their manipulation with light.

## Authors

Bo Peng, Yuchen Hu, Shuichi Murakami, Tiantian Zhang, Bartomeu Monserrat

## Time slot

2020-12-02 16:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by bp432** [comment]
Yes we put it on Cambridge repository rather than arXiv. But technically it is still a preprint.

**Comment by akhmerov** [comment]
Thanks for the clarification. We use arXiv to verify submissions. We'll discuss what to do with cases like yours on a technical level, and get back to you shortly.

**Comment by akhmerov** [comment]
Disregard the last message, you're in the schedule.

**Comment by bp432** [comment]
Thanks for this!

**Comment by akhmerov** [comment]
@bp432 sorry about the repeated emails with talk link—there was a bug, which I now fixed. Please use the latest link for your talk (you should have received it about now).

**Comment by bp432** [comment]
I confirm that I have received the email. Thank you very much!

> 
> 
> We've added your talk to the schedule tada!
> 
> Below please find a checklist for your presentation.
> Please read it carefully and confirm that everything is clear by adding a comment to this issue.
> Also reply here if you have any questions or problems.
> Good luck with your talk!
> ## Before your meeting
> 
>     * We will send you an email containing the meeting key and your join URL in a moment.
>       **Confirm that you received the meeting key and URL by responding in this issue.**
> 
>     * Install a [Zoom client](https://zoom.us/download). This is required for registration-only meetings.
> 
>     * Test your setup on your own: check that your sound, video, and slide-sharing work.
> 
>     * **Announce the meeting to your colleagues and invite them to register for the talk**.
> 
>     * We will include your talk in the VSF mailing list announcement. If you like you can also tweet at @VirtualSciForum with the hashtag #VSFSpeakersCorner and we will retweet information about your talk.
> 
> 
> ## During the meeting
> 
>     * The meeting will be open for joining 5 minutes before the talk starts. Join at that time using the personal link we sent (don't be late!).
> 
>     * Claim meeting host by using the host key that is in your email.
> 
>     * The recording starts automatically as soon as you join. Don't stop it; you may pause it, but don't forget to unpause.
> 
>     * Tell your audience how the questions will be organized. Can they ask questions during the talk or only at the end? How should they signal they have a question?
> 
>     * Start your presentation.
> 
>     * Aim for a 40 minute presentation followed by 15 minutes discussion.
>       
>       * If another Speakers' Corner talk is scheduled immediately after your talk, your meeting will be shut down at 55 minutes on the hour.
>       * If there isn't, you are free to use your time for up to 2 hours.
> 
> 
> ## After the meeting
> 
>     * Once the recording is ready, we share a link to it and ask for your approval.
> 
>     * Once approved, the recording will be published at [the Speakers' Corner YouTube page](https://www.youtube.com/channel/UCvQEx4iW7u_x3jX742kUZLw)

I confirm that I have received the email! Thank you very much!

**Comment by bp432** [comment]
> 
> 
> @bp432 sorry about the repeated emails with talk link—there was a bug, which I now fixed. Please use the latest link for your talk (you should have received it about now).

I got plenty of emails lol

**Comment by bp432** [comment]
I approve publishing of the recording. Talk start is 00:08:30, talk end is 00:50:35.

**Comment by akhmerov** [comment]
The video is published, thank you for your contribution!
