### ISSUE TITLE
Speakers' corner talk application - Brown Zak fermions

### ISSUE THREAD

**Issue by julienbarrier** [virtualscienceforum/virtualscienceforum#213]
## Name

Julien Barrier

## Affiliation

The University of Manchester, U.K.

## Email

julien.barrier@manchester.ac.uk

## Preprint ID

2006.15040

## Title

Long-range ballistic transport of Brown-Zak fermions in graphene superlattices

## Abstract

In quantizing magnetic fields, graphene superlattices exhibit a complex fractal spectrum often referred to as the Hofstadter butterfly. It can be viewed as a collection of Landau levels that arise from quantization of Brown-Zak minibands recurring at rational ($p/q$) fractions of the magnetic flux quantum per superlattice unit cell. Here we show that, in graphene-on-boron-nitride superlattices, Brown-Zak fermions can exhibit mobilities above 10$^6$ cm$^2$V$^{-1}$s$^{-1}$ and the mean free path exceeding several micrometers. The exceptional quality of our devices allows us to show that Brown-Zak minibands are $4q$ times degenerate and all the degeneracies (spin, valley and mini-valley) can be lifted by exchange interactions below 1K. We also found negative bend resistance at $1/q$ fractions for electrical probes placed as far as several micrometers apart. The latter observation highlights the fact that Brown-Zak fermions are Bloch quasiparticles propagating in high fields along straight trajectories, just like electrons in zero field.

## Authors

Julien Barrier, Piranavan Kumaravadivel, Roshan Krishna-Kumar, L. A. Ponomarenko, Na Xin, Matthew Holwill, Ciaran Mullan, Minsoo Kim, R. V. Gorbachev, M. D. Thompson, J. R. Prance, T. Taniguchi, K. Watanabe, I. V. Grigorieva, K. S. Novoselov, A. Mishchenko, V. I. Fal'ko, A. K. Geim, A. I. Berdyugin

## Time slot

2020-11-24 16:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
@julienbarrier please confirm if you received the email and whether the instructions are clear.

**Comment by julienbarrier** [comment]
> @julienbarrier please confirm if you received the email and whether the instructions are clear.

No I haven't received the e-mail containing the zoom link + host key, yet.

**Comment by akhmerov** [comment]
Oops, I'll investigate what's wrong and fix it in a moment.

**Comment by akhmerov** [comment]
@julienbarrier the email with your login link and host key should have been delivered to your email now, please check again.

**Comment by julienbarrier** [comment]
I received it, thanks!

**Comment by julienbarrier** [comment]
I approve publishing of the recording. Talk start is 00:01:06, talk end is 00:39:03.

**Comment by akhmerov** [comment]
The video is published, thank you for your contribution!
