### ISSUE TITLE
VSF Organizational Meeting 03 November 2020 7pm CEST / 1pm EST

### ISSUE THREAD

**Issue by giulia-pacchioni** [virtualscienceforum/virtualscienceforum#214]
Zoom link:  https://virtualscienceforum-org.zoom.us/j/97339120210

Hackmd link for meeting minutes: https://hackmd.io/4F9NtyZhTaSha8IbOeCeUA

Proposed agenda:

- LRC colloquium checks
-- Do we want to introduce the new Zoom breakout rooms?
- Speakers' Corner updates
-- What do do if paper is not on the arXiv?
- Any other businness
- Next chair

[Proivde a list of items. Be sure to include - Next chair? ]

Checklist:
- [x] Start recording on Zoom
- [x] Copy paste meeting notes to Wiki, title "YYYY-MM-DD Org Meeting"
- [x] Post Zoom recording to [YouTube channel](https://www.youtube.com/channel/UCvQEx4iW7u_x3jX742kUZLw) (use title "Organizational meeting YYYY-MM-DD" and add to the "Organizational meetings" playlist)
- [x] Close this issue

**Comment by akhmerov** [comment]
Also funding update
