### ISSUE TITLE
Introduction to computational quantum transport with Kwant

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#215]
## Organizers

- Christoph Groth
- Xavier Waintal
- Michael Wimmer
- Anton Akhmerov

## Description

In this four-hour workshop we will introduce the basics of quantum transport simulations of mesoscopic devices using the Kwant software package.
Our entry-level workshop is aimed at active condensed matter physicics who have a basic knowledge of Python.
We do not expect familiarity with Kwant or quantum transport simulations.

The workshop will begin with a brief introduction of the essential theoretical background, followed by hands-on examples of quantum transport simulations.
During the ensuing interactive sessions the participants will directly apply what they have learned and receive immediate feedback.
We will conclude with an overview of advanced topics which will be left for later self-study.

## List of potential speakers 

- Christoph Groth
- Xavier Waintal
- Michael Wimmer
- Anton Akhmerov
- Pablo Piskunov
- Daniel Varjas
- Thomas Kloss
- Bas Nijholt

## Preferred date and time slot

2020-12-17 15:00–19:00 CET

## Additional remarks

This is a course rather than a conference session, so most of the speakers are internal.

**Comment by akhmerov** [comment]
For additional information, here's our internal checklist:

- 11/19 Assemble the course team
- 11/19 Prepare a repository and define the structure
- Decide on participant/instructor ratio
- 11/19 Finalize the schedule (at least rough schedule)
- 11/26 Publish the event page
    - Decide whether we want to ask additional questions on registration
    - Open call for assistants to join
- 11/26 Make a blog post and mailing list announcements
- 12/10 Prepare the materials
- 12/15 Review the materials
- 12/15 Infrastructure/software test
- 12/17 Run the event
- Debrief
- 12/19 Wrap up, update Kwant website and VSF event page

**Comment by vfatemi** [comment]
Your assigned VSF rep is Valla Fatemi.

**Comment by akhmerov** [comment]
Lagging behind the schedule a bit, here's our planning document: https://hackmd.io/YyU_cVLKRbOQGZAj2a0ovQ

**Comment by akhmerov** [comment]
Remaining TODO items:

- [ ] remove the registration and move the event to past events
- [ ] publish the videos
- [ ] update the workshop page
- [ ] email the workshop participants a link to the finalized page and the survey

**Comment by akhmerov** [comment]
The workshop is over, page updated, so this is all done, closing :tada:
