### ISSUE TITLE
VSF Organizational Meeting 2020-11-10 7pm CEST / 1pm EST

### ISSUE THREAD

**Issue by babaks77** [virtualscienceforum/virtualscienceforum#219]
Zoom link:  https://virtualscienceforum-org.zoom.us/j/97339120210

Hackmd link for meeting minutes: https://hackmd.io/YdB5eCR3RwiZ4_i2MyfkRA

Proposed agenda:

- LRC prep
- Speakers' Corner Update
- Update of previous action items 
  - Zoom breakout rooms
- New events?
- Next chair?

Checklist:
- [x] Start recording on Zoom
- [x] Copy paste meeting notes to Wiki, title "YYYY-MM-DD Org Meeting"
- [x] Post Zoom recording to [YouTube channel](https://www.youtube.com/channel/UCvQEx4iW7u_x3jX742kUZLw) (use title "Organizational meeting YYYY-MM-DD" and add to the "Organizational meetings" playlist)
- [x] Close this issue

**Comment by akhmerov** [comment]
@babaks77 what's the status of this issue?

**Comment by babaks77** [comment]
Working on completing it.
