### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by mimigdal** [virtualscienceforum/virtualscienceforum#222]
## Name

Dalla Torre Emanuele

## Affiliation

Bar-Ilan University

## Email

emanuele.dalla-torre@biu.ac.il

## Preprint ID

2005.07207

## Title

Statistical Floquet prethermalization from kicked rotors to the Bose-Hubbard model

## Abstract

The manipulation of many-body systems often involves time-dependent forces that cause unwanted heating. One strategy to suppress heating is to use time-periodic (Floquet) forces at large frequencies. In particular, for quantum spin systems with bounded spectra, it was shown rigorously that the heating rate is exponentially small in the driving frequency. Recently, the exponential suppression of heating has also been observed in an experiment with ultracold atoms, realizing a periodically driven Bose-Hubbard model. This model has an unbounded spectrum and, hence, is beyond the reach of previous theoretical approaches. Here, we develop a semiclassical description of Floquet prethermal states and link the suppressed heating rate to the low probability of finding many particles on a single site. We derive an analytic expression for the exponential suppression of heating valid at strong interactions and large temperatures, which matches the exact numerical solution of the model. Our approach demonstrates the relevance of statistical arguments to Floquet perthermalization of interacting many-body quantum systems.

## Authors

Emanuele G. Dalla Torre

## Time slot

2020-12-08 10:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by mimigdal** [comment]
Dear VSF,
I have received the email containing the host password and everything seems in place.
Can you please confirm that an email about the talk has been sent to the VSF mailing list?
See you later!
Best,
Emanuele

**Comment by akhmerov** [comment]
Hi Emanuele! Indeed, the talk was announced via the weekly mailing list posting.

**Comment by mimigdal** [comment]
Excellent. Thanks!

**Comment by mimigdal** [comment]
I approve publishing of the recording. Talk start is 00:00:14, talk end is 00:35:20

**Comment by akhmerov** [comment]
The video is published, thank you for your contribution!

**Comment by mimigdal** [comment]
Thank you! Best regards, Emanuele
