### ISSUE TITLE
VSF Organizational Meeting 2020-11-17 7pm CEST / 1pm EST

### ISSUE THREAD

**Issue by giulia-pacchioni** [virtualscienceforum/virtualscienceforum#225]
Zoom link:  https://virtualscienceforum-org.zoom.us/j/97339120210

Hackmd link for meeting minutes: https://hackmd.io/YWjMki57QKemHv5V2lW4Ug

Proposed agenda:

- LRC prep
- Speakers' Corner Update
- Next chair?

Checklist:
- [x] Start recording on Zoom
- [x] Copy paste meeting notes to Wiki, title "YYYY-MM-DD Org Meeting"
- [x] Convert all action points to issues, assign or mention the relevant people
- [x] Post Zoom recording to [YouTube channel](https://www.youtube.com/channel/UCvQEx4iW7u_x3jX742kUZLw) (use title "Organizational meeting YYYY-MM-DD" and add to the "Organizational meetings" playlist)
- [x] Close this issue

**Comment by akhmerov** [comment]
My proposals for more agenda items:

- #215
- Auto-opening of org issues
- Speakers' corner tweaks, based on observations
- #224 #223
