### ISSUE TITLE
Send email to announce André's talk is delayed by an hour

### ISSUE THREAD

**Issue by andrenmelo** [virtualscienceforum/virtualscienceforum#227]
subject:  Schedule change for Speakers' Corner talk on Friday 20/11
from: VSF team <no-reply@mail.virtualscienceforum.org>
to: 99801126781
---
Dear %recipient_name%,

Due to a schedule conflict André Melo's talk ("Conductance asymmetries in mesoscopic superconducting devices due to finite bias") will take place at 16:00 UTC, one hour later than originally planned. 

Best regards,
The VSF Organizers

**Comment by akhmerov** [comment]
Fixed the date and removed the header.
