### ISSUE TITLE
Set up automatic recordings of Spearkers' Corner talks

### ISSUE THREAD

**Issue by giulia-pacchioni** [virtualscienceforum/virtualscienceforum#228]
Action point from today's meeting.

We should ask speakers to pause the recording if they wish, but not stop it, and to provide timestamps so the video can be trimmed before publication. 

@akhmerov or @everthemore you want to take this as you are the automation wizards?

**Comment by akhmerov** [comment]
The actual title is "automation goblins", and I've turned it on now (https://github.com/virtualscienceforum/automation/commit/a55e25aa9cd5c33722af58056b6e9a8adf0ca51e).

This will apply to all *newly scheduled* talks, so we still need to update the instructions (let's use #234 for that).

We should also decide what to do with the talks that are scheduled now: we can either let them be, or manually change the meetings and update the instructions.

**Comment by akhmerov** [comment]
I think there is only one "old" talk remaining, so we can close this.
