### ISSUE TITLE
Prepare template email to provide to Speakers' Corner presenters

### ISSUE THREAD

**Issue by giulia-pacchioni** [virtualscienceforum/virtualscienceforum#230]
Action point from today's meeting.

We should provide presenters with a template email to advertise their talk. This will be helpful for less-experienced speakers, but also make it clearer that we expect them to spread the word.

@babaks77 @greplova you seemed interested in this topic, maybe you want to prepare a draft :)

**Comment by greplova** [comment]
First draft of announcement here: https://github.com/virtualscienceforum/virtualscienceforum/blob/master/texts/SpeakersCornerTemplate.md

**Comment by everthemore** [comment]
Merged
