### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by vvadimov** [virtualscienceforum/virtualscienceforum#236]
## Name

Vasilii Vadimov

## Affiliation

QCD Labs, Department of Applied Physics, Aalto University

## Email

vasilii.1.vadimov@aalto.fi

## Preprint ID

2011.06552

## Title

Many-body Majorana-like zero modes without gauge symmetry breaking

## Abstract

Topological superconductors represent one of the key hosts of Majorana-based topological quantum computing. Typical scenarios for one-dimensional topological superconductivity assume a broken gauge symmetry associated to a superconducting state. However, no interacting one-dimensional many-body system is known to spontaneously break gauge symmetries. Here, we show that zero modes emerge in a many-body system without gauge symmetry breaking and in the absence of superconducting order. In particular, we demonstrate that Majorana zero modes of the symmetry-broken superconducting state are continuously connected to these zero-mode excitations, demonstrating that zero-bias anomalies may emerge in the absence of gauge symmetry breaking. We demonstrate that these many-body zero modes share the robustness features of the Majorana zero modes of symmetry-broken topological superconductors. We introduce a bosonization formalism to analyze these excitations and show that a ground state analogous to a topological superconducting state can be analytically found in a certain limit. Our results demonstrate that robust Majorana-like zero modes may appear in a many-body systems without gauge symmetry breaking, thus introducing a family of protected excitations with no single-particle analogs.

## Authors

V. Vadimov, T. Hyart, J. L. Lado, M. Möttönen, T. Ala-Nissila

## Time slot

2020-12-09 13:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
@vvadimov sorry about the repeated emails with the talk link—there was a bug, which I now fixed. Please use the latest link for your talk (you should have received it about now).

**Comment by vvadimov** [comment]
@akhmerov I confirm that I received the email with my meeting information.

**Comment by vvadimov** [comment]
@akhmerov due to some technical difficulties the talk was given in another zoom meeting, the link to the recording is https://www.dropbox.com/sh/2k2h0nm4xspvo1h/AADqk_bDVVT4_iX5ITvFidfra?dl=0 , I approve publishing of the record.

**Comment by akhmerov** [comment]
The video is published, thank you for your contribution!
