### ISSUE TITLE
VSF Organizational Meeting 2020-11-24 7pm CEST / 1pm EST

### ISSUE THREAD

**Issue by greplova** [virtualscienceforum/virtualscienceforum#241]
Zoom link: https://virtualscienceforum-org.zoom.us/j/97339120210

Hackmd link for meeting minutes: https://hackmd.io/@greplova/HkE2p599D/edit

Proposed agenda:

- LRC updates + 2021 planning
- Speakers' Corner Update
- More discussion items? 
- Next chair

Checklist:
- [x] Start recording on Zoom
- [x]  Copy paste meeting notes to Wiki, title "YYYY-MM-DD Org Meeting"
- [x] Convert all action points to issues, assign or mention the relevant people
- [x] Post Zoom recording to YouTube channel (use title "Organizational meeting YYYY-MM-DD" and add to the "Organizational meetings" playlist)
- [x]  Close this issue

**Comment by akhmerov** [comment]
Let's use #238 (or close it)
