### ISSUE TITLE
LRC webpage 2021

### ISSUE THREAD

**Issue by greplova** [virtualscienceforum/virtualscienceforum#245]
Setup the new website for LRC 2021. Switching to automated version (a la Speaker's Corner) would be ideal.

**Comment by vfatemi** [comment]
Not only ideal, but automation will be done!

**Comment by akhmerov** [comment]
A quick status update. The next steps are:

- Update the workflow issue for adding the talk data.
- Update the page for publication

**Comment by everthemore** [comment]
We should also update the rendering for the speakers corner to filter out the speakers corner event types

**Comment by akhmerov** [comment]
Hashtag future-proof https://github.com/virtualscienceforum/virtualscienceforum/blob/master/bots/render_talks.py#L27 ;)

**Comment by everthemore** [comment]
Sweet, completely missed that

**Comment by akhmerov** [comment]
alright, everything works, but may be a bit rough on the edges.

**Comment by akhmerov** [comment]
Now everything should be in place. We should also improve the text, but this we should track from a different issue.
