### ISSUE TITLE
Open Science Fund / Innovation Fund application

### ISSUE THREAD

**Issue by everthemore** [virtualscienceforum/virtualscienceforum#249]
Application for max EUR 50.000 for 1y, deadline 18 May 2021
https://www.nwo.nl/en/calls/open-science-fund-2020/2021

This issue is meant to collect ideas for what to apply for. Discussed so far:

- Hire someone to work on VSF backend and frontend (integrate w/ arXiv, update website, etc)
- Pay for professional website (few thousands of EUR)

**Comment by akhmerov** [comment]
We're also considering https://www.aps.org/programs/innovation/fund/

**Comment by greplova** [comment]
Innovation fund application doc: https://docs.google.com/document/d/1tQWuVy7V_TjeRcHcyd1BdOSCtsgiNJmdKLIv7YF6YvM/edit?usp=sharing

**Comment by akhmerov** [comment]
Here's what I submitted for the record. Due to a lack of time, I had no chance to solicit feedback, so apologies for the rough state :crossed_fingers: :sunglasses: 

[NWO_OSF_Akhmerov.pdf](https://github.com/virtualscienceforum/virtualscienceforum/files/6501057/NWO_OSF_Akhmerov.pdf)

I'm closing this for now, will reopen if we need any follow-up action, e.g. for the IF.

**Comment by akhmerov** [comment]
Since @babaks77 was informed that we were selected for the full proposal round of the IF, I'm reopening the issue. @babaks77 please add the detailed information here once you have it.

On my side I received a notification that my proposal is eligible and will be considered. Here's the timeline:

- May 18th, 2021      Deadline for submitting applications
- May-June, 2021      Eligibility check by NWO staff
- Mid-June, 2021      Pre-selection meeting
- ~5-9 July, 2021     Possibility for reaction applicant
- September, 2021     Selection committee meeting
- October, 2021  Decision NWO Executive Board

**Comment by babaks77** [comment]
Innovation Fund full proposal deadline is July 1. They will send more information later this week. For now, the application site shows we need
* Application, including
  * Executive Summary (3-4 sentence)
  * Background/Motivation (< 500 words)
  * Project Details (< 1000 words)
  * A list of Project Deliverables (outcomes/milestones) and timeline
  * Assessment Strategy (< 750 words)
  * Sustainability Plan (< 500 words)
  * APS Role/Expectations (APS staff time and resources needed; < 250 words)
  * Additional Information (eg. PI experience; < 500 words)
  * Budget Justification (< 750 words)
* Budget Spreadsheet
* CVs
* Letters of Support (optional)

**Comment by adelatorreduran** [comment]
**Summary of  Innovation Fund Committee (IFC) comments (in no particular order):**

- This must complement APS Meetings and IT department activities and align with their strategic directions.

- Provide support for the claim that there is a huge untapped need for this service.

- Describe metrics to evaluate its efficacy.

- Provide more justification for the budget. Consult with APS Meetings to gain a clear view of the costs and quality of online platforms that the broad physics community is expecting. This budget and the staffing does not seem robust enough unless there is a revenue structure that runs alongside it.
                        -  If this is intended to become a profit generating activity, please describe the envisioned governance and operational structure.

- Provide details about the current architecture of the platform, the specific enhancements you plan to make, and how this will be sustained in the long run. Note the resources needed to scale it up.

- Address any knowledge sharing (code sharing for instance) you would be willing to do and how you might see this helping serve APS meeting needs better than the already established platforms APS is using or experimenting with. 

- Make a case for why the hosting platform is the best long-term repository for meeting content and discuss how this activity complements the mission of APS.


**We encourage you to reach out directly to the following individuals to discuss your proposal** (Contacts were provided).

**The deadline for submission of the full proposal is Thursday, July 1 at noon ET. Please be aware that the review committee will likely request that you provide brief written responses to a short list of remaining questions to guide their final decision making. You should expect to receive these questions on August 9 with a response deadline of August 16.**

**Comment by adelatorreduran** [comment]
From Org Meeting 2021-06-04:

The first two points above seem to be the hardest to address.
The largest priority is consulting the APS employees we were advised to contact.
We can provide letters of support.
We should also reach out via Twitter/email/LRCs.
A good idea to mention creating a nonprofit and a timeline for this.

**Comment by babaks77** [comment]
IU Research Admin office timeline
![APS-IF_IU-timeline](https://user-images.githubusercontent.com/35002137/120110828-387fd680-c13d-11eb-848b-252e67b06261.jpg)

**Comment by greplova** [comment]
notes from the full proposal planning meeting: https://hackmd.io/JFrUeB6SQZ6fVhN9oYAJoQ?both

**Comment by sentefmi** [comment]
Google doc:
https://docs.google.com/document/d/13a2Gkol68ScbgLQe8yFWuSZ59ZrBBXTw9KKwzSlTRik/edit#

**Comment by sentefmi** [comment]
@babaks77 We should follow up by writing to the APS folks indidually if we do not hear back by Monday

**Comment by adelatorreduran** [comment]
Useful answers from the APS Director of Meetings (bold) to some of our questions:

- Collaboration with APS meetings. For example, VSF can organize a virtual component of an APS meeting that would run over a longer time frame to accommodate different time zones and constraints of the online format. In this respect, what are the APS plans for virtual or hybrid meetings in the future? **Virtual Events are here to stay. We have actually hired a Virtual Events Manager to oversee these events as we go forward. While there is certainly siginificant demand to continue face-to-face meetings (mainly for the serendiptious collaboration and networking that occurs), we recognize that offering a virtual component of the larger in-person meetings will enable others who would not come to the live meeting to attend virtually. Also, in some cases virtual meetings will replace some of the smaller meetings that have typically been held in person.**

- Along these lines, we are convinced that there is a need in the community for a scientific presentation platform akin to arXiv. We would like to ask your opinion on this and how we could advertise this proposal and expand our current efforts to the APS community **There are several companies that offer these services and the American Chemical Society is offering such a service to other scientifc organizations.  I beleieve that the idea has merit but I am not familiar enough with arXiv to make a judgement on a similar model for meetings content. As far as advertsing to the APS community is concerned, each APS unit has the potential to have content to add to such a platform, some with a greater volume than others.**

- What metrics has APS used to evaluate success during/after the most recent online March Meeting? **We did a survey of attendees after the meeting. Many attendees were pleased with the virtual meeting. As with any event, there were lessons learned to take forward for our next virtual event. Of interest was the Net Promoter Score which was a -9. That is the current average score for all virtual meetings across all industries (not just scirentific meetings). We beleive that is a result of an audience that is over saturated with virtual meetings of all kinds. In other words, people are ready to return to face-to-face meetings. That said, it is our intent to offer a virtual component to all future in person meetings. There were many who expressed that they would like for their content to be accessible beyond the 90 days that the virtual platform offered.**

- Data management would be fundamental in the long-term success of this proposal. Our content is currently hosted on YouTube. However, the recent decision by Google to run ads on all hosted videos, has prompted a discussion about how and where to host our recorded events and seminars. What are your thoughts on this? What has been identified as the best solution for data management of scientific publications and any recorded content at the APS? **We are currently exploring content repositories that will be searchable and have DOIs for our meetings video recordings. Two companies we will be exploring futher are Morressier and Cadmore.**

**Comment by babaks77** [comment]
Budget is approved by IU research office.

**Comment by akhmerov** [comment]
@babaks77 can you please let everyone with link comment/view the proposal (for sharing with colleagues)?

**Comment by akhmerov** [comment]
Closing, while we wait for the evaluation.

**Comment by babaks77** [comment]
IF not selected by the APS. Here is the relevant part of the feedback:

> The Innovation Fund Committee acknowledges that dissemination of knowledge and inclusion/access is highly aligned with the APS Strategic Plan. Throughout the proposal, it was clear that the PIs understood the appeal of the arXiv approach and desired to leverage this for research talks and conferences. However, it was unclear if the motivations and needs of the current and potential future users were well understood, and several aspects of the volunteer-led initiative did not appear to have a viable sustainability plan, particularly if use increased.
> 
> APS Information Systems – Mark Doyle in particular – would welcome this PI team to keep in touch so that you can share with each other what you're all learning in developing video platforms for meetings.

**Comment by akhmerov** [comment]
Too bad. On the other hand, it's decent that we can keep in touch. May come in handy.

**Comment by akhmerov** [comment]
For completeness, I attach the motivation letter here:

[203.001.170 Akhmerov.pdf](https://github.com/virtualscienceforum/virtualscienceforum/files/7587660/203.001.170.Akhmerov.pdf)

Largely the comments are about the amount of detail and the clarity of the plan.
