### ISSUE TITLE
Quantum Oscillations in Insulators

### ISSUE THREAD

**Issue by brianqskinner** [virtualscienceforum/virtualscienceforum#251]
## Organizers

Brian Skinner (https://physics.osu.edu/people/skinner.352)
Suchitra Sebastian (https://www.phy.cam.ac.uk/directory/sebastians)
Yun Suk Eo (https://vector.umd.edu/people/item/9-yun-suk-eo.html)

## Description

In 2015 the Cambridge group reported the mysterious observation of quantum (de Haas-van Alphen) oscillations in the electrically insulating material samarium hexaboride (SmB6). This finding presented an apparent paradox, since quantum oscillations usually indicate a Fermi surface of electrons, which is at odds with the lack of electrical conduction. This surprising finding kicked off a flurry of activity, including a range of experimental studies of SmB6 and a variety of theories proposing various mechanisms for forming a Fermi surface of charge-neutral quasiparticles. While our understanding of SmB6 as a material has advanced significantly, the central mystery of the origin of the oscillations does not have a consensus solution.

Very recently, however, experiments have uncovered similar phenomenology -- quantum oscillations coinciding with electrical insulation -- in other materials, including ytterbium boron 12 and tungsten ditelluride. These new observations may be the key to a breakthrough in understanding this phenomenon.

Our workshop aims to bring together the key experimental and theoretical leaders in the question of quantum oscillations in insulators. To our knowledge, there has never been a conference, workshop, or focus session devoted to the topic of quantum oscillations in insulators, and we hope that bringing this community together can help to resolve this prominent scientific mystery.

## List of potential speakers 

Our tentative goal is to host six talks across four hours and two days -- two hours each day.
Our list of potential speakers includes:
Suchitra Sebastian (Cambridge University)
Colin Broholm (Johns Hopkins)
Lu Li (University of Michigan)
Sanfeng Wu (Princeton University)
T. Senthil (MIT)
Joel Moore (as a discussion moderator, Berkeley)
Priscila Rosa (Los Alamos)
Patrick Lee (MIT)

## Preferred date and time slot

Feb. 18 and 19, 10am - 12pm US EST

## Additional remarks (if any)

We would like this to be a two-day event, with two hours of talks and discussion each day.

**Comment by akhmerov** [comment]
Hey @brianqskinner! Sounds like a cool event! I'll be keeping an eye on your preparations and helping with technical matters.

I'm about to run my own workshop #247, so I'll also have fresh first hand information about the necessary steps and potential problems. The workshop is in a week, which also means that I'm going to be rather busy until that time. As the first step, I suggest making a rough timeline for yourself. The key deadlines are:

- Gathering all the speakers
- Making the event page
- Announcing the event and opening the registration

It's helpful to reserve at least 2 or better 3 weeks for the announcement. Preparing the event page takes little effort—it may be as short as your description + the schedule + a registration form. This still gives you plenty of time to prepare.

**Comment by brianqskinner** [comment]
Great, thanks Anton! We have already started issuing invitations to the
speakers.

Regarding the website + registration form, is that something that we do
through github? Or is it up to us how we want to do it?
I apologize up front that I may have a number of very naive questions as
this process continues, since I have never used github before.

There's no real urgency (yet), so feel free to get back to me after your
own workshop is over.

Thanks,
Brian

**Comment by akhmerov** [comment]
Aight, I'm (almost) done with my own workshop, so I'd be happy to walk you through the process in one of the coming days (I'll contact you elsewhere for planning a time).

If a single page for the event is enough for you, I suggest indeed doing it via github—you don't need much more information than e.g. [here](https://virtualscienceforum.org/#/quantum-transport-workshop). If you want, I can prepare a draft based on your submission above, and I will of course guide you through the process of tweaking.

We will take care scheduling the Zoom meeting and of adding the registration form to the event page.

When the page is up and running, you'll want to prepare emails with announcements, see [here](https://github.com/virtualscienceforum/virtualscienceforum/blob/master/texts/email_instructions.md) for instructions.

**Comment by brianqskinner** [comment]
Thanks Anton! I'll do this in the next few days.  All of our first-choice
speakers have agreed and committed to a time slot, so putting together the
schedule + website should be quite easy.

-Brian

**Comment by brianqskinner** [comment]
Hi Anton,

We now have a finalized workshop schedule, and would like to send out an
announcement email. But I am somehow having trouble navigating github, both
for the purpose of updating the website and composing the announcement
email.

Do you have ~10 minutes to chat some time either tomorrow (Friday) or over
the weekend?

Sorry for my relative incompetence.  I should be free all day except for
3:30-4:30pm EST.

-Brian

**Comment by akhmerov** [comment]
Sure thing, let's talk at 11 EST in [this zoom room](https://tudelft.zoom.us/j/93861503228?pwd=eC9EbjMvODRWbmtjWVErK210MGtNUT09).

In the meantime, [here](https://github.com/virtualscienceforum/virtualscienceforum/issues/new?assignees=&labels=email&template=email.md) you can start editing your email announcement, and [here](https://github.com/brianqskinner/virtualscienceforum/edit/patch-1/quantum-oscillations-insulators.md?pr=%2Fvirtualscienceforum%2Fvirtualscienceforum%2Fpull%2F268) you can edit your proposed program page.

**Comment by brianqskinner** [comment]
Hi Anton,

We are having a small issue, in that a number of people have results and
comments that are relevant for the workshop, but we don't have time in the
program to accommodate them. So we were thinking of inviting another set of
people to record ~10 minute talks, and we will post them on the workshop
web page a few days before the workshop starts.

Is there any logistical impediment to doing this? Probably the easiest
thing is to ask people to upload the talk to YouTube, and then we can embed
the talks on the web page. (I understand that you can also password-protect
YouTube videos, so if the speakers only want to share their talk with
conference attendees that should be possible.)

At the moment we are thinking of inviting ~12 people, which will lead to
maybe 4-5 actual submissions.

-Brian

PS  Do you know how many people have registered so far?

**Comment by akhmerov** [comment]
Sounds cool! No problem with the logistics. Some points to consider:

- You may also consider inviting people for satellite [speakers' corner](virtualscienceforum.org/#/speakers-corner) talks (speakers corner talks can be easily processed and publisehd within a day)
- We usually prefer to keep the materials perpetually and publicly available, so if possible, public videos w/o protection would be better.
- We can also publish the recorded videos via the VSF youtube channel in case some contributors don't want to create their own channel.

Let me know what you think

**Comment by brianqskinner** [comment]
Thanks Anton.  Regarding the VSF youtube channel, how would that work
logistically?  Would the speaker send you a video file that you upload? Or
would you grant the speaker's personal account access to the VSF youtube
channel?

**Comment by akhmerov** [comment]
> Regarding the VSF youtube channel, how would that work logistically? 

The file (shared via e.g. a dropbox or a similar servicei public link) + extra information (name, affiliation, title, abstract).

**Comment by akhmerov** [comment]
Hi @brianqskinner, just a quick check: did you decide what you'd like to do with the videos?

**Comment by brianqskinner** [comment]
Hi Anton,

In the end we invited a limited group of people to record their talks, so
that we can host them on the web page. I expect that we'll have somewhere
between 4 and 8 entries. I recommended for everyone to keep it short (in
the style of a 10-minute March Meeting talk), but I don't intend to enforce
time limits.

I asked people to submit their videos by next Friday, Feb. 12. They have
the option of either posting the video on youtube on their own channel, or
sending us a video file that we can upload to the VSF channel.

I'm hoping that we can post them on the web page on Monday, Feb. 15 or so.
I haven't received any submissions yet.

Thanks,
Brian

**Comment by brianqskinner** [comment]
Hi Anton,

I am starting to get some submissions for "contributed talks" that we want
to add to the web page of the workshop. The plan is to upload these talks
to the VSF channel, right? Can you help me with this?

I am putting them in this Google Drive folder:
https://drive.google.com/drive/folders/1qsVOz2FkkeS3g-Eq5L-qn_Hgw-1GO39K?usp=sharing

Thanks,
Brian

**Comment by akhmerov** [comment]
Hey Brian,

Yes, indeed, that's the plan. As a quick check: the presenters agree to the publication of the videos, is that correct?

If yes, I propose the following: I create the event playlist on the VSF youtube channel, you provide the desired talk titles, I upload the videos, and we embed the talk videos in the event page. Does that sound reasonable? Do you expect more contributions?

**Comment by brianqskinner** [comment]
Hi Anton,

Yes, when we announced this recorded session we made clear that the talks
would be posted on youtube.

Your plan sounds good. We gave people a deadline of Feb. 12 (today) for
their submission, so maybe we can wait until tomorrow to finalize the
playlist.  I will send you all the information.
At the moment we have five submissions -- three uploaded in the Google
Drive folder that I linked to, and two more that have been posted on
youtube by the speakers directly.

-Brian

**Comment by brianqskinner** [comment]
Hi Anton,

It looks like all the talks are in now.  There are six in total -- two that
have been uploaded directly to youtube:
https://www.youtube.com/watch?v=BqhF5Ic8E1g
https://www.youtube.com/watch?v=5YKtNYs1e2Q
and four more four in the Google Drive folder:
https://drive.google.com/drive/folders/1qsVOz2FkkeS3g-Eq5L-qn_Hgw-1GO39K?usp=sharing

Here is a suggested playlist, along with titles:

   - Kin Fai Mak, Cornell University: *Quantum oscillations in 2D
   insulators induced by graphite gates*
   - Jeff Sonier, Simon Fraser University: *Intrinsic low-energy magnetic
   excitations detected in SmB6 by μSR*
   - Cagliyan Kurdak, University of Michigan: *Bulk Transport Through
   Defects in Floating Zone and Al-flux-grown Samarium Hexaboride*
   - Patrick LeBarre, University of California Santa Cruz: *Evidence for
   Specific Heat Quantum Oscillations in SmB6*
   - Valentin Leeb, Technical University Munich: *Anomalous Quantum
   Oscillations in a Heterostructure of Graphene on a Proximate Quantum Spin
   Liquid*
   - Chandra Varma, University of California Berkeley: *Majoranas in Mixed
   Valence Insulators*

Thanks,
Brian

**Comment by akhmerov** [comment]
Alright, here's the playlist: https://www.youtube.com/playlist?list=PLqJ4D_Db7W_prRSWig2Nq-OBTDNxvZ9IC let me know if you'd like to change anything.

Some other final preparations:

- Should we embed the videos in the workshop page?
- Let's prepare a reminder announcement to send a few hours before the event
- In order to ensure that you have access to the moderation controls of the meeting I'd like to add you to the VSF zoom account (temporarily). This requires an email address that isn't associated with any other zoom account. Shall I use your gmail?

**Comment by brianqskinner** [comment]
Hi Anton,

The playlist looks great. Yes, let's go ahead and embed these videos on the
web page (perhaps just below the workshop program). We have been calling
this the "Late-breaking session".

One question: I would like to send an email to the participants today or
tomorrow, informing them that these talks have been posted, and encouraging
people to watch them in advance of the live sessions. Is that possible?

I will draft a separate reminder email to send shortly before the event.

And yes, my gmail account (brianqskinner@gmail.com) is a good one to use,
and is not associated with any other zoom account.

Thanks,
Brian

**Comment by akhmerov** [comment]
I've added the videos to the page, check it out. Also made you an alternative host of the conference meeting. This still means that you'll need to manually designate other organizers and speakers as cohosts, but other than that you're set.

To email the participants, use this issue form: https://github.com/virtualscienceforum/virtualscienceforum/issues/new?assignees=&labels=email&template=email.md (this goes for both the announcement of the extra videos and and any other communication.

Please put the meeting ID 92595407988 in the "to" field in the issue. Also don't worry to mess anything up, these are only sent after my approval.

**Comment by brianqskinner** [comment]
Thanks Anton, it looks great.
I just drafted an announcement email, if it looks okay to you then you can
send it out.

Thanks,
Brian

**Comment by brianqskinner** [comment]
Hi Anton,

Sorry to bug you, but we have a late submission to the "late-breaking
session". Would you mind adding it to the end of the playlist and the
bottom of the list on the web page?

The file has been uploaded to the Google Drive:
https://drive.google.com/file/d/1TeO7D4hN3Ku72WCgAJkbvTP7758F0d-2/view?usp=sharing
"SingletonTalk.mp4"
The talk can be listed as:
John Singleton, Los Alamos: *Survival of neutral fermions into the
high-magnetic-field Kondo-metal state of YbB_{12}*

Thank you!

-Brian

**Comment by akhmerov** [comment]
Done, it's live.

**Comment by brianqskinner** [comment]
!

What quick service! Where do I fill out the feedback form expressing my
customer satisfaction?
:)

**Comment by akhmerov** [comment]
https://virtualscienceforum.org/#/?id=join-us :)

**Comment by brianqskinner** [comment]
Hi Anton,

I made a draft of an announcement email to be sent out tomorrow (around
8:30 am EST / 14:30 CET) before the workshop begins.  If it looks okay to
you, then go ahead and prepare it to be sent.
Sorry that I didn't know how to properly insert the name or registration
link in markup.

Dear %name%,

Thank you for registering for the Quantum Oscillations in Insulators
workshop, which begins today in one and a half hours (10:00 AM EST / 16:00
CET).

You can join using your %registration link%.

Click (here)[
https://virtualscienceforum.org/#/quantum-oscillations-insulators] to see
the program of the workshop, and to watch the talks that have been already
uploaded as part of the "Late-breaking session".

Remember that the workshop takes place over two days, and will continue
tomorrow beginning at the same time. You can use the %same registration
link% to access the workshop tomorrow.

See you soon,
The workshop organizers

Thanks,
Brian

**Comment by akhmerov** [comment]
please use a separate issue for preparing the email: https://github.com/virtualscienceforum/virtualscienceforum/issues/new?assignees=&labels=email&template=email.md (it's the same procedure as with the previous one)

Once again, please put the meeting ID 92595407988 in the "to" field in the issue.

**Comment by brianqskinner** [comment]
Done, sorry about that.

**Comment by brianqskinner** [comment]
Hi Anton,

It just occurred to me that we should probably send a reminder email for
the second day of the workshop, with the link posted again.
I just issued another draft for an announcement email to be sent
immediately. Go ahead and send it if it looks okay to you.

Thanks,
Brian

**Comment by akhmerov** [comment]
Hey Brian!

Happy that the workshop was successful! I shared the recording links via email. In order to publish the videos, I would like the following input from you.

For each video please provide the following:

- Title (<100 charachters)
- Description (optional, but preferable since the title is really short)
- Name of the recording from zoom ("Recording 1–6)
- A list of segments you want to include in the format `HH:MM:SS–HH:MM:SS`

The participants and the workshop organizers also remarked that the chats are useful to preserve in some form. This will take some more thought. So far I think that the raw chats are too unstructured to be directly useful (especially since it will be hard to find accompanying video context). What do you think making a separate write-up or a video summary of the discussion, which would be based on the chat remarks?

After the recordings are published, we should embed them in the event page, and send a final email to the participants.

Does this plan sound good?

**Comment by brianqskinner** [comment]
Hi Anton,

You sent me two different links, both of which had files labeled "Recording
1/2/3". So I hope that the information listed below is clear:

From the first day (Feb. 18):

Title: "Bulk Fermi surfaces in bulk unconventional insulators"
Description: Suchitra Sebastian of Cambridge University provides an
overview of the experimental evidence for a Fermi surface of neutral
fermions within the bulk of the Kondo insulators SmB<sub>6</sub> and
YbB<sub>12</sub>.
"Recording 1"
segments to include: 00:00:10 - 00:41:15

Title: "Magnetism in SmB<sub>6</sub>"
Description: Collin Broholm of Johns Hopkins University gives an overview
of what is known about intrinsic and extrinsic sources of magnetism in
SmB<sub>6</sub>.
"Recording 2"
segments to include: 00:00:30 - 00:38:54

Title: "Quantum Oscillations in Resistivity and Magnetization of Insulators"
Description: Lu Li from the University of Michigan describes quantum
oscillations of magnetization in SmB<sub>6</sub> and of both magnetization
and resistance in YbB<sub>12</sub>. The two materials are compared and
contrasted, and emphasis is given to the aspects where there is not yet an
experimental consensus.
"Recording 3"
segments to include: 00:00:06 - 00:41:53

From the second day (Feb. 19):

Title: "Intrinsic Landau Quantization in WTe<sub>2</sub> Insulators"
Description: Sanfeng Wu of Princeton University discusses recent
measurements of quantum oscillations of resistivity in the insulating state
of monolayer WTe<sub>2</sub>. Particular attention is given to the question
of whether the oscillations could arise from the graphite gate underneath
the sample.
"Recording 1"
segments to include: 00:00:06 - 00:41:04

Title: "Quantum oscillations in the resistivity of an excitonic insulator"
Description: Patrick Lee of MIT discusses a theoretical mechanism that can
give rise to quantum oscillations in an excitonic insulator, with a focus
on WTe<sub>2</sub>. He also provides a brief overview of different
mechanisms proposed to explain the quantum oscillations in SmB<sub>6</sub>.
"Recording 2"
segments to include: 00:00:00 - 00:17:11

Title: "Panel discussion"
Description: An open-ended panel discussion considers the question of what
are the most promising avenues for new experimental and theoretical work to
resolve the mystery of quantum oscillations in insulating materials.
Panelists are Leslie Schoop, G. Baskaran, Piers Coleman, Nigel Cooper, and
T. Senthil. The discussion is moderated by Arthur Ramirez.
"Recording 3"
segments to include: 00:00:04 - 01:09:49

The issue of what to do about the chat is tricky. Part of what made them
valuable is that participants were debating each other: lobbying for
different viewpoints and rebutting each others' statements. It would be
hard for a writeup or summary to do justice to this exchange, although it
could perform the more limited service of collecting the references that
people brought up.

There is also the issue that, while the speakers explicitly consented to
having their talks recorded, the users of the chat did not explicitly agree
to have their comments preserved and made public. So maybe it isn't okay to
post their comments without getting them to agree to it.
On the other hand, apparently anyone in the zoom call had the ability to
download and save the chat file already (and I think a few participants did
so).

Perhaps the first step is for myself and the other organizers can look at
the recorded chat and try to decide whether we can make a useful summary of
things that happened there.

-Brian

**Comment by brianqskinner** [comment]
Hi Anton,

Regarding the chat, maybe the simplest thing to do is just to provide a
copy of the chat for all registered attendees.  Since the chat was visible
to all of them, and they all had the ability to download and save it on
their own, I don't think there is any issue of needing people's consent to
distribute the chat to just the attendees.

What do you think?

-Brian

**Comment by brianqskinner** [comment]
Hi Anton,

Do you have a projected timeline for when the talks from the workshop will
be posted online?  At this point I have received a half-dozen or so emails
from people asking when they will be able to watch the talks online.

Thanks,
Brian

**Comment by akhmerov** [comment]
Online in the playlist (was delayed due to teaching). Would you be able to include these in the workshop page?

**Comment by brianqskinner** [comment]
Thank you, Anton! And sorry to pester you when you are trying to teach.

I embedded the talks on the web page, and also drafted an email
announcement. If both look okay to you then you can approve them. (Web page
first, then send the email.)

Thanks again for everything.

-Brian

**Comment by akhmerov** [comment]
> I embedded the talks on the web page

I can't see that, you need to make a pull request first.

**Comment by brianqskinner** [comment]
Sorry. How about now?

**Comment by brianqskinner** [comment]
Uh oh, there is a mistake that I need to fix before you send the email.

**Comment by akhmerov** [comment]
Oh, sorry, saw this too late :(

**Comment by akhmerov** [comment]
If it's a mistake in the page, we can still fix it though—no problem

**Comment by brianqskinner** [comment]
Okay, it should be good to go now. I just made another pull request.

**Comment by akhmerov** [comment]
Great! I think we're all set, or do you plan to do something with the chat log?

**Comment by brianqskinner** [comment]
In the end, we couldn't decide what to do with the chat log, and we weren't
confident that it would be okay with the participants if we posted it
anywhere. So we are just keeping it for our own records, and I guess that
if anyone writes to ask for it then we can share it privately.

Thanks again for everything! I guess that at this point we can officially
say that workshop-related activities are over.

-Brian

**Comment by akhmerov** [comment]
Yep, makes sense.

I'm closing this issue. If you have any feedback, let me know or drop by directly at our Tuesday meeting.
