### ISSUE TITLE
LRC reminder email

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#254]
subject: email subject
from: VSF team <no-reply@mail.virtualscienceforum.org>
to: 99408575470
---
Dear %recipient_name%,

Thank you for registering for today's Long Range Colloquium by Deji Akinwande! The talk will begin in four hours (19:30 CET / 1:30 PM EST).
As usual, we will have an informal chat about research with Deji Akinwande starting a bit earlier—15 minutes before the talk. You are very welcome to join!

Your can join using your [registration link](%recipient.join_url%).

The title and the abstract of the talk are below.

**Title:** 2D materials: From atoms to applications

**Abstract:** This talk will present our latest research adventures on 2D nanomaterials towards greater scientific understanding and advanced engineering applications. In particular, the talk will highlight our work on flexible electronics, zero-power devices, monolayer memory (atomristors), non-volatile RF switches, and wearable tattoo sensors. Non-volatile memory devices based on 2D materials represent an application of defects and are a rapidly advancing field with rich physics that can be attributed to sulfur vacancies or metal diffusion. Atomistic modeling and atomic-resolution imaging are contemporary tools used to elucidate the memory phenomena in these systems. Likewise, from a practical point of view, electronic tattoos based on graphene have ushered a new material platform that has highly desirable practical attributes including optical transparency, mechanical imperceptibility, and is the thinnest conductive electrode sensor that can be integrated on skin for physiological measurements.

See you soon,  
The Virtual Science Forum team

**Comment by akhmerov** [comment]
@virtualscienceforum/core this is the reminder announcement for the colloquium. Please add the "approved" label about 4 hours before the colloquium for the email to be sent (@giulia-pacchioni want to do the honors?).

![image](https://user-images.githubusercontent.com/2069677/101611711-20d75900-3a0a-11eb-9f29-d9a4d5184ccb.png)

**Comment by giulia-pacchioni** [comment]
Sure, thanks!
