### ISSUE TITLE
improve LRC book-keeping

### ISSUE THREAD

**Issue by vfatemi** [virtualscienceforum/virtualscienceforum#260]
Babak will put together a method for combining wiki+github issues for LRC invitations, scheduling, etc

**Comment by babaks77** [comment]
This is done, old wiki page is [archived](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers-2020-%5BArchived%5D), a new LRC speakers wiki page [created](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers), and added item to the LRC speakers checklist to keep the wiki page up to date.
