### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by AbhiPhy2020** [virtualscienceforum/virtualscienceforum#265]
## Name

Abhishek Kumar

## Affiliation

Indiana University Bloomington

## Email

ak24@iu.edu

## Preprint ID

2012.09677

## Title

Floquet Gauge Pump

## Abstract

We introduce the concept of a Floquet gauge pump whereby a dynamically engineered Floquet Hamiltonian is employed to reveal the inherent degeneracy of the ground state in interacting systems. We demonstrate this concept in a one-dimensional XY model with periodically driven couplings and transverse field. In the high frequency limit, we obtain the Floquet Hamiltonian consisting of the static XY and dynamically generated Dzyaloshinsky-Moriya interaction (DMI) terms. The dynamically generated magnetization current depends on the phases of complex coupling terms, with the XY interaction as the real and DMI as the imaginary part. As these phases are cycled, it reveals the ground state degeneracies that distinguish the ordered and disordered phases. We discuss experimental requirements needed to realize the Floquet gauge pump in a synthetic quantum spin system of interacting trapped ions.

## Authors

Abhishek Kumar, Gerardo Ortiz, Philip Richerme, Babak Seradjeh

## Time slot

2021-01-21  17:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
@AbhiPhy2020 can you please confirm that you:

- received an email with your login link and the host key
- read the instructions

**Comment by AbhiPhy2020** [comment]
Hi, 
Sorry for the late response. I have received an email with the login link and the host key. 
Also, I have read the instructions.

Thanks!

**Comment by AbhiPhy2020** [comment]
I approve publishing of the recording. Talk start is 00:05:20, talk end is 00:42:18.

**Comment by akhmerov** [comment]
The video is published at https://youtu.be/Vh7dllQ6-FM

Cheers!
