### ISSUE TITLE
Announce video availability of quantum transport workshop

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#267]
subject: "Quantum transport workshop: recordings and survey"
from: The workshop team <no-reply@mail.virtualscienceforum.org>
to: 92046730124
---
Dear %recipient_name%,

We have now processed the videos of the quantum transport mini-workshop and made them available together with the workshop materials on the [workshop page](https://virtualscienceforum.org/#/quantum-transport-workshop).

If you attended the workshop, we are very interested to hear about your experience and ideas, so please fill out this short (1-2 minute) [survey](https://forms.gle/R8DTbhipG48LCsdH8).

Happy 2021,  
The workshop organizers

**Comment by akhmerov** [comment]
@vfatemi (as the contact person) can you please take a look and add the "approved" label if all looks good?

**Comment by vfatemi** [comment]
@akhmerov looks fine, although "looking back" is a bit vague in the subject so it might be good to include the specific content of the email, a la "quantum transport workshop: recordings online + survey", or something to that effect

**Comment by akhmerov** [comment]
Thanks, good point.
