### ISSUE TITLE
Use different fonts in the inaugural event

### ISSUE THREAD

**Issue by xabomon** [virtualscienceforum/virtualscienceforum#28]
In order to make it more visually attractive we might want to consider using different fonts on the inaugural event, e.g. bold letters for the titles.

**Comment by akhmerov** [comment]
We'll make the program into a table I think.

**Comment by akhmerov** [comment]
@xabomon are you happy with the program I uploaded, or should we change it?

**Comment by xabomon** [comment]
Yes! I'm gonna close the issue now.
