### ISSUE TITLE
Improve the LRC description page

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#284]
We should also link the 2020 archives.

The text is now located here: https://github.com/virtualscienceforum/virtualscienceforum/blob/master/templates/long_range_colloquium.md.j2#L3-L8

@giulia-pacchioni you said you'd take a look?

**Comment by giulia-pacchioni** [comment]
I have suggested a few changes and added links to the 2020 archive and to the mailing list registration page, and I opened a pull request for approval.
