### ISSUE TITLE
email announcement: Quantum Oscillations in Insulators

### ISSUE THREAD

**Issue by brianqskinner** [virtualscienceforum/virtualscienceforum#294]
subject: "Workshop: Quantum Oscillations in Insulators"
from: workshop organizers <no-reply@mail.virtualscienceforum.org>
to: vsf-announce 
---
Dear %recipient_name%,

We would like to announce an upcoming online workshop, "Quantum Oscillations in Insulators." 
The workshop will take place on Feb. 18-19, from 10am to noon US eastern time on each day.

The goal of the workshop is to review recent developments in the experimental observation and theoretical understanding of quantum oscillations in electrical insulators. The workshop will bring together the leading experts in both experiment and theory, including talks about the materials SmB<sub>6</sub>, YbB<sub>12</sub>, and WTe<sub>2</sub>. The existing theoretical proposals will be discussed, as well as next steps for experiment and theory.

Please visit the [workshop web page](https://virtualscienceforum.org/#/quantum-oscillations-insulators) to view the program of the workshop and to register.

Participation is free, but the number of participants is limited.

Thank you,  
Brian Skinner  
Suchitra Sebastian  
Yun Suk Eo  
(the organizers)

**Comment by brianqskinner** [comment]
Please send out this email announcement some time on Monday (Jan. 18).

**Comment by akhmerov** [comment]
Will do!

**Comment by brianqskinner** [comment]
Hi Anton,

I just noticed a problem with the registration link (at the bottom of
https://virtualscienceforum.org/#/quantum-oscillations-insulators)
It lists the date as Feb. 19 and Feb. 20  (Friday/Saturday)
The correct dates are Feb. 18 and Feb. 19  (Thursday/Friday).

Can you please fix this as soon as possible? We have already started
sending out the link for registration.

Thank you,
Brian

**Comment by akhmerov** [comment]
Fixed, pardon for the mixup.
