### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by cheipesh** [virtualscienceforum/virtualscienceforum#297]
## Name

Yevheniia Cheipesh

## Affiliation

Leiden University

## Email

gene.cheypesh@gmail.com

## Preprint ID

2011.05238

## Title

Quantum tunneling dynamics in complex SYK model quenched-coupled to a cool-bath

## Abstract

The Sachdev-Ye-Kitaev (SYK) model describes interacting fermionic zero modes in zero spatial dimensions, e.g. quantum dot, with interactions strong enough to completely washout quasiparticle excitations in the infrared. In this note, we consider the complex-valued SYK model at temperature $T$ coupled to a zero temperature reservoir by a quench. We find out that the tunneling current dynamics reveals a way to distinguish the SYK non-Fermi liquid (nFL) initial state of the subsystem from the disordered Fermi liquid. Temperature dependent contribution to the current's half-life scales linearly in $T$ at low temperatures for the SYK nFl state, while for the Fermi liquid it scales as $T^2$. This provides a characteristic signature of the SYK non-Fermi liquid in a non-equilibrium measurement.

## Authors

Y. Cheipesh, A. I. Pavlov, V. Ohanesjan, K. Schalm, N. V. Gnezdilov

## Time slot

2021-02-26 16:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
Ugh, the bot is doing something weird, I'll investigate.

**Comment by akhmerov** [comment]
Alright, now all should be good :ok_hand:

Please disregard the first registration email—that was a bug.
