### ISSUE TITLE
section vs subsection distinction

### ISSUE THREAD

**Issue by vfatemi** [virtualscienceforum/virtualscienceforum#3]
In the guidelines, the sections and subsections titles aren't especially distinct from each other.

**Comment by everthemore** [comment]
One option could be to skip a header section, i.e. use #### instead of ###

**Comment by vfatemi** [comment]
Yes, although the preview on gihub doesn't exactly reproduce what appears on the website (like those horizontal lines). e.g. see

here: https://github.com/virtualscienceforum/virtualscienceforum/blob/master/speakerguide.md
vs
here: https://virtualscienceforum.org/#/speakerguide

**Comment by everthemore** [comment]
Ok, right. But once we've figured it out we can add it to the guides and the template event page. Also, if you have a local copy of the repository you can run "python3 -m http.server" in that directory and you'll get to see it without having to push it to the repo :nerd_face:

**Comment by everthemore** [comment]
Or we could try to add the horizontal lines? GitHub has their own markdown processor, so we'd have to add it manually (or find a good plugin)

**Comment by everthemore** [comment]
Using three hyphens '---' will create the line, and the thickness can be changed by adding #'s in front (e.g. --- vs #---).

**Comment by akhmerov** [comment]
Is this still relevant?

**Comment by vfatemi** [comment]
I think it's purpose is concluded. I will make PRs to add such lines to help define the bigger sections.
