### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by mjpacholski** [virtualscienceforum/virtualscienceforum#301]
## Name

Michał Pacholski

## Affiliation

Instituut-Lorentz, Universiteit Leiden

## Email

mpacholski@lorentz.leidenuniv.nl

## Preprint ID

2101.08252

## Title

Deconfinement of Majorana vortex modes produces a superconducting Landau level

## Abstract

A spatially oscillating pair potential $\Delta(r)=\Delta_0 e^{i K\cdot x}$ with momentum $K>\Delta_0/\hbar v$ drives a deconfinement transition of the Majorana bound states in the vortex cores of a Fu-Kane heterostructure (a 3D topological insulator with Fermi velocity $v$, on a superconducting substrate with gap $\Delta_0$, in a perpendicular magnetic field). In the deconfined phase at zero chemical potential the Majorana fermions form a dispersionless Landau level, protected by chiral symmetry against broadening due to vortex scattering. The coherent superposition of electrons and holes in the Majorana Landau level is detectable as a local density of states oscillation with wave vector $\sqrt{K^2-(\Delta_0/\hbar v)^2}$. The striped pattern also provides a means to measure the chirality of the Majorana fermions.

## Authors

M. J. Pacholski, G. Lemut, O. Ovdat, İ. Adagideli, C. W. J. Beenakker

## Time slot

2021-02-19 16:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
@mjpacholski do you have a preprint number?

**Comment by akhmerov** [comment]
You can edit the application form and provide the correct one. Otherwise please provide the rest of the info.

**Comment by mjpacholski** [comment]
Fixed! Apologies for the mistake

**Comment by mjpacholski** [comment]
I have received the key and URL, everything is clear

**Comment by mjpacholski** [comment]
I approve publishing of the recording. Talk start is 00:18:05, talk end is 01:11:30
