### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by kumarjnc** [virtualscienceforum/virtualscienceforum#302]
## Name

Pramod Kumar

## Affiliation

Aalto University

## Email

pramod.kumar@aalto.fi

## Preprint ID

2005.05457

## Title

Flat band induced non-Fermi liquid behavior of multicomponent fermions

## Abstract

We investigate multicomponent fermions in a flat band and predict experimental signatures of non-Fermi liquid behavior. We use dynamical mean-field theory to obtain the density, double occupancy and entropy in a Lieb lattice for $\mathcal{N} = 2$ and $\mathcal{N} = 4$ components. We derive a mean-field scaling relation between the results for different values of $\mathcal{N}$, and study its breakdown due to beyond-mean field effects. The predicted signatures occur at temperatures above the N\'eel temperature and persist in presence of a harmonic trapping potential, thus they are observable with current ultracold gas experiments.

## Authors

Pramod Kumar, Sebastiano Peotta, Yosuke Takasu, Yoshiro Takahashi, Päivi Törmä

## Time slot

2021-03-01  16:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
I fixed the formatting issues, all looks good.

**Comment by kumarjnc** [comment]
I have received the email and everything is OK

**Comment by kumarjnc** [comment]
"I approve publishing of the recording. Talk start is 00:14:16, talk end is 00:58:10."
