### ISSUE TITLE
Update contributors and active organizers

### ISSUE THREAD

**Issue by everthemore** [virtualscienceforum/virtualscienceforum#306]
Update the 'whoweare.md' page to list:

- Current active organizers
- Overall list of contributors (past & current organizers)

**Comment by everthemore** [comment]
Todo: Add 'last updated on'.

**Comment by babaks77** [comment]
Looks like Daniel is listed under past instead of current organizers.

**Comment by giulia-pacchioni** [comment]
Good point Babak, I have moved him up and opened a pull request to approve the change.
