### ISSUE TITLE
Add inclusivity and diversity statement

### ISSUE THREAD

**Issue by everthemore** [virtualscienceforum/virtualscienceforum#307]
We discussed a paragraph with something along the lines of:

- "We welcome any contribution from researchers, regardless of seniority", making sure to not only target organizers but also speakers and audience. 
- We will put it somewhere different from the LRC page.

**Comment by everthemore** [comment]
Perhaps a page with code of conduct (separate from attendee guide) would be a good place?

**Comment by adelatorreduran** [comment]
What about something along the lines of:

"We prioritize upholding a safe, accessible, inclusive and equitable online environment for all across the spectrum of identities and lived experiences. We encourage participation, either as speakers or audience, of all members of the scientific community, regardless of seniority."

**Comment by giulia-pacchioni** [comment]
Hi Alberto, I like your suggestion!  I particularly like the expression 'lived experiences'.

1. Should we say 'either as speakers, audience or organizers'? We encourage people to join the main committee or to organize their own events, and also there everyone is welcome.
2. Do you think that mentioning only seniority in the second statement might be read as exclusion of other issues? I agree we don't want to have an endless list of race, gender, ability etc. I also see the point that seniority is the only thing that's not obvious (some series only want super established speakers). I don't necessarily want to change this statement, but would like to hear your thoughts.
3. Where do you see this paragraph fit on the website? I think we have not reached a conclusion during the meeting last week. Could we group it with the privacy policy somehow to avoid the multiplication of pages or you think it's best to have a dedicated page?

**Comment by akhmerov** [comment]
Let's put it in "what we do" together with updating that section.

**Comment by adelatorreduran** [comment]
Including the suggestions:

"We prioritize upholding a safe, accessible, inclusive and equitable online environment for all across the spectrum of identities and lived experiences. We encourage participation, either as speakers, organizers or audience, of all members of the scientific community."

And I think we agreed on putting it on "What we do".

**Comment by giulia-pacchioni** [comment]
I like your suggestion @adelatorreduran , and I think we should remove the sentence "Now that winter has arrived, we particularly encourage applications for winter schools organized by graduate students, post docs or early-career researchers.", as it's currently not our main focus any more.

Do you know how to update the page? If not we can coordinate through gitter and I can show you the ropes.

**Comment by adelatorreduran** [comment]
As this is the first time, I think it would be great if you show me how to do it, don't want to mess up  :)

**Comment by giulia-pacchioni** [comment]
Sure, I sent you a message in the chat :)

**Comment by giulia-pacchioni** [comment]
Statement added! I'm closing the issue.
