### ISSUE TITLE
Create mail lists for admins and organizers

### ISSUE THREAD

**Issue by babaks77** [virtualscienceforum/virtualscienceforum#31]
It would be good to have an admin email list on the website. Two types of lists can be created:

1. General admin, sending emails to admins who can resolve general issues, answer general questions, etc.
2. For each session or event, we can have emails created for organizers as well as admin email for communication about the event itself.

**Comment by akhmerov** [comment]
I think it's best to keep most questions public and answer them via this issue tracker.

- That way any of us can reply
- Those asking can check if their question was answered before
- We easily keep a track record of those that we can convert into an FAQ/manual

That said, we should definitely list an admin email like `admin@virtualscienceforum.org`, but perhaps with clear instructions of what range of issues should be addressed to that email (what should those be?)

**Comment by babaks77** [comment]
Keeping questions public via issue tracker is good. Can each session have its own "channel" or something like that so issues arising specifically for a session (organization, logistics, speaker requests, etc.) can be addressed within it?

**Comment by akhmerov** [comment]
Yes, there are special tools for filtering issues: labels, milestones, projects.

Right now we have a separate label for applications, but not much more beyond that. We'll introduce more structure with time.

**Comment by akhmerov** [comment]
I think the matter of organizing sessions has now been addressed.
