### ISSUE TITLE
Long Range Colloquium by Xie Chen

### ISSUE THREAD

**Issue by everthemore** [virtualscienceforum/virtualscienceforum#312]
subject: Long Range Colloquium by Xie Chen
from: VSF team <no-reply@mail.virtualscienceforum.org>
to: vsf-announce
---
Dear %recipient_name%,

We would like to invite you to the upcoming VSF Long Range Colloquium that is going to take place Wednesday February 17th at 1:30 PM ET (19:30 CET). We are happy to have [Xie Chen](http://www.its.caltech.edu/~xcchen/) (Caltech) as the next speaker, who is going to talk about "Fracton and Chern-Simons Theory". To see the talk abstract and register, please go to [the colloquium page](https://virtualscienceforum.org/#/long_range_colloquium) or register directly at [this URL](https://virtualscienceforum-org.zoom.us/meeting/register/tJcoc-uprTgsGdz_poJN6ALGKN3lSPfaGEQg).

Best regards,  
The Virtual Science Forum team.

**Comment by akhmerov** [comment]
Closing (these announcements aren't supported yet because of attaching a calendar event)
