### ISSUE TITLE
What we learned from the first VSF

### ISSUE THREAD

**Issue by vfatemi** [virtualscienceforum/virtualscienceforum#33]
Please add anything you observed from our first public event that you feel is worth sharing. These would be errors that require solutions, good things that we should do more of, and anything in between.

A few items observed in advance of the event: 
* We should put the Zoom link in the immediate registration confirmation email. (in the google form: settings → presentation → confirmation message)
* In the conference welcome page, we should specify that registration will result in them being emailed the link to the Zoom meeting (this would be both immediately after registration and in a reminder email a few hours before the event). 
* Speakers may be too busy or difficult to reach to reliably get them to test the Zoom platform only 24 hours in advance. Perhaps this should be an "anytime in the week before the conference" task, not a "within the day before" task.

**Comment by akhmerov** [comment]
* Our email workflow really needs some work. We might get an account with a mailing list or email hosting provider.

**Comment by vfatemi** [comment]
* Warn speakers about how they may inadvertently draw on their screen (or use this to their advantage)

**Comment by vfatemi** [comment]
* Suggestion from a friend: let the audience know they can periodically use (e.g. it is not rude to use) the "slow-down/speed-up" buttons to help encourage the speaker in some direction.

**Comment by xabomon** [comment]
>     * Suggestion from a friend: let the audience know they can periodically use (e.g. it is not rude to use) the "slow-down/speed-up" buttons to help encourage the speaker in some direction.

As a momentary solution one can remember in the chat that this is possible, but should definitely be in the guides.

**Comment by xabomon** [comment]
- Most of the videos of the audience are off, we should recommend to turn them on.

**Comment by vfatemi** [comment]
* Extra emphasis on a good microphone is a must. Perhaps there is a way we can make this easier for the speakers with a list of inexpensive suggestions?

* It seems like the speakers may have a poorer handle on time, given that there is no natural clock to glance at, and since the speaker is not in their "usual mode" of standing and giving the presentation from memory, with clickers, etc. Is there a way we can tell Zoom to have a timer or clock appear for the speakers, or a discrete way of alerting the speaker regarding remaining time?

**Comment by vfatemi** [comment]
* Steve had some slide advancement issues while in Zoom, perhaps related to using the pointers. We should look into this.

**Comment by vfatemi** [comment]
* The break was a good idea. 
* The spreading out of the talks (with plenty of in between time for questions) was also nice to ensure ending on time.

**Comment by vfatemi** [comment]
Idea from a Yale colleague: 
* Encourage speakers to sit further away from the camera so we have a more full-body shot, since body language is a nice part of the communication and is better if it is conveyed.

**Comment by vfatemi** [comment]
* Apparently the mobile version of zoom has some weird behaviors, particularly that it notifies the person whenever someone has entered or exited the room. We should try testing the mobile version at some point.

**Comment by vfatemi** [comment]
* Do not "unmute all" as that will lead to pandemonium. However during breaks I think doing the "you can unmute yourselves and let's have a group chat" thing is a good idea if we execute it with more intention and planning, which we can explore.

**Comment by akhmerov** [comment]
* Someone from the audience was using annotations to draw over the presenter screen (likely due to curiosity rather than being disruptive). I have cleared annotations myself, but if we keep using zoom, we should instruct the speakers to disable audience annotations.
