### ISSUE TITLE
Info on maximum recommended screen resolution

### ISSUE THREAD

**Issue by giulia-pacchioni** [virtualscienceforum/virtualscienceforum#335]
Let's include this information in the LRC reminder email to the speaker and in the Speakers' corner checklist to ensure all presenters see it. @vfatemi @akhmerov do you want to take this on as you are the ones who found the solution to the problem?

**Comment by akhmerov** [comment]
That should rather go into the reminder to the speaker. That means we should include this in the action points for the host.

**Comment by giulia-pacchioni** [comment]
Good point, done, I've also proposed the update to the SC checklist.
