### ISSUE TITLE
inaugural session wrap-up

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#35]
Summarizing things we still need to do to finalize the session

- [x] publish the videos
- [x] make a separate page with the session summary
- [x] make a new landing page

Did I forget anything?

**Comment by vfatemi** [comment]
Thank you emails to the speakers. 
Thank you emails to the registered participants.

Both these emails should have (I think) link to the videos, link to the new session summary page, further request for feedback, and encouragement to make their own VSF happen by submitting an idea to us.

**Comment by akhmerov** [comment]
- [ ] contact APS so that they can update https://march.aps.org/about/sharing-your-research/

**Comment by xabomon** [comment]
>     * [ ]  Thank you emails to the speakers.
> 
>     * [ ]  Thank you emails to the registered participants.
> 
> 
> Both these emails should have (I think) link to the videos, link to the new session summary page, further request for feedback, and encouragement to make their own VSF happen by submitting an idea to us.

Hi Valla,
is this email been sent yet? The website with the event has been updated, and the videos are online, shall we write this email?

Best,
Xavi

**Comment by akhmerov** [comment]
> Thank you emails to the registered participants.

I'm wondering if this is appropriate: quite generally I'm hesitant sending mass emails without an explicit request.

**Comment by vfatemi** [comment]
> > Thank you emails to the registered participants.
> 
> I'm wondering if this is appropriate: quite generally I'm hesitant sending mass emails without an explicit request.

I had at least four local colleagues ask if there would be a video posted online, which would indicate that a reasonable proportion of the participants would like to be informed of this. It also gives us an opportunity to request feedback or encourage people to contact us about making their own VSF.

Perhaps for the next time, the registration form can include a specific question about whether they would like to be emailed a link to the videos when they are ready, separately from the broader "can we contact you about future VSF stuff" question. But that might be overly complicated, and a yes to the latter question may be sufficient.

**Comment by xabomon** [comment]
I agree with @vfatemi . I think a closing email is OK, including the links to the talks, asking for feedback and encouraging people to contribute or organize a session using VSF.

Do you guys want to use a Google docs for a closing email? I can start it.

**Comment by akhmerov** [comment]
I think we should move everything to this repository. Please create a folder called `email_templates` and add a draft there.

**Comment by akhmerov** [comment]
All done.
