### ISSUE TITLE
Tidy up org meeting recordings

### ISSUE THREAD

**Issue by babaks77** [virtualscienceforum/virtualscienceforum#361]
From [Apr 27, 2021 meeting](https://github.com/virtualscienceforum/virtualscienceforum/issues/358):

- [x] Update org meeting instructions
- [x] Review and close open org meeting issues
- [x] Remove YourTube playlist.

**Comment by akhmerov** [comment]
I made the playlist and the videos unlisted rather than deleted. This achieves the same result.
