### ISSUE TITLE
Consider implementing designated questioners

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#37]
In order to provide better immediate feedback to the presenter, the organizers could designate a couple of people, who would be able to interrupt the talk at any moment, ask both basic questions and in-depth questions, as well as directly respond to the queries by the presenter.

This would of course happen in addition to the questions from the audience.

**Comment by vfatemi** [comment]
More than just having the ability to interrupt at any moment, it could be an explicit, designated role to ask basic questions: their job during the talk is to identify undefined jargon or unclear points and ask the presenter about them.

**Comment by vfatemi** [comment]
Revisiting this issue -- it seems with our roughly half a year of experience, this is probably not necessary. Ok to close?

**Comment by akhmerov** [comment]
I agree. I think speakers are now also more used to the new setting.
