### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by Waintal** [virtualscienceforum/virtualscienceforum#375]
## Name

Xavier Waintal

## Affiliation

PHELIQS, CEA Grenoble, France

## Email

xavier.waintal@cea.fr

## Preprint ID

2002.12372

## Title

Correlations and computational quantum transport: an approach for the automatic calculation
of Feynman diagrams at large orders

## Abstract

Even in the simplest quantum nanoelectronic devices, such as quantum dots (Kondo effect, Coulomb blockade) or quantum point contacts (0.7 anomaly), electronic correlations play a central role. Yet, except in some specific situations, these correlations are beyond the reach of existing numerical techniques. In this talk, I will present our efforts to build algorithms that systematically and automatically calculate all Feynman diagrams up to very large order (10-22). As a first real life application, I will show how the technique can be used to solve the Kondo problem out-of-equilibrium.

## Authors

Marjan Maček, Philipp T. Dumitrescu, Corentin Bertrand, Bill Triggs, Olivier Parcollet, Xavier Waintal

## Time slot

2021-06-01 14:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
@Waintal are you sure you want to talk at 16:00 UTC (that's 18:00 CEST)?

**Comment by Waintal** [comment]
Hum, got confused again with time.


Would 16H00 CEST be good?


X.


________________________________
De : Anton Akhmerov ***@***.***>
Envoyé : lundi 17 mai 2021 15:42:57
À : virtualscienceforum/virtualscienceforum
Cc : Xavier Waintal; Mention
Objet : Re: [virtualscienceforum/virtualscienceforum] Speakers' corner talk application (#375)


@Waintal<https://github.com/Waintal> are you sure you want to talk at 16:00 UTC (that's 18:00 CEST)?

**Comment by akhmerov** [comment]
Great, I fixed the time. All looks good!

**Comment by Waintal** [comment]
Got it!

**Comment by Waintal** [comment]
I approve publishing of the recording. Talk start is 00:07:30, talk end is 01:12:30.
