### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by ristoja** [virtualscienceforum/virtualscienceforum#384]
## Name

Risto Ojajärvi

## Affiliation

University of Jyväskylä

## Email

risto.m.m.ojajarvi@jyu.fi

## Preprint ID

2103.07412

## Title

Superconductivity provides a giant enhancement to the spin battery effect

## Abstract

We develop a theory of the spin battery effect in superconductor/ferromagnetic insulator (SC/FI) systems taking into account the magnetic proximity effect. We demonstrate that the spin-energy mixing enabled by the superconductivity leads to the enhancement of spin accumulation by several orders of magnitude relative to the normal state. This finding can explain the recently observed giant inverse spin Hall effect generated by thermal magnons in the SC/FI system. We suggest a non-local electrical detection scheme which can directly probe the spin accumulation driven by the magnetization dynamics. We predict a giant Seebeck effect converting the magnon temperature bias into the non-local voltage signal. We also show how this can be used to enhance the sensitivity of magnon detection even up to the single-magnon level.

## Authors

Risto Ojajärvi, Tero T. Heikkilä, P. Virtanen, M. A. Silaev

## Time slot

2021-06-23 12:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by ristoja** [comment]
Is the length of the Speaker's corner talk fixed to 40min? I would actually like to give a shorter 30min talk if that is ok, and can be added to the announcement.

**Comment by ristoja** [comment]
I confirm that I received the email instructions, read and understood them.

**Comment by akhmerov** [comment]
40 m is the recommended length, but you're free to give either a shorter or a longer one—the only hard limit is that the meeting is stopped after 1¾ hours.

Do you think it's important to reflect the shorter duration in the announcement? We don't really specify the talk duration right now.

**Comment by ristoja** [comment]
No, it's not necessary. I can also specify the approximate length of the talk in the beginning of the talk.

**Comment by ristoja** [comment]
I approve publishing of the recording. Talk start is 0:11:16, talk end is 1:12:18.
