### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by Noah-F-Q-Yuan** [virtualscienceforum/virtualscienceforum#387]
## Name

Noah F. Q. Yuan

## Affiliation

Shenzhen JL Computational Science and Applied Research Institute

## Email

yuanfanqi@csar.ac.cn

## Preprint ID

2106.01909

## Title

Supercurrent diode effect and finite momentum superconductivity

## Abstract

When both inversion and time-reversal symmetries are broken, the critical current of a superconductor can be nonreciprocal. In this work we show that in certain classes of two-dimensional superconductors with antisymmetric spin-orbit coupling, Cooper pairs acquire a finite momentum upon the application of an in-plane magnetic field, and as a result, critical currents in the direction parallel and antiparallel to the Cooper pair momentum become unequal. This supercurrent diode effect is also manifested in the polarity-dependence of in-plane critical fields induced by a supercurrent. These nonreciprocal effects may be found in polar SrTiO$_3$ film, few-layer MoTe$_2$ in the $T_d$ phase, and twisted bilayer graphene in which the valley degrees of freedom plays the role analogous to spin.

## Authors

Noah F. Q. Yuan, Liang Fu

## Time slot

2021-06-24 14:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
I'll fix that, no problem.

**Comment by akhmerov** [comment]
Fixed

**Comment by Noah-F-Q-Yuan** [comment]
Thank you so much! @akhmerov

**Comment by Noah-F-Q-Yuan** [comment]
Sorry I think I didn’t receive the meeting key and my join URL. Could you check it and send them to me?

Thanks and regards,
Noah

**Comment by akhmerov** [comment]
@Noah-F-Q-Yuan I've resend the email, let me know if it worked now.

**Comment by Noah-F-Q-Yuan** [comment]
@akhmerov Thank you for your help and I just received it. The two emails were misidentified as junk mails.

**Comment by akhmerov** [comment]
@Noah-F-Q-Yuan just checking: did you receive an email with a request to approve publishing of the video? Please check your spam folder.

**Comment by Noah-F-Q-Yuan** [comment]
I approve publishing of the recording. Talk start is 00:09:59, talk end is 01:00:00.

**Comment by Noah-F-Q-Yuan** [comment]
@ Anton Akhmerov Thank you for reminding me. I just move the related email addresses to the whitelist.
