### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by j-curtis** [virtualscienceforum/virtualscienceforum#390]
## Name

Jonathan Curtis

## Affiliation

Harvard University

## Email

jcurtis@seas.harvard.edu

## Preprint ID

2106.07828

## Title

Cavity magnon-polaritons in cuprate parent compounds

## Abstract

Cavity control of quantum matter may offer new ways to study and manipulate many-body systems. A particularly appealing idea is to use cavities to enhance superconductivity, especially in unconventional or high-$T_c$ systems. Motivated by this, we propose a scheme for coupling Terahertz resonators to the antiferromagnetic fluctuations in a cuprate parent compound, which are believed to provide the glue for Cooper pairs in the superconducting phase. First, we derive the interaction between magnon excitations of the Ne\'el-order and polar phonons associated with the planar oxygens. This mode also couples to the cavity electric field, and in the presence of spin-orbit interactions mediates a linear coupling between the cavity and magnons, forming hybridized magnon-polaritons. This hybridization vanishes linearly with photon momentum, implying the need for near-field optical methods, which we analyze within a simple model. We then derive a higher-order coupling between the cavity and magnons which is only present in bilayer systems, but does not rely on spin-orbit coupling. This interaction is found to be large, but only couples to the bimagnon operator. As a result we find a strong, but heavily damped, bimagnon-cavity interaction which produces highly asymmetric cavity line-shapes in the strong-coupling regime. To conclude, we outline several interesting extensions of our theory, including applications to carrier-doped cuprates and other strongly-correlated systems with Terahertz-scale magnetic excitations.

## Authors

Jonathan B. Curtis, Andrey Grankin, Nicholas R. Poniatowski, Victor M. Galitski, Prineha Narang, Eugene Demler

## Time slot

2021-07-08 14:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
@j-curtis I fixed the last bit (the bot was unreasonably strict with checking).

**Comment by sentefmi** [comment]
I can chair this talk

**Comment by j-curtis** [comment]
Thank you, I was very confused haha

**Comment by j-curtis** [comment]
I confirm I received the host-key and email containing it.

**Comment by j-curtis** [comment]
I approve publishing of the recording. Talk start is 00:19:33, talk end is 01:19:40.
