### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by tpyang** [virtualscienceforum/virtualscienceforum#398]
## Name

Yang Zhang

## Affiliation

Massachusetts Institute of Technology

## Email

yzhang11@mit.edu

## Preprint ID

2107.02167

## Title

Spin-textured Chern bands in AB-stacked transition metal dichalcogenide bilayer MoTe2/WSe2

## Abstract

While transition metal dichalcogenide (TMD) based moire materials have been shown to host various correlated electronic phenomena, topological states have not been experimentally observed until now. In this work, using first principles calculations and continuum modeling, we reveal the displacement field induced topological moire bands in AB-stacked TMD heterobilayer MoTe2/WSe2. Valley contrasting Chern bands with non-trivial spin texture are formed from interlayer hybridization between MoTe2 and WSe2 bands of nominally opposite spins. Our study establishes a recipe for creating topological bands in AB stacked TMD bilayers in general, which provides a highly tunable platform for realizing quantum spin Hall and interaction induced quantum anomalous Hall effects.

## Authors

Yang Zhang, Trithep Devakul, Liang Fu

## Time slot

2021-07-29 14:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
@tpyang just checking: did your receive an email with your link and the host password?

**Comment by tpyang** [comment]
> @tpyang just checking: did your receive an email with your link and the host password?

Hi Anton, I haven't received the link and host password, could you please send it again? My email address is yzhang11@mit.edu

**Comment by akhmerov** [comment]
Did that, should be there

**Comment by tpyang** [comment]
> Did that, should be there

Thank you! Now I received it.

**Comment by tpyang** [comment]
I approve publishing of the recording. Talk start is 00:12:05, talk end is 01:09:04.
