### ISSUE TITLE
Upgrade to a static website generator with a (nicer) theme

### ISSUE THREAD

**Issue by everthemore** [virtualscienceforum/virtualscienceforum#401]
Potential options:
* https://themes.gohugo.io/
* https://www.gatsbyjs.com/starters/?
* ...

**Comment by everthemore** [comment]
Related to issue #45

**Comment by akhmerov** [comment]
@everthemore check out https://wowchemy.com/ (former Hugo academic theme).

**Comment by akhmerov** [comment]
@everthemore what do you think about https://squidfunk.github.io/mkdocs-material/?
