### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by brianqskinner** [virtualscienceforum/virtualscienceforum#407]
## Name

Brian Skinner

## Affiliation

Ohio State University

## Email

skinner.352@osu.edu

## Preprint ID

2103.16586

## Title

Mysteries near the zero-field Wigner crystal transition in a 2D electron system

## Abstract

I will discuss recent experimental results on the low-temperature transport in a strongly interacting zinc-oxide-based high mobility two dimensional electron system. The data shows clear hallmarks of the long-anticipated transition between a Fermi liquid phase and a Wigner crystal phase at zero magnetic field. Other features of the data, however, suggest new mysteries in the vicinity of this transition. This talk will highlight those mysteries, and overview a number of sharp and unexpected questions that are implied by the data. I will focus on the resistivity at ultra-low temperatures as a function of electron concentration and spin polarization.

## Authors

Joseph Falson, Inti Sodemann, Brian Skinner, Daniela Tabrea, Yusuke Kozuka, Atsushi Tsukazaki, Masashi Kawasaki, Klaus von Klitzing, Jurgen H Smet

## Time slot

2021-08-18 16:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by brianqskinner** [comment]
I confirm that I have received the email with the host key and zoom login link.

Please note that I have slightly updated the title of the talk.

**Comment by brianqskinner** [comment]
Just to clarify the previous comment:

I am hoping to slightly edit the title of the talk, to "Mysteries near the zero-field Wigner crystal transition in a 2D electron system". I am not changing anything else.

**Comment by akhmerov** [comment]
I updated the title. The bot's message was too terse—we manually review and apply changes after the event becomes public.

**Comment by brianqskinner** [comment]
I approve publishing of the recording.
Talk start is 00:08:47, talk end is 01:12:36.
