### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by gaberber** [virtualscienceforum/virtualscienceforum#446]
## Name

Guanzhong Wang

## Affiliation

TU Delft

## Email

g.wang-4@tudelft.nl

## Preprint ID

2110.05373

## Title

Non-local measurement of quasiparticle distribution in proximitized semiconductor nanowires using quantum dots

## Abstract

The lowest-energy excitations of superconductors do not carry an electric charge, as their wave function is equally electron-like and hole-like. This fundamental property is not easy to study in electrical measurements that rely on charge to generate an observable signal. The ability of a quantum dot to act as a charge filter enables us to solve this problem and measure the quasiparticle charge in superconducting-semiconducting hybrid nanowire heterostructures. We report measurements on a three-terminal circuit, in which an injection lead excites a non-equilibrium in the hybrid system and the electron or hole component of the resulting quasiparticles is detected using a quantum dot as a tunable charge and energy filter. The results verify the chargeless nature of the quasiparticles at the gap edge and further reveal the complete relaxation of injected charge and energy in a proximitized nanowire, resolving open questions in previous three-terminal experiments. Our setup can also be utilized to study spin physics in proximitized systems.

## Authors

Guanzhong Wang, Tom Dvir, Nick van Loo, Grzegorz P. Mazur, Sasa Gazibegovic, Ghada Badawy, Erik P. A. M. Bakkers, Leo P. Kouwenhoven, Gijs de Lange

## Time slot

2021-11-18 16:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
Closing due to the talk cancelation
