### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by balabastien** [virtualscienceforum/virtualscienceforum#456]
## Name

Bastien Lapierre

## Affiliation

University of Zurich

## Email

bastien.lapierre@uzh.ch

## Preprint ID

2110.14651

## Title

Topologically Localized Insulators

## Abstract

In this talk I will show that fully localized, three-dimensional, time-reversal-symmetry-broken Anderson insulators support topologically distinct phases that can be labelled by integers. Any two such topologically localized phases are separated by a metallic phase. These novel topological phases are fundamentally distinct from insulators without disorder: they are guaranteed to host delocalized states along their insulating boundaries, giving rise to the quantized boundary Hall conductance whose value is determined by the integer invariant assigned to the bulk.

## Authors

Bastien Lapierre, Titus Neupert, Luka Trifunovic

## Time slot

2021-11-25 14:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
@balabastien just checking: did you receive the meeting host key and the instructions?

**Comment by balabastien** [comment]
> @balabastien just checking: did you receive the meeting host key and the instructions?

Dear Anton,
Yes, I already received the meeting host key and the instructions for the talk.

**Comment by balabastien** [comment]
I approve publishing of the recording. Start is 00:14:46, end is 01:09:02.
