### ISSUE TITLE
VSF platform for cancelled departamental seminars 

### ISSUE THREAD

**Issue by aggrushin** [virtualscienceforum/virtualscienceforum#46]
Speakers scheduled to give your departamental seminar at our research institutions might be or will be canceling due to COVID-19, and in the future other reasons (strike, flight cancellation, visa problems).  

1. Are there specific instructions/recommendations that we could add to our existing ones? 
2. Could we add a broader scope to the website? (i.e. to the leading sentence at our website: 'A platform for scientific conferences going fully digital')

**Comment by vfatemi** [comment]
This seems now past its utility for the community.
