### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by nisargapaul** [virtualscienceforum/virtualscienceforum#460]
## Name

Nisarga Paul

## Affiliation

Massachusetts Institute of Technology

## Email

npaul@mit.edu

## Preprint ID

2111.01805

## Title

Giant proximity exchange and flat Chern band in 2D magnet-semiconductor heterostructures

## Abstract

Van der Waals (vdW) heterostructures formed by two-dimensional magnets and semiconductors have provided a fertile ground for fundamental science and for spintronics. In this talk I discuss two main results: (1) a first-principles calculations finding a proximity exchange splitting of 14 meV equivalent to an effective Zeeman field of 120 T in the vdW magnet-semiconductor heterostructure MoS2/CrBr3 and (2) the appearance of a flat Chern band in the electronic bandstructure of 2D magnet - semiconductor heterostructures when the magnetic layer hosts chiral spin textures such as skyrmions. The latter result is derived in a completely general continuum model. More specifically, a flat Chern band is found at a "magic" value of magnetization (~0.2) for Schrödinger electrons, and it generally occurs for Dirac electrons. I also discuss possible connections to skyrmions in magnetic TIs and spintronics.

## Authors

Nisarga Paul, Yang Zhang, Liang Fu

## Time slot

2021-12-16 15:00 UTC

## Notes
I approve publishing of the recording. Start is 00:11:55, end is 00:44:44.

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
Done, I've rescheduled the talk.

**Comment by akhmerov** [comment]
Hey @nisargapaul just checking: did you receive the video publication link? Do you approve publishing of the video?

**Comment by nisargapaul** [comment]
Sorry for missing this! I approve publishing of the recording. Start is 00:11:55, end is 00:44:44.
