### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by trithepd** [virtualscienceforum/virtualscienceforum#467]
## Name

Trithep Devakul

## Affiliation

MIT

## Email

tdevakul@mit.edu

## Preprint ID

2109.13909

## Title

Quantum anomalous Hall effect from inverted charge transfer gap: application to moire transition metal dichalcogenide bilayers

## Abstract

A general mechanism is presented by which topological physics arises in strongly correlated systems without flat bands. Starting from a charge transfer insulator, topology emerges when the charge transfer energy between the cation and anion is reduced to invert the lower Hubbard band and the spin-degenerate charge transfer band. A universal low-energy theory is developed for the inversion of charge transfer gap in an $xy$ antiferromagnet. The inverted state is found to be a quantum anomalous Hall (QAH) insulator with non-coplanar magnetism. Interactions play two essential roles in this mechanism: producing the Mott gap and quasiparticle bands necessary for band inversion, and driving non-coplanar magnetism after inversion. Our theory applies to and explains the recently observed QAH state in AB-stacked TMD bilayer MoTe$_2$/WSe$_2$.

## Authors

Trithep Devakul, Liang Fu

## Time slot

2021-12-07 16:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by trithepd** [comment]
Hi,

I would like to update the title of my talk to:
Quantum anomalous Hall effect from inverted charge transfer gap: application to moire transition metal dichalcogenide bilayers

**Comment by akhmerov** [comment]
Done, I updated the title

**Comment by trithepd** [comment]
I am just confirming that I've received the confirmation email and read all the instructions.

**Comment by trithepd** [comment]
Hi,

The video recording of this talk seems to be broken.  When I click the link sent to my email, I find just a 7 second long clip.

Best,
Trithep

**Comment by akhmerov** [comment]
I now emailed you the correct link, please use that one.

**Comment by trithepd** [comment]
I approve publishing of the recording. Start is 00:18:28, end is 01:14:05.
