### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by ding6626e34** [virtualscienceforum/virtualscienceforum#468]
## Name

Ding Zhang

## Affiliation

Tsinghua University

## Email

dingzhang@tsinghua.edu.cn

## Preprint ID

1903.07627

## Title

Ising superconductivity in few-layer stanene

## Abstract

The two-dimensional crystalline superconductors possess a variety of exotic properties. For instance, their Cooper pairs can sustain a large in-plane magnetic field owning to the spin-orbital locking [1]. Here we report two-dimensional superconductivity in few layer stanene—ultrathin gray tin (111)—with an enhanced in-plane upper critical field. The emergence of superconductivity in stanene is unexpected because bulk gray tin is non-superconductive. We found superconductivity in few-layer stanene on PbTe/Bi2Te3/Si(111) substrate grown by molecular beam epitaxy [2]. The superconducting properties can be modulated by varying the substrate thickness. The band structure of this system is consistent with first-principles calculations, suggesting topologically non-trivial properties. Furthermore, few-layer stanene hosts enhanced in-plane upper critical fields that greatly exceed the conventional limit. Few-layer stanene is centrosymmetric and its electronic bands center around the Γ point. Therefore, the established Ising superconductivity for transition metal dichalcogenide does not apply. Instead, we propose a novel type of spin locking mechanism—dubbed type-II Ising pairing, which accounts for the large in-plane upper critical magnetic field in centrosymmetric superconductor with multiple degenerate orbitals [3].

1. D. Zhang and J. Falson, _Nanotechnology_ **32**, 502003 (2021).
2. M. Liao#, Y. Zang#, et al. _Nat. Phys._ **14**, 344-348 (2018).
3. J. Falson, et al. _Science_ **367**, 1454 (2020).

## Time slot

2021-11-30 00:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by vfatemi** [comment]
Looks good!

**Comment by ding6626e34** [comment]
I would like to confirm that I have received the instructions and the confirmation email.

**Comment by akhmerov** [comment]
@ding6626e34 just checking that the time is correct: your talk is scheduled for midnight UTC, which is 8:00 in Beijing time zone / 1:00 EU time and 7pm US East.

**Comment by ding6626e34** [comment]
@akhmerov Hi Anton, I confirm that the time is correct.

**Comment by ding6626e34** [comment]
I approve publishing of the recording. Start is 00:13:10, end is 00:48:11.
