### ISSUE TITLE
Add page on legal aspects of VSF.

### ISSUE THREAD

**Issue by xabomon** [virtualscienceforum/virtualscienceforum#47]
After a discussion with some colleagues:
- Make sure that everything is complaint with  GDPR, including forms for recording talks, attendees questions etc.

**Comment by astroleo** [comment]
Just to add a piece of background on this: privacy concerns, and especially concerns about GDPR compliance (which can lead to hefty fines), have been the biggest worry for several people I discussed with when considering to move an in-person conference to a (recorded) digital one. Should you be able to come up with a GDPR-compliant form for participants and speakers, that would be of great help for potential organisers of digital conferences. Ideally this form would take into account the more difficult case that a few participants do not want to be on the recording, but may still want to pose questions. Thanks! A colleague. :-)

**Comment by akhmerov** [comment]
A quick remark about the recordings.

According to my best understanding of DGPR, verbally informing the participants that a recording takes place is sufficient to make "legitimate interest" a legal basis for processing of the audience personal data (i.e. their voice if they ask a question). As opposed to informed consent (which is much harder to organize at scale), legitimate interest does not require collecting a proof that every participant agreed.

**Comment by astroleo** [comment]
Thanks, Anton. That sounds reasonable. Any chance to get legal people involved in your project as well?

**Comment by akhmerov** [comment]
If a lawyer finds it online and joins, then sure.

Just to provide a bit more reading material to explain that I'm not just randomly expressing a strong opinion:

1. An explanation of "legitimate interest" as a basis for data
processing: https://www.ucl.ac.uk/legal-services/ucl-general-data-protection-regulation-gdpr/guidance-notices-ucl-staff/legitimate-interests-lawful
2. The clarification specifically about the proper protocol of
publishing lecture recordings, specifically this paragraph:
https://www.ucl.ac.uk/legal-services/ucl-general-data-protection-regulation-gdpr/guidance-notices-ucl-staff/guidance-note-capturing

---

Overall this is a community effort, and while we want to handle the personal data properly, we also collect it rather explicitly, and only use for the purpose that we declare. This puts us at an overall good standing with GDPR (NB: we aren't actually a legal entity, so technically speaking GDPR doesn't even apply to us...)

We certainly should add a page that describes our privacy approach.

**Comment by aggrushin** [comment]
An additional question: If one uses the full version of Zoom facilitated by a university (we've been using Indiana for our meetings), does this come with extra legal restrictions?
