### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by IvanKulesh** [virtualscienceforum/virtualscienceforum#471]
## Name

Ivan Kulesh

## Affiliation

QuTech, Delft University of Technology

## Email

I.Kulesh-1@tudelft.nl

## Title

Longitudinal resistance oscillations in InSbAs 2DEGs in a Quantum Hall regime

## Abstract

Integer quantum Hall states interacting with a superconducting electrode, are predicted to form Andreev edge states. This effect is expected to exhibit an oscillatory interference pattern in the longitudinal resistance, measured with respect to the grounded superconducting lead. In InSb-based two-dimensional electron gases we observe pronounced longitudinal  resistance oscillations. However, we verify that the origin of such oscillation is not related to the superconductivity, but rather, transport through the bulk in the disordered quantum Hall regime. Understanding the origin and location in parameter states of these oscillations is important to clearly distinguish between trivial and superconducting effects in the quantum Hall regime.

## Authors

Ivan Kulesh, Mark van Blankenstein, Candice Thomas, Di Xiao, Geoffrey C. Gardner, Michael J. Manfra, Srijit Goswami

## Time slot

2021-12-08 16:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by IvanKulesh** [comment]
I confirm that I've received the email with the zoom link and instructions

**Comment by akhmerov** [comment]
The speaker approves publishing the recording. start 00:07:40 end 01:00:04
