### ISSUE TITLE
New iteration of guidelines

### ISSUE THREAD

**Issue by xabomon** [virtualscienceforum/virtualscienceforum#48]
- [x] Update existing material: Organizers, Attendees, Moderators
- [ ] Include details on how to use a virtual blackboard (most likely needs a third an external tool such as tablet or peripheral)
- [ ] Record videos with details about how to host, moderate and ask questions
- [ ] Describe how speakers can set up faces in their screen

**Comment by akamra47** [comment]
Hi,

I was reviewing the organizer guidelines. I think it might be useful to comment on the attendance limitations of the platform (Zoom). As an organizer, I would like to know what audience size I should aim for, and what would get me in trouble.

**Comment by aggrushin** [comment]
Another possible addition: Perhaps it is not very clear from the guidelines who, between the host and organizers, has the power to lower raise hands, and how this role is assigned within the platform.

**Comment by everthemore** [comment]
We could add another action point: Establish a second, quick, connection to the speaker (phone, chat). In case they have technical difficulties and need to contact the host, or if something is wrong during their talk and they don't see Zoom messages etc.

**Comment by xabomon** [comment]
This issue is linked to #86 and #87

**Comment by akhmerov** [comment]
I think we can close this: the iterated guidelines are now in place.
