### ISSUE TITLE
ARQH talks and questions announcement

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#480]
subject: "ARQH workshop: satellite talks and questions"
from: "ARQH organizers <arqh@virtualscienceforum.org>"
to: 85059061436
---
Dear %recipient_name%,

The ARQH workshop takes place in two days, and we are looking forward to seeing you there!

In the meantime, tomorrow at 17:00 CET / 11:00 Eastern time we will have the second [satellite talk](https://virtualscienceforum.org/arqh/#schedule) about "Longitudinal resistance oscillations in InSbAs 2DEGs in a Quantum Hall regime" by Ivan Kulesh. We will also soon share the video for the final satellite talk "Mesoscopic conductance along the proximitized quantum Hall edge" by Vladislav D. Kurilovich.

The main part of the workshop is the panel discussion that follows the talks. For that, we welcome your input. Do you have any thoughts or considerations about Andreev reflection in the quantum Hall regime you would like to share? Or perhaps questions that you would like the speakers or other participants to address? If yes—please share these by replying to this email or directly adding your point to our [questions list](https://hackmd.io/@ARQH/questions) (use the "edit" button). We will of course also welcome your input during the workshop.

See you at the workshop,  
ARQH organizers

**Comment by vfatemi** [comment]
I've edited for grammar and clarity. Otherwise looks good.
