### ISSUE TITLE
Mailing List Survey Questions

### ISSUE THREAD

**Issue by everthemore** [virtualscienceforum/virtualscienceforum#487]
We are discussing sending a survey to the mailing list subscribers, so that we get more insight into what the community values and wants.

This issue is meant to collect questions and get a discussion started. They will eventually be turned into a Google form for the survey.

Please contribute if you have thoughs/opinions/comments!

Some important topics and questions are:
- LRC
    - Which timezone are you in? And is the LRC talk at an appropriate time in your timezone? Is this a reason not to attend, but would you watch the recording instead?
    - Would you be interested in submitting speaker proposals? Would you want to host them? 
- SC 
    - Do you like the format? What do you think we could do to improve the self-sustainability of this series?
- General
    - What do you think about online seminars in general? Did you grow tired of them, or do they (still) add value?
    - What about workshops instead?

**Comment by akhmerov** [comment]
I think good non-leading questions to add are:

- How many online talks did you attend in 2021
- How many online talks do you plan to attend in 2022

**Comment by akhmerov** [comment]
We discussed this more in depth during the meeting and came up with the draft shared in #492. That survey is broader scope than just what we do, and that seems useful given our search for new activities. I'm closing this in favor of #492.
