### ISSUE TITLE
Announcing the survey

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#495]
The survey page is now live: https://virtualscienceforum.org/survey-2022/, as the next step let's announce it.

- [x] Twitter: @greplova are you available to do it?
- [x] #496

Where else should we post it?

**Comment by akhmerov** [comment]
@greplova can you unpin the tweet with the survey? It's time to close it and process the data, but I can't unpin tweets via tweetdeck.

**Comment by greplova** [comment]
Done.

**Comment by akhmerov** [comment]
Thanks. I now also closed the poll and removed its mention from the website. The follow-up of writing a summary we will track in #509
