### ISSUE TITLE
Survey email announcement

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#496]
subject: VSF online scientific event survey
from: VSF team <no-reply@mail.virtualscienceforum.org>
to: vsf-announce
---
Dear %recipient_name%,

The Virtual Science Forum has been running for almost two years now, and online events became commonplace. We believe that now is a good moment to reflect and to plan for the future: how should the online events evolve, what should we focus on?

For that we would like to ask for your input: please tell us how online events work for you by filling out this [short survey](https://virtualscienceforum.org/survey-2022/) (it should take less than 5 minutes).

Thank you in advance,  
The VSF team

**Comment by vfatemi** [comment]
Made some edits
