### ISSUE TITLE
superconducting workshop announcement 

### ISSUE THREAD

**Issue by ViktoriiaKornich** [virtualscienceforum/virtualscienceforum#506]
subject: Workshop on unconventional superconductivity
from: VSF team <no-reply@mail.virtualscienceforum.org>
to: vsf-announce
---
Dear %recipient_name%,

On March 30-31, 2022 we will run a workshop on recent developments in exotic and unconventional superconductivity.

Conventional superconductors are characterized by the global U(1) phase rotation symmetry breaking. Unconventional superconductors are a consequence of breaking of other symmetries. Thus, additional degrees of freedom (orbital, sublattice, bands, valley, etc.), electronic correlations, or more chemical elements reduce the symmetries leading to unconventional superconducting states. One might also obtain unconventional and exotic states extrinsically, e.g. by changing the geometry (interfaces and heterostructures) and applying gates or magnetic fields. This two-day workshop will gather experimentalists and theorists to discuss recent developments in unconventional and exotic superconductivity. The workshop's themes span heavy-fermion systems, high-Tc materials, high magnetic field effects, flat-band systems, and non-equilibrium superconductivity.

We invite everyone interested to join the workshop.

Please find the detailed information about the workshop and the registration form on the [workshop page](https://virtualscienceforum.org/unconventional-superconductivity/).

Best regards,  
The workshop organizers: Viktoriia Kornich, David Möckli, and Alessio Calzona

**Comment by adelatorreduran** [comment]
@ViktoriiaKornich do you want to advertise the call for contributed talks with this email too?

**Comment by ViktoriiaKornich** [comment]
@adelatorreduran thank you! No, so far we will send emails to potentially interested people by ourselves. Then, if our plan won't be successful, we will probably ask for an additional advertisements from VSF :-)

**Comment by adelatorreduran** [comment]
Sounds good!
