### ISSUE TITLE
Superconducting Diode Effects

### ISSUE THREAD

**Issue by maz-ali-web** [virtualscienceforum/virtualscienceforum#522]
## Organizers

Mazhar N. Ali, Valla Fatemi, Heng Wu

## Description

In the last few years, experimental breakthroughs in the field of non-reciprocal superconductivity have led to the realization of the superconducting diode effect in both bulk and junction based systems (Josephson diode), both with and without an applied magnetic field. These results raise fundamental questions as to the origins and mechanisms of the different superconducting diode effects as well as open the door to game-changing advancements in superconducting electronics for technological applications. In this workshop, we bring together experimentalists creating and exploring novel superconducting diodes as well as theorists explaining and predicting these effects. 

## List of potential speakers 

Banabir Pal
Dimitri Efetov
Heng Wu
J.J.A. Li
Kun Jiang
Mathias Scheurer
Naoto Nagaosa
Nicola Paradiso
Teruo Ono
Youichi Yanase
Mazhar Ali

## Preferred date and time slot

May 11th – 12th (Backup date: May 18th-19th)

## Additional remarks (if any)

12 main speakers – list below
11 invited talks at 45 min total time each: (35 min lecture + 10 min discussion)
1 overview talk at 20 min on the first day
Only Invited Talks, no contributed, no posters.
Total time: 
•	515 minutes
•	257,5 min per day, or ~4 hours per day
•	Ideally 2 hours before break, 2 hours after break
•	5 speakers in Europe, 2 from US, 3 from Japan, 1 from China
•	Ideally we schedule Japanese talks earlier in our day and US ones later. Very difficult to overlap these two audiences unfortunately.
Mix of theory and experiment (1 talk TH, followed by 1 talk EXP, and so on in alternating fashion)

Rough Schedule (TH = Theory, EXP = Experimental):
•	Day one – 
o	Intro/Overview – Maz
o	Observation of the superconducting diode effect – Teruo Ono (JP, EXP)
o	Intrinsic Superconducting Diode Effect – Yanase (JP, TH)
o	Break
o	The field-free Josephson diode in a van der Waals heterostructure – Wu (NL, EXP)
o	General Theory of Josephson Diodes – Jiang (CH, TH)
o	Josephson diode effect from Cooper pair momentum in a topological semimetal – Pal (DE, EXP)
•	Day two -
o	Supercurrent diode rectification – Paradiso (DE, EXP)
o	A phenomenological theory of superconductor diodes – Nagaosa (JP, TH)
o	Magnetic JJ and SC diodes in Magic Angle Twisted Bilayer Graphene – Efetov (SP, EXP)
o	Break
o	Universal Josephson diode effect – Fu (USA, TH)
o	Zero-field superconducting diode effect in twisted trilayer graphene Li (USA, EXP)
o	Theory of zero-field diode effect in twisted trilayer graphene – Scheurer (AUS, TH)

**Comment by akhmerov** [comment]
@maz-ali-web @vfatemi happy to see the workshop coming to life! Please proceed with approaching the speakers. I'll create a workshop page for you to edit and also create a zoom meeting once the workshop date is fixed.

**Comment by vfatemi** [comment]
@akhmerov sounds great! I would like to start work on the workshop page this week, if possible.

**Comment by akhmerov** [comment]
I've created #525 for you. You can either edit that branch directly or do it from your fork.

**Comment by maz-ali-web** [comment]
Thanks Anton!


Prof. Dr. Mazhar Ali

Associate Professor
Department of Quantum Nanoscience
Kavli Institute of Nanoscience
Faculty of Applied Sciences
Delft University of Technology (*TU Delft*)
***@***.***
+310628280964
***@***.***
+19252864907


Associate Editor | *Science** Advances* (AAAS)
***@***.***

Co-Founder and Chief Scientific Officer
Material Mind Inc.
Fremont, California, 94555, USA
www.materialmind.ai
***@***.***

https://www.linkedin.com/in/profmaz/
<https://www.linkedin.com/in/mazhar-ali-5bb53a83/>

**Comment by vfatemi** [comment]
@akhmerov We are set on May 18-19. We are also likely to span the seminars from 14:30–19:00/19:20, and allow a buffer for informal discussion until 20:00 each day. We will confirm all timeslots this week and should be ready to publicize next week. 

We also agreed to allow satellite talks, like we did for ARQH. 

Could you advise as to how to set up a VSF-branded workshop email?

**Comment by akhmerov** [comment]
> We will confirm all timeslots this week and should be ready to publicize next week.

Great to hear, let me know when #525 is ready for review. I'll also use that review to create the zoom meeting for the evnet.

> Could you advise as to how to set up a VSF-branded workshop email?

I have to do it for you. Just let me know which email you want to use for the workshop and where it should be forwarded.

**Comment by vfatemi** [comment]
the email we would like is "superdiodes".

**Comment by akhmerov** [comment]
Should be done. I sent a test email to that one.

**Comment by vfatemi** [comment]
I don't think I received any email. Was it sent to vf82@cornell.edu?

**Comment by akhmerov** [comment]
Yes. I just tried again.

**Comment by vfatemi** [comment]
@akhmerov I think the webpage is ready, and the speaker list is mostly confirmed (waiting on 3 more, but we are pretty sure it will be ok). Could you create the Zoom meeting and its registration according to what is on the page, and have a look over it make sure everything looks ok to you?

**Comment by akhmerov** [comment]
I've created the meeting and added the registration to the website draft. Will still need to review the page before merging. Please go ahead with:
- [ ] drafting the announcement email
- [ ] Registering all speakers so that they receive workshop-related communications

**Comment by akhmerov** [comment]
I've created the meeting and added the registration to the website draft. Will still need to review the page before merging. Please go ahead with:
- [ ] drafting the announcement email
- [ ] Registering all speakers so that they receive workshop-related communications

**Comment by maz-ali-web** [comment]
Here is the announcement email!


[SDE_Announcement Email.pdf](https://github.com/virtualscienceforum/virtualscienceforum/files/8458649/SDE_Announcement.Email.pdf)

**Comment by akhmerov** [comment]
I would like to avoid copypasting from a PDF. Please follow the instructions [here](https://github.com/virtualscienceforum/virtualscienceforum/blob/master/texts/email_instructions.md) to create an announcement email. Don't worry if you get something wrong—I'll fix everything for you.

**Comment by akhmerov** [comment]
A quick ping here: you will probably want to update the workshop page by including the speakers' corner recordings (both published now). This would make sense to also include in the announcement of the late arrival talk from #545. Would you like help with that?

**Comment by akhmerov** [comment]
I mean the workshop participants.

**Comment by maz-ali-web** [comment]
Right, Valla is drafting an email for this already! The plan is to send
this email tonight!

Best,
Maz

Prof. Dr. Mazhar Ali

Associate Professor
Department of Quantum Nanoscience
Kavli Institute of Nanoscience
Faculty of Applied Sciences
Delft University of Technology (*TU Delft*)
***@***.***
+310628280964
***@***.***
+19252864907


Associate Editor | *Science** Advances* (AAAS)
***@***.***

Co-Founder and Chief Scientific Officer
Material Mind Inc.
Fremont, California, 94555, USA
www.materialmind.ai
***@***.***

https://www.linkedin.com/in/profmaz/
<https://www.linkedin.com/in/mazhar-ali-5bb53a83/>

**Comment by akhmerov** [comment]
Congratulations with the successful workshop!

There are still several things that we'd like you to do. Firstly, please go over the video recordings (I'll send a private link to the organizer email) and there for each file indicate the start and end of what you want to be published. For example if you started the recording a bit earlier where the speaker didn't turn on presentation mode yet. For that please respond here with data like:

```
day 1
Speaker name; talk title; start 00:00:23 end 43:01:21
...
```

Please also double-check that the speakers are OK with publishing the recordings.

Once this is done, we'll publish the recordings to youtube, include them in the workshop page. Then I recommend writing another email announcement to the participants to let them know that the recordings are online.

Finally, please think of any feedback that you have for us, be it positive, negative, or suggestions for something new and share here.

**Comment by vfatemi** [comment]
Thanks, Anton! We will take care of this in the coming days. 

Also, on Day 1, we erred in starting the second recording too late, and as a result the first part of Kun Jiang's talk was not recorded. He kindly recorded that segment later on his own so that we could stitch it together. Here is a link to that recording: https://www.dropbox.com/sh/blguj3sslj23gfn/AACrX7gZQvBi54INhiZW7m6Ea?dl=0

**Comment by vfatemi** [comment]
All speakers confirmed OK to publish recordings with the following start/end times. Please recall the need to stitch Kun's talk with his post-event recording of the first part of his talk.

day 1, first recording
Mazhar Ali; Superconducting diode effects: intro and overview; start 00:2:24; end 00:28:35
Teruo Ono; Superconducting diode effects in Rashba superlattice; start 00:29:07; end 01:13:41
Akito Daido; Theory of intrinsic superconducting diode effect; start 01:13:42; end 01:58:48

day 1, second recording
Kun Jiang; General theory of Josephson diodes; start 00:00:00; end 00:33:25
Heng Wu; The field-free Josephson diode effect in a van der Waals heterostructure; start 00:33:4; end 01:20:23
Denis Kochan; Supercurrent rectification, Lifshitz invariants, vortex squeezing, and magnetochiral effects in synthetic Rashba superconductors; start 01:20:57; end 02:10:49
Discussion Section; Discussion Section ; start 02:10:50; end 02:32:25

day 2
Naoto Nagaosa; Theory of superconducting diode; start: 4:29; end 49:13
Nicola Paradiso; Supercurrent rectification and magnetochiral effects from Rashba and valley-Zeeman spin-orbit coupling; start 50:17; end 1:35:05
Dmitri Efetov; Magic angle bilayer graphene: broken symmetries and superconducting diodes in gate-induced Josephson junctions; start 1:36:50; end 2:25:09
Liang Fu; Supercurrent diode effect; start 2:33:01; end 03:21:10
Jiang-Xiazi Lin; Zero-field superconducting diode effect in small-twist-angle trilayer graphene; start 03:21:48; end 03:45:40
Mathias Scheurer; Theory of zero-field superconducting diode effect in trilayer graphene; start 04:02:56; end 04:55:20
Discussion Section; Discussion Section; start 04:55:34; end 05:24:22

**Comment by akhmerov** [comment]
I now published the videos, they are available in this playlist: https://www.youtube.com/playlist?list=PLqJ4D_Db7W_rex4IAIHv6_wQdWo8CE7Mk

Do you have everything you need to proceed with finalizing the workshop page?

**Comment by vfatemi** [comment]
Added all the videos to the workshop page with a draft pull request. If it looks good we can merge that. We are still considering whether to add some commentary of some kind, so "finalization" is still premature.

**Comment by akhmerov** [comment]
With the final email sent, I'll close this issue. If you want to add to the workshop page—please go ahead, this can be done at any time.
