### ISSUE TITLE
Reminder: Recent Developments in Exotic and Unconventional Superconductivity

### ISSUE THREAD

**Issue by ViktoriiaKornich** [virtualscienceforum/virtualscienceforum#527]
subject: "Workshop on Recent Developments in Exotic and Unconventional Superconductivity starts in a week!"
from: Workshop organizers <no-reply@mail.virtualscienceforum.org>
to: 89192095960
---
Dear %recipient_name%,

Thank you for registering for the workshop "Recent Developments in Exotic and Unconventional Superconductivity" that will be held in one week, on March 30-31! You can join the workshop using your [registration link](%recipient.join_url%). The finalized program is available at [the workshop page](https://virtualscienceforum.org/unconventional-superconductivity/).

See you soon,  
Viktoriia Kornich, David Möckli, Alessio Calzona

**Comment by akhmerov** [comment]
When do you want the email to be sent?

**Comment by ViktoriiaKornich** [comment]
I think, today, as the text says "in one week". Today is 24th. The workshop is on 30th, so in around a week.

**Comment by akhmerov** [comment]
I've edited things a bit (subject and link formatting). Does that look OK?

**Comment by ViktoriiaKornich** [comment]
Thank you, looks more optimistic! Let's keep it as it is now!

**Comment by ViktoriiaKornich** [comment]
I assume, it was not sent yet? Or maybe I have not noticed some notification about it? Last time there was a notification from vsf bot.

**Comment by akhmerov** [comment]
Oh, sorry, sending now.
