### ISSUE TITLE
Superconducting Diode Effects Workshop Announcement

### ISSUE THREAD

**Issue by maz-ali-web** [virtualscienceforum/virtualscienceforum#531]
subject: Superconducting Diode Effects Workshop Announcement
from: "Workshop organizers <superdiodes@virtualscienceforum.org>"
to: vsf-announce 
---
Dear %recipient_name%,

The Virtual Science Forum and conference organizers Mazhar Ali (TU Delft), Valla Fatemi (Cornell University), and Heng Wu (TU Delft) invite you to attend the Superconducting Diode Effects Workshop. This online workshop will take place on Wednesday May 18th and Thursday May 19th from 16:30 to 22:00 CEST. There are 12 invited talks by speakers at the forefront of the field—see the workshop [webpage](https://virtualscienceforum.org/josephson-diode) for the full program.

To join the meeting, please [register](https://virtualscienceforum.org/josephson-diode/#registration).

The workshop description is as follows:  
In the last few years, experimental breakthroughs in the field of non-reciprocal superconductivity have led to the realization of the superconducting diode effect in both bulk and junction-based systems (i.e. Josephson diodes), both with and without an applied magnetic field to break symmetry. These results raise fundamental questions as to the origins and mechanisms of the different superconducting diode effects as well as open the door to game-changing advancements in superconducting electronics for technological applications. In this workshop, we bring together experimentalists creating and exploring novel superconducting diodes as well as theorists explaining and predicting these effects. Through a series of seminars and discussions, we will compile the status of the field and chart a path for the future.
	
Additionally, we welcome interested colleagues to deliver a satellite talk on closely related research. We will announce these talks to all participants and include them on the workshop webpage. To let us know if you are interested in giving a satellite talk, please send us an email at  [superdiodes@virtualscienceforum.org](mailto:superdiodes@virtualscienceforum.org). Then you may either: register to give a talk in the Speaker’s Corner seminar series, share a YouTube link of your talk, or send us a recording of your talk.

Sincerely Yours,  
Prof. Dr. Mazhar N. Ali, Kavli Institute of Nanoscience, TU Delft  
Prof. Dr. Valla Fatemi, Applied and Engineering Physics, Cornell University  
Dr. Heng Wu, Applied Sciences Quantum Nanoscience, TU Delft

**Comment by akhmerov** [comment]
@maz-ali-web thanks! I copyedited the text slightly, and will send it if you're OK with it.

**Comment by maz-ali-web** [comment]
Looks great! Lets do it!

Thanks Anton!


Prof. Dr. Mazhar Ali

Associate Professor
Department of Quantum Nanoscience
Kavli Institute of Nanoscience
Faculty of Applied Sciences
Delft University of Technology (TU Delft)
***@***.***
+310628280964
+19252864907

Associate Editor | Science Advances (AAAS)
***@***.***

Co-Founder and Chief Scientific Officer
Material Mind Inc.
Fremont, California, 94555, USA
www.materialmind.ai
***@***.***
