### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by jbucko** [virtualscienceforum/virtualscienceforum#533]
## Name

Jozef Bucko

## Affiliation

Institute for Computational Science, University of Zurich

## Email

jozef.bucko@uzh.ch

## Preprint ID

2203.00697

## Title

Automated reconstruction of bound states in bilayer graphene quantum dots

## Abstract

Bilayer graphene is a nanomaterial that allows for well-defined, separated quantum states to be defined by electrostatic gating and, therefore, provides an attractive platform to construct tunable quantum dots. When a magnetic field perpendicular to the graphene layers is applied, the graphene valley degeneracy is lifted, and splitting of the energy levels of the dot is observed. Given the experimental ability to engineer this energy valley splitting, bilayer graphene quantum dots have a great potential for hosting robust qubits. Although bilayer graphene quantum dots have been recently realized in experiments, it is critically important to devise robust methods that can identify the observed quantum states from accessible measurement data. Here, we develop an efficient algorithm for extracting the model parameters needed to characterize the states of a bilayer graphene quantum dot completely. We introduce a Hamiltonian-guided random search method and demonstrate robust identification of quantum states on both simulated and experimental data.

## Authors

Jozef Bucko, Frank Schäfer, František Herman, Rebekka Garreis, Chuyao Tong, Annika Kurzmann, Thomas Ihn, Eliska Greplova

## Time slot

2022-05-11 12:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
@jbucko just checking: did you receive an email with the host key and instructions

**Comment by jbucko** [comment]
Hello, yes, I have received the instructions and the zoom link.
