### ISSUE TITLE
Talks from the workshop Recent Developments in Exotic and Unconventional Superconductivity are now online!

### ISSUE THREAD

**Issue by ViktoriiaKornich** [virtualscienceforum/virtualscienceforum#534]
subject: Videos from the workshop on unconventional superconductivity
from: "VSF team <no-reply@mail.virtualscienceforum.org>"
to: 89192095960
---
Dear %recipient_name%,

Thank you for your participation in the workshop Recent Developments in Exotic and Unconventional Superconductivity! We would like to thank the speakers and the audience for enthusiastic, professional, and friendly participation! 

The talks and discussions from the workshop have been uploaded to youtube and are listed on the [workshop page](https://virtualscienceforum.org/unconventional-superconductivity/) and in [this youtube playlist](https://www.youtube.com/playlist?list=PLqJ4D_Db7W_oNmr5HFLfWRRS2ket4Ig93). Please feel free to share the link with anyone who may be interested.

Yours sincerely,  
The organisers: Viktoriia Kornich, David Möckli, Alessio Calzona

**Comment by akhmerov** [comment]
Edited it a bit; does it look OK?

**Comment by ViktoriiaKornich** [comment]
Yes, it is great, thank you!
