### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by stefaniliccsic** [virtualscienceforum/virtualscienceforum#537]
## Name

Stefan Ilić

## Affiliation

Centro de Fisica de Materiales (CFM-MPC), San Sebastian, Spain

## Email

stefan.ilic@csic.es

## Preprint ID

2108.00209

## Title

Theory of the supercurrent diode effect in Rashba superconductors with arbitrary disorder

## Abstract

We calculate the non-reciprocal critical current and quantify the supercurrent diode effect in Rashba superconductors with arbitrary disorder, using the quasiclassical Eilenberger equation. The non-reciprocity is caused by the helical superconducting state, which appears when both inversion and time-reversal symmetries are broken. In the absence of disorder, we find a very strong diode effect, with the non-reciprocity exceeding 40% at optimal temperatures, magnetic fields and spin-orbit coupling. We establish that the effect persists even in the presence of strong disorder. We show that the sign of the diode effect changes as magnetic field and disorder are increased, reflecting the changes in the nature of the helical state.

## Authors

Stefan Ilić, Sebastian Bergeret

## Time slot

2022-05-11 14:00 UTC

## Notes

Satellite talk for the Superconducting Diode Effects Workshop

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by vfatemi** [comment]
All looks good!

**Comment by akhmerov** [comment]
@stefaniliccsic just checking: did you receive the email with the host key and the instructions?

**Comment by stefaniliccsic** [comment]
Yes, I got the e-mail

**Comment by stefaniliccsic** [comment]
I approve publishing of the recording. Start is 00:15:02, end is 01:10:31
