### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by wsban** [virtualscienceforum/virtualscienceforum#539]
## Name

Bomin Zhang

## Affiliation

University of Pittsburgh

## Email

boz15@pitt.edu

## Preprint ID

Not submitted yet

## Title

Superconducting diode effect in InSb nanowires Josephson junctions

## Abstract

We study Josephson Junction in InSb nanowires with 15nm Tin shells. We observe critical current diffraction patterns skewed and inversion-symmetric in the magnetic field and bias direction. The effect is stronger when the external magnetic field is aligned perpendicular to the nanowire, in the substrate plane. i.e. in the most likely direction of the effective spin-orbit field in the junction. The effect is also tunable by the gate voltage. We discuss this effect in the context of phi0-Josephson junction physics, one consequence of which is known in recent literature as the superconducting diode effect. We consider alternative explanations such as the effective magnetic field and perform numerical simulations to understand our findings.

## Authors

Bomin Zhang, Zhuang Li, Victor Aguilar, Po Zhang, Mihir Pendharkar, Connor Dempsey, Joon Sue Lue, Sean Harrington, Ghada Badawy, Sasa Gazibegovic, Jason Jung, An-Hsi Chen, Susheng Tan, Marcel Verheijen, Moira Hocevar, Erik Bakkers, Chris Palmstrøm, Sergey Frolov

## Time slot

2022-05-10 14:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
@wsban just checking: did you receive the email with the host key and the instructions?

**Comment by wsban** [comment]
@akhmerov Yes, I've received the host key. Thanks for asking!

**Comment by akhmerov** [comment]
I updated the abstract in our list :heavy_check_mark:

**Comment by wsban** [comment]
I approve publishing of the recording. Start is 00:16:40, end is 00:43:30.

**Comment by wsban** [comment]
Hello Anton,

Thanks for your email. I’ve received my host key and the instructions.

Best,
Bomin

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
