### ISSUE TITLE
Superdiode Workshop final pre-workshop email

### ISSUE THREAD

**Issue by vfatemi** [virtualscienceforum/virtualscienceforum#548]
subject: Satellite Talks and Zoom link for Superconducting Diode Effect workshop 
from: superdiodes@virtualscienceforum.org
to: 83054266376
---
Dear %recipient_name%,

The Superconducting Diode Effects workshop is in two days, starting at 4:30pm CET on Wednesday and Thursday. As a reminder, you can see our program at [the workshop webpage](https://virtualscienceforum.org/josephson-diode/). For your convenience, here is your [Zoom link](%recipient.join_url%) for joining the workshop.

The videos for last week's Satellite Talks are now available on the workshop webpage. A final Satellite Talk titled 'The Josephson diode effect in supercurrent interferometers' will be delivered live tomorrow at 10am ET by Rubén Seoane Souto from the Niels Bohr Institute at the University of Copenhagen. You can register to attend this one [on its page](https://virtualscienceforum.org/speakers-corner/#the-josephson-diode-effect-in-supercurrent-interferometers). 

Best regards,  
Prof. Dr. Mazhar N. Ali, Kavli Institute of Nanoscience, TU Delft  
Prof. Dr. Valla Fatemi, Applied and Engineering Physics, Cornell University  
Dr. Heng Wu, Applied Sciences Quantum Nanoscience, TU Delft

**Comment by vfatemi** [comment]
Still need to embed the videos.

**Comment by akhmerov** [comment]
The videos are now embedded, but may I suggest changing the email subject?

**Comment by akhmerov** [comment]
Oh, wait, the link is off.

**Comment by vfatemi** [comment]
Ok, I used your link format, changed the subject, and reorganized the main body a bit.

**Comment by akhmerov** [comment]
I've edited the text to avoid link text always being "here", all ready to send?
