### ISSUE TITLE
More systematic email management

### ISSUE THREAD

**Issue by vfatemi** [virtualscienceforum/virtualscienceforum#55]
Our home page would benefit from simple way for people to subscribe to get general announcements and updates via email.

**Comment by akhmerov** [comment]
Overall: we should be using an email management service.

**Comment by akhmerov** [comment]
A great idea [from twitter](https://twitter.com/mcditoos/status/1247987569633177600) we should be attaching calendar events to the registration confirmation emails.

Formatting .ics files isn't rocket science, and there are several packages that do that.

**Comment by akhmerov** [comment]
I now have a mailgun account that I used to announce the first long range colloquium. I'll experiment with the .ics for the next event.

**Comment by akhmerov** [comment]
:construction_worker_man: I can now attach high-tech calendar events to emails. :construction_worker_man:

**Comment by akhmerov** [comment]
We now have mailing list sign-ups working.

Automated announcements for speakers' corner we'll handle via virtualscienceforum/automation#13. Likely we'll do the same with LRC as we go ahead.
