### ISSUE TITLE
Consider not making mailing list sign up checked by default

### ISSUE THREAD

**Issue by Milesstone** [virtualscienceforum/virtualscienceforum#552]
The default settings of the registration form at this point have, per default, the option enabled to contact you in the future about VSF events. Since the VSF generally appeals to an informed audience that, if convinced by the format, return for news and updates by themselves, having the subscription option not disabled per default introduces unnecessary effort on the viewers part. In extension, disabling the option can be easily missed in short notice situations leading to potentially unwanted messages. As such I petition to change the default form settings to not have future messages enabled.

**Comment by akhmerov** [comment]
I'm :+1: to not have "please sign me up for the mailing list" checked by default. Any objections?

**Comment by everthemore** [comment]
Sounds good to me too 👍
