### ISSUE TITLE
Pre-School Survey - Floquet Summer School

### ISSUE THREAD

**Issue by luisfoa** [virtualscienceforum/virtualscienceforum#567]
subject: Pre-School Survey - Floquet Summer School
from: "Floquet school organizers <FloquetSchool@mail.virtualscienceforum.org>"
to: 88162067840
---
Dear %recipient_name%,

The [Floquet Summer School](https://virtualscienceforum.org/floquet-school/) is approaching and we wanted to kindly ask you to fill this [pre-School survey](https://forms.gle/4aN6XVnMY7yUkp9U6).

The information will be shared with the speakers so that they could tune the contents to the audience.

With best regards,  
Michael Sentef  
Babak Seradjeh  
Luis E. F. Foà Torres

**Comment by akhmerov** [comment]
I've edited the email to specify the subject, the "from" email, and to format the survey link. Does everything look OK?

**Comment by luisfoa** [comment]
Yes, it's perfect. Thanks again for your help!
