### ISSUE TITLE
VSF Floquet Summer School

### ISSUE THREAD

**Issue by luisfoa** [virtualscienceforum/virtualscienceforum#569]
subject: email subject
from: Floquet Summer School Team <FloquetSchool@virtualscienceforum.org>
to: 88162067840
---
Dear %recipient_name%,

The VSF Floquet Summer School is starting in a few hours. We are looking forward to having you. As a reminder you can join using your [registration link](%recipient.join_url%).

Each lecture will have 50 minutes + 10 minutes for questions. Questions could take place during the lectures but may also be deferred to the end. We remind you to check the [attendee guide](https://virtualscienceforum.org/attendeeguide/).

The lectures will be recorded as is usual in the Virtual Science Forum events. 

The schedule is as follows:

September 13 (Tuesday)
- 13:55 GMT Opening
- 14:00 GMT Takashi Oka, lecture 1  (Moderator: Babak)
- 15:00 GMT Mark Rudner, lecture 1  (Moderator: Babak)
- 16:00 – 16:10 Break
- 16.10 – 17:10 Xavier Waintal / Thomas Kloss - lecture 1 (Moderator: Luis)

September 14 (Wednesday)
- 14:00 GMT Takashi Oka, lecture 2  (Moderator: Luis)
- 15:00 GMT Mark Rudner, lecture 2  (Moderator: Luis)
- 16:00 – 16:10 Break
- 16.10 – 17:10 Xavier Waintal / Thomas Kloss, lecture 2 (Moderator: Babak)

September 20 (Tuesday)
- 15:00 GMT Anushya Chandran, lecture 1 (Moderator: Michael)
- 16:00 GMT Monika Aidelsburger, lecture 1 (Moderator: Michael)

September 21 (Wednesday)
- 15:00 GMT Anushya Chandran, lecture 2 (Moderator: Michael)
- 16:00 GMT Monika Aidelsburger, lecture 2 (Moderator: Michael)

September 22 (Thursday)
- 15:00 GMT Mikael Rechtsman, lecture 1 (Moderator: Babak)
- 16:00 GMT Mikael Rechtsman, lecture 2 (Moderator: Luis)

Thanks once again for kindly joining us.

With best regards,  
Babak, Michael and Luis

**Comment by akhmerov** [comment]
I've edited the formatting. Are you sure you want to provide the full schedule rather than what the attendees encounter in the first day?

**Comment by luisfoa** [comment]
Hi Anton, I think that the full schedule is Ok, just for reference. Or perhaps we could append it after the signature.

**Comment by akhmerov** [comment]
Oops, forgot to edit the title :sweat_smile:
