### ISSUE TITLE
VSF Floquet Summer School week 2 

### ISSUE THREAD

**Issue by sentefmi** [virtualscienceforum/virtualscienceforum#572]
subject: Second week of the Floquet Summer School
from: "VSF Floquet Summer School team <FloquetSchool@virtualscienceforum.org>"
to: 88162067840
---
Dear %recipient_name%,

We are excited to host the VSF Floquet Summer School, which is going into its second week today. As a reminder you can join using your [registration link](%recipient.join_url%).

Each lecture will have 50 minutes + 10 minutes for questions. Questions could take place during the lectures but may also be deferred to the end. We remind you to check the [attendee guide](https://virtualscienceforum.org/attendeeguide/).

The lectures will be recorded as is usual in the Virtual Science Forum events. Note that last week’s lectures are already available to (re-)watch on our [YouTube playlist](https://www.youtube.com/playlist?list=PLqJ4D_Db7W_oUZsiehNLtNyJTKyYxLaTh).

The schedule for this week is as follows:

September 20 (Tuesday)
15:00 GMT Anushya Chandran - lecture 1 (Moderator: Michael)
16:00 GMT Monika Aidelsburger - lecture 1 (Moderator: Michael)

September 21 (Wednesday)
15:00 GMT Anushya Chandran - lecture 2 (Moderator: Michael)
16:00 GMT Monika Aidelsburger - lecture 2 (Moderator: Michael)

September 22 (Thursday)
15:00 GMT Mikael Rechtsman - lecture 1 (Moderator: Babak)
16:00 GMT Mikael Rechtsman - lecture 2 (Moderator: Luis)

Thanks once again for kindly joining us.

With best regards,  
Babak, Michael and Luis

**Comment by sentefmi** [comment]
@akhmerov I wasn't sure what to put in the "to:" field

**Comment by akhmerov** [comment]
The meeting zoom ID, I've fixed it for you. All looks good, you can add the "approved" label from the menu on the right whenever you want to send the email.
![image](https://user-images.githubusercontent.com/2069677/191209302-14c7298c-f918-4942-b6f1-49bcf8102d22.png)

**Comment by sentefmi** [comment]
Yup. Sending it now :)
