### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by wfizyk** [virtualscienceforum/virtualscienceforum#573]
## Name

Wojciech Brzezicki

## Affiliation

Jagiellonian University, Krakow

## Email

w.brzezicki@uj.edu.pl

## Preprint ID

2209.06912

## Title

Unprotected edge modes in quantum spin Hall insulator candidate materials

## Abstract

The experiments in quantum spin Hall insulator candidate materials, such as HgTe/CdTe and InAs/GaSb heterostructures, indicate that in addition to the topologically protected helical edge modes these multilayer heterostructures may also support additional edge states, which can contribute to the scattering and the transport. We use first-principles calculations to derive an effective tight-binding model for HgTe/CdTe, HgS/CdTe and InAs/GaSb heterostructures, and we show that all these materials support additional edge states which are sensitive to the edge termination. We trace the microscopic origin of these states back to a minimal model supporting flat bands with a nontrivial quantum geometry that gives rise to polarization charges at the edges. We show that the polarization charges transform into the additional edge states when the flat bands are coupled to each other and to the other states to form the Hamiltonian describing the full heterostructure. Interestingly, in the HgTe/CdTe quantum wells the additional edge states are far away from the Fermi level so that they do not contribute to the transport but in the HgS/CdTe and InAs/GaSb heterostructures they appear within the bulk energy gap giving rise to the possibility of multimode edge transport. Finally, we demonstrate that because these additional edge modes are non-topological it is possible to remove them from the bulk energy gap by modifying the edge potential for example with the help of a side gate or chemical doping.

## Authors

Nguyen Minh Nguyen, Giuseppe Cuono, Rajibul Islam, Carmine Autieri, Timo Hyart, Wojciech Brzezicki

## Time slot

2022-10-18 15:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
All looks good, however I have one request: can you please shorten your affiliation? It's used to list the speakers, and should be just 2-3 words, if that's OK with you.

**Comment by wfizyk** [comment]
Ok, can be just Jagiellonian University, Krakow.

W dniu wt., 20.09.2022 o 17:10 Anton Akhmerov ***@***.***>
napisał(a):

**Comment by wfizyk** [comment]
Ok, got the key and the link
