### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by ivanamelio** [virtualscienceforum/virtualscienceforum#574]
## Name

Ivan Amelio

## Affiliation

ETH Zurich

## Email

iamelio@phys.ethz.ch

## Preprint ID

2210.03658

## Title

Polaron spectroscopy of a bilayer excitonic insulator

## Abstract

Recent advances in fabrication of two dimensional materials and their moiré heterostructures have opened up new avenues for realization of ground-state excitonic insulators, where the structure spontaneously develops a finite interlayer electronic polarization. We propose and analyze a scheme where an optically generated intralayer exciton is screened by excitations out of the excitonic insulator to form interlayer polarons. Using Quantum Monte-Carlo calculations we first determine the binding energy of the biexciton state composed of inter- and intralayer excitons, which plays a central role in understanding polaron formation. We describe the excitations out of the ground-state condensate using BCS theory and use a single interacting-quasiparticle-pair excitation Ansatz to describe dynamical screening of optical excitations. Our predictions carry the hallmarks of the excitonic insulator excitation spectrum and show how changing the interlayer exciton binding energy by increasing the layer separation modifies the optical spectra.

## Authors

Ivan Amelio, Neil Drummond, Eugene Demler, Richard Schmidt, Atac Imamoglu

## Time slot

2022-10-26 15:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
I've fixed the preprint ID and the author list: we don't support hyperlinks in either.

**Comment by ivanamelio** [comment]
Received email and everything looks good!

**Comment by ivanamelio** [comment]
I approve publishing of the recording. Start is 00:12:40, end is 01:07:01.
