### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by msoldi** [virtualscienceforum/virtualscienceforum#576]
## Name

Martina Ondina Soldini

## Affiliation

University of Zurich

## Email

msoldi@physik.uzh.ch

## Preprint ID

2209.10556

## Title

Interacting topological quantum chemistry of Mott atomic limits

## Abstract

Topological quantum chemistry (TQC) is a successful framework for identifying (non-interacting) topological materials. Based on the symmetry eigenvalues of Bloch eigenstates at high symmetry momenta, which are attainable from first principles calculations, a band structure can either be classified as an atomic limit, in other words adiabatically connected to independent electronic orbitals on the respective crystal lattice, or it is topological. For interacting systems, there is no single-particle band structure and hence, the TQC machinery grinds to a halt. We develop a framework analogous to TQC, but employing $n$-particle Green's function to classify interacting systems. Fundamentally, we define a class of interacting reference states that generalize the notion of atomic limits, which we call Mott atomic limits. Our formalism allows to fully classify these reference states (with $n=2$), which can themselves represent symmetry protected topological states. We present a comprehensive classification of such states in one and two-dimensions and provide numerical results on model systems. With this, we establish Mott atomic limit states as a generalization of the atomic limits to interacting systems.

## Authors

Martina O. Soldini, Nikita Astrakhantsev, Mikel Iraola, Apoorv Tiwari, Mark H. Fischer, Roser Valentí, Maia G. Vergniory, Glenn Wagner, Titus Neupert

## Time slot

2022-11-30 17:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
Following a discussion with @msoldi I'm closing this (the talk is postponed). @msoldi please open another application closer to the new time slot when the time becomes clearer.
