### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by msoldi** [virtualscienceforum/virtualscienceforum#580]
## Name

Martina Ondina Soldini

## Affiliation

University of Zurich

## Email

msoldi@physik.uzh.ch

## Preprint ID

2209.10556

## Title

Interacting topological quantum chemistry of Mott atomic limits

## Abstract

Topological quantum chemistry (TQC) is a successful framework for identifying (non-interacting) topological materials. Based on the symmetry eigenvalues of Bloch eigenstates at high symmetry momenta, which are attainable from first principles calculations, a band structure can either be classified as an atomic limit, in other words adiabatically connected to independent electronic orbitals on the respective crystal lattice, or it is topological. For interacting systems, there is no single-particle band structure and hence, the TQC machinery grinds to a halt. We develop a framework analogous to TQC, but employing n-particle Green's function to classify interacting systems. Fundamentally, we define a class of interacting reference states that generalize the notion of atomic limits, which we call Mott atomic limits. Our formalism allows to fully classify these reference states (with n=2), which can themselves represent symmetry protected topological states. With this, we establish Mott atomic limit states as a generalisation of the atomic limits to interacting systems.

## Authors

Martina O. Soldini, Nikita Astrakhantsev, Mikel Iraola, Apoorv Tiwari, Mark H. Fischer, Roser Valentí, Maia G. Vergniory, Glenn Wagner, Titus Neupert

## Time slot

2023-01-30 15:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
@msoldi 15:00 UTC is 16:00 CET, the time is correct.

**Comment by msoldi** [comment]
Thank you for correcting the time, it is all clear now, thank you! I also received the link for the streaming

**Comment by msoldi** [comment]
I approve publishing of the recording. Start is 00:10:58, end is 01:06:12.
