### ISSUE TITLE
EPN article

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#59]
We were invited to submit a feature article about virtual conferences to the Europhysics news.

Below I post the relevant information:

- subject: How to Make Online Conferences
- Deadline: May 4th
- Length: equivalent of < 2000 words including figures
- Author guidelines: [Guidelines-EPN authors_new.pdf](https://github.com/virtualscienceforum/virtualscienceforum/files/4455915/Guidelines-EPN.authors_new.pdf)
- I have checked that EPN does not require exclusive publication rights
- In order to make EPN attractive to a broad readership, we specifically welcome illustrations, also in the form of pictures.

I propose to use this issue to brainstorm the main message, and once that's clear, move to a shared document.

Also @virtualscienceforum upvote with :rocket: if you want to take part in writing.

**Comment by akhmerov** [comment]
I've created a [zoom meeting](https://zoom.us/j/96337573296?pwd=N25jbi9KM0VrUTUySHVVZUxsR1Fwdz09) for today's sprint. If anyone wants to join, respond here.

My proposal for today's plan:

- [ ] Agree on a workflow. My proposal: 
  - work via a pull request to this repository
  - decide on the main article message and points
  - break it down to a paragraph-level skeleton
  - distribute the paragraphs and write them asynchronously
  - cross-review and have another synchronous reading of the manuscript
- [ ] assuming everyone is fine with the above: decide the storyline
- [ ] break it down to paragraphs
- [ ] distribute the paragraphs

**Comment by xabomon** [comment]
I will join. Usual time (7pm CEST)?

**Comment by akhmerov** [comment]
Thanks, forgot to specify. Indeed 19 CEST as we discussed.

**Comment by greplova** [comment]
I'm in too.

**Comment by dvarjas** [comment]
I'll join

**Comment by everthemore** [comment]
If there is a paragraph left I'll join. Also, don't forget to put the image on the list, perhaps?
