### ISSUE TITLE
Reproducibility workshop reminder

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#598]
subject: Reproducibility workshop starting soon
from: VSF team <no-reply@mail.virtualscienceforum.org>
to: 88003344446
---
Dear %recipient_name%,

We are looking forward to your participation in the upcoming workshop, "Does condensed matter physics need to worry about a replication crisis?", which is taking place this Thursday, March 2. You will be able to join using your [registration link](%recipient.join_url%).

Since our original announcement, we have added an additional section of satellite talks contributed by workshop attendees, which are now hosted on the [web page](https://virtualscienceforum.org/reproducibility_in_cmp/#satellite-talks).

We strongly encourage you to take a few moments to look through these talks in the days before the workshop begins. Some of these talks are related to the presentations that will be given on Thursday and will be relevant for our discussions.

We also invite you to join for the satellite [Speakers' Corner talk](https://virtualscienceforum.org/speakers-corner/#erroneous-statistics-in-physical-review-physics-education-research) "Erroneous Statistics in Physical Review Physics Education Research" by Michael B. Weissman (UIUC) on Tuesday.

Thank you, and we look forward to seeing you at the workshop.  
The organizers: Brian Skinner and Sergey Frolov

**Comment by akhmerov** [comment]
@brianqskinner something like this? I've edited the page, so let me know if this is good to go.

**Comment by brianqskinner** [comment]
Hi Anton,

This looks terrific, thank you!

One small change: Anatoli Polkovnikov has requested that the title of his
talk be changed to: "Illusive Many-Body Localization"

-Brian
