### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by julianingham** [virtualscienceforum/virtualscienceforum#601]
## Name

Julian Ingham

## Affiliation

Columbia University

## Email

jingham@bu.edu

## Preprint ID

2308.00748

## Title

Revival of Quadratic Dirac fermions and the competition of ordered states in twisted bilayer graphene

## Abstract

Twisted bilayer graphene (TBG) exhibits an interesting phase diagram as a function of electron density — when the number of electrons per moir\'e unit cell $\nu$ is an integer, insulating and nematic states are observed, with superconductivity appearing as $\nu$ is increased past integer values. The fourfold degenerate bands near charge neutrality feature Dirac fermions, and experiments have observed an effect known as the “Dirac revival”: at integer values of $\nu$ the density ‘resets’ to the charge neutrality point, so the system is described by a Dirac theory even away from charge neutrality. In this talk I will describe a theoretical proposal in which these revived Dirac fermions have a small velocity, so that their dispersion is approximately quadratic in a range of energies. The quadratic Dirac fermions result in a logarithmic enhancement of interaction effects, which does not appear for a linear dispersion. The resulting non-trivial RG flow produces nematic and insulating states near integer fillings, which give way to superconducting states past a critical relative doping, and predicts phases which resolve several experimental puzzles — producing T-IVC insulating states for repulsive interactions, explaining the results of very recent STM experiments, alongside nodal $A_2$ superconductivity near $\nu=2$, whose properties can explain puzzles in tunnelling studies of the superconducting state. The model also explains why superconductivity is generally not observed when TBG is aligned with an hBN substrate, why superconductivity is less robust near $\nu=0$ and 1 than $\nu=2$, the asymmetry of the phase diagram between electron and hole doping, and the transition from a gapless to gapped charge neutrality point as a function of strain seen in STM — unifying many aspects of the phase diagram with a single theoretical model.

## Authors

Julian Ingham, Tommy Li, Mathias Scheurer, Harley Scammell

## Time slot

2023-09-26 14:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
Hi @julianingham just checking: did you receive the email with the host key?

**Comment by akhmerov** [comment]
@julianingham checking again: did you receive the email with the host key?

**Comment by julianingham** [comment]
Hi Anton,

the talk just finished; there was a short delay starting -- I was wondering if we could trim the recording to begin when the talk actually starts?

Julian
________________________________

**Comment by akhmerov** [comment]
Absolutely, the bot will send you a video link and the instructions on how to provide the trim times.

**Comment by julianingham** [comment]
Hi Anton,

I still have not received an email from the bot (it's not in my spam folder or inbox). What is the usual time delay before this email is sent?

Julian
________________________________

**Comment by julianingham** [comment]
Hi Anton,

I still haven't received this email.

Best,
Julian
________________________________

**Comment by julianingham** [comment]
I approve publishing of the recording. Start is 00:19:30, end is 01:19:07.
