### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by YugoOnishi** [virtualscienceforum/virtualscienceforum#609]
## Name

Yugo Onishi

## Affiliation

Massachusetts Institute of Technology

## Email

yugo0o24@mit.edu

## Preprint ID

2401.13847

## Title

Quantum weight

## Abstract

We introduce the concept of quantum weight as a fundamental property of insulating states of matter that is encoded in the ground-state static structure and measures quantum fluctuation in electrons' center of mass. We find a sum rule that directly relates quantum weight -- a ground state property -- with the negative-first moment of the optical conductivity above the gap frequency. Building on this connection to optical absorption, we derive both an upper bound and a lower bound on quantum weight in terms of electron density, dielectric constant, and energy gap. Therefore, quantum weight constitutes a key material parameter that can be experimentally determined from X-ray scattering.

## Authors

Yugo Onishi, Liang Fu

## Time slot

2024-04-05 14:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by Gaozou** [comment]
I confirmed that I have received an email containing zoom meeting information.

**Comment by YugoOnishi** [comment]
I confirmed that I have received an email containing Zoom meeting information.

**Comment by YugoOnishi** [comment]
I approve publishing of the recording. Start is 00:00:00, end is 01:09:17.
