### ISSUE TITLE
Webpage listing virtual seminars

### ISSUE THREAD

**Issue by andrenmelo** [virtualscienceforum/virtualscienceforum#61]
Would be cool to create a physics version of this: https://mathseminars.org/

The source code of that website is even available here: https://github.com/roed314/seminars

**Comment by akhmerov** [comment]
NB: they don't have a license yet, so the code isn't available for reuse. (https://github.com/roed314/seminars/issues/4)

**Comment by roed314** [comment]
We will be adding a license soon, so feel free to get started.

**Comment by roed314** [comment]
We've added a GPLv2+ license.  Feel free to get in touch if you have questions about how we did anything.

**Comment by akhmerov** [comment]
Thanks!

**Comment by akhmerov** [comment]
https://researchseminars.org/ now covers all domains, but we should link it and make use of it.

**Comment by vfatemi** [comment]
Per @akhmerov 's last comment, we no longer need to create an aggregator. closed under review of 20 Oct 2020 org meeting.
