### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by juandaanieel** [virtualscienceforum/virtualscienceforum#611]
## Name

Juan Daniel Torres

## Affiliation

TU Delft

## Email

jdtorresluna@tudelft.nl

## Preprint ID

2405.00538

## Title

Probing valley phenomena with gate-defined valley splitters

## Abstract

Despite many reports of valley-related phenomena in graphene and its multilayers, current transport experiments cannot probe valley phenomena without the application of external fields. Here we propose a gate-defined valley splitter as a direct transport probe for valley phenomenon in graphene multilayers. First, we show how the device works, its magnetotransport response, and its robustness against fabrication errors. Secondly, we present two applications for valley splitters: (i) resonant tunneling of quantum dots probed by a valley splitter shows the valley polarization of dot levels; (ii) a combination of two valley splitters resolves the nature of order parameters in mesoscopic samples.

## Authors

Juan Daniel Torres Luna, Kostas Vilkelis, Antonio L. R. Manesco

## Time slot

2024-06-04 15:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
@juandaanieel did you receive the host key and the link?

**Comment by juandaanieel** [comment]
I have received the host key

**Comment by akhmerov** [comment]
@juandaanieel did you review the recording?

**Comment by juandaanieel** [comment]
I approve publishing of the recording. Start is 00:17:30, end is 00:48:50.
