### ISSUE TITLE
Speakers' corner talk application

### ISSUE THREAD

**Issue by D-Scheer** [virtualscienceforum/virtualscienceforum#613]
## Name

David Scheer

## Affiliation

RWTH Aachen University

## Email

david.scheer@rwth-aachen.de

## Preprint ID

2406.14435

## Title

The superconducting clock-circuit: Improving the coherence of Josephson radiation beyond the thermodynamic uncertainty relation

## Abstract

In the field of superconducting electronics, the on-chip generation of AC radiation is essential for further advancements. Although a Josephson junction can emit AC radiation from a purely DC voltage bias, the coherence of this radiation is significantly limited by Johnson-Nyquist noise. We relate this limitation to the thermodynamic uncertainty relation (TUR) in the field of stochastic thermodynamics. Recent findings indicate that the thermodynamic uncertainty relation can be broken by a classical pendulum clock. We demonstrate how the violation of the TUR can be used as a design principle for radiation sources by showing that a superconducting clock circuit emits coherent AC radiation from a DC bias.

## Authors

David Scheer, Jonas Völler, Fabian Hassler

## Time slot

2024-07-11 14:00 UTC

## Confirmation

I declare that:

- The other coauthors agree to the presentation
- I permit VSF to perform and publish the recording (following my approval)
- I will follow the VSF code of conduct and the rules of the Speakers' corner seminar

**Comment by akhmerov** [comment]
Hey @D-Scheer, we usually recommend EU late afternoon for the talks if you want to reach the audience from the Americas.

**Comment by D-Scheer** [comment]
Hi @akhmerov, that is a good point! What is the usual time for these talks?
 I will gladly change the time slot if that helps.

**Comment by akhmerov** [comment]
4PM EU time is probably best

**Comment by D-Scheer** [comment]
Then I will do 4PM.

**Comment by akhmerov** [comment]
Unfortunately our scripts only support integer hours, sorry about that.

**Comment by D-Scheer** [comment]
Ok that's unfortunate. Would Wednesday 2024-07-10 also work? Then 4PM EU would be ideal.

**Comment by akhmerov** [comment]
That works. Unfortunately my group won't be able to join then, but we will catch up with the recording once it is available. Please update the time in the issue description.

**Comment by akhmerov** [comment]
For my group 07-11 works better, and several of us would like to attend. Is it OK to move to Thursday same time? Please update the time in the issue description.

**Comment by D-Scheer** [comment]
That also works.

**Comment by akhmerov** [comment]
Just checking, did you also receive the zoom link and host key?

**Comment by D-Scheer** [comment]
Yes, thank you for asking.

**Comment by D-Scheer** [comment]
I approve publishing of the recording. Start is 00:03:18, end is 00:36:36.
