### ISSUE TITLE
Session time

### ISSUE THREAD

**Issue by giulia-pacchioni** [virtualscienceforum/virtualscienceforum#64]
Hi All,

I think there is some confusion about the colloquium time: if I'm not mistaken, CET is London time (one our behind Europe), not Europe time, because of daylight saving time. The idea is to have the talk at 19:30 Europe time, right? That would be 19:30pm _CEST_ time. I’m not sure if it’s worth sending a follow up email to ensure the time is clear to everybody…

See you later,
Giulia

**Comment by giulia-pacchioni** [comment]
On the other hand, the fact that the email says 'in two hours' is going to be helpful, so maybe no need for an update. The time is also correct on the website.

**Comment by akhmerov** [comment]
Yep, it was my bad, I'll fix that in the next announcements.
