### ISSUE TITLE
New development in scanning probe microscopy (tentative title)

### ISSUE THREAD

**Issue by giulia-pacchioni** [virtualscienceforum/virtualscienceforum#68]
## Title: <your session title>

New development in scanning probe microscopy (tentative title)

## Organizers

**List the names of the organizers, preferably [link](url) to their personal webpages.**

[Giulia Pacchioni](https://www.nature.com/natrevmats/about/editors) (Nature Reviews Materials)
[Fabio Donati](https://qns.science/our-team/fabiodonati/) (Ewha Womans University, Seoul)
[Aparajita Singha](https://www.fkf.mpg.de/person/104080/5017348) (Max Planck Institute)
[Fabian Natterer](https://www.physik.uzh.ch/en/groups/natterer/Team/Fabian-Natterer.html) (University of Zurich)
[Marina Pivetta](https://people.epfl.ch/marina.pivetta/?lang=en) (EPFL)

## Description

**A 1-2 paragraph description explaining the scope, timeliness, and the interest of the session.**

Scanning probe techniques (in particular scanning tunneling microscopy and atomic force microscopy) have been around for 30 years, but researchers are still find clever ways to push their reach and measure systems and properties that were previously inaccessible.
The idea behind this session is to invite 3 or 4 talks on very recent technical developments in these techniques, and then to have a few contributed talks and posters showcasing recent results obtained with scanning probe techniques (not necessarily technical advancements, any new results).

## List of potential speakers 

**Please have more potential speaks than slots in the conference: people are often busy.**

[Katharina Franke](https://www.physik.fu-berlin.de/en/einrichtungen/ag/ag-franke/index.html), FU Berlin -- recent papers on inelastic (vibrational) spectroscopy on molecules, and on STM combined with microwave radiation.

[Yosoo Kim](http://www2.riken.jp/Kimlab/), Riken -- recent results on STM combined with optics, such as Raman spectroscopy on single molecules or triplet exciton formation.

[Jasha Repp](http://www.physik.uni-regensburg.de/forschung/repp/), University of Regernsburg -- recent work on using AFM to determine the charge states of molecules on insulators, and interesting work on STM coupled with THz radiation.

[Laurent Limot](http://www.ipcms.unistra.fr/?page_id=9173), Strasbourg University -- recent work with magnetic molecules (metallocenes) on the tip of the STM. 

[Jo Stroscio](https://www.nist.gov/people/joseph-stroscio), NIST -- Combination of STM, AFM, and magnetotransport measurements for in-operando studies.

## Preferred date and time slot

**We suggest to reserve at least two months for the organization and the announcement.**

We are thinking about the middle or end of June, in a Europe + Asia time zone.

## Additional remarks (if any)

We would like to have a really interactive poster session: imagine one hour during which each poster has a Zoom link that leads to a discussion room in which you can see the poster and ask questions to the presenter. There are  a lot of technical details to think about, but we feel this would make the event much more useful in terms of find out what are the latest news from everybody's labs.

**Comment by akhmerov** [comment]
Awesome plan.

Following the organizational discussion I propose the following first steps:

- decide on a specific date and time slot
- approach the speakers

After that we can proceed with publishing the event page and announcing a call for poster presentations. These are going to be challenging to organize, but we're also excited to experiment with the format!

**Comment by giulia-pacchioni** [comment]
I agree on your first steps :). We will also need to choose a name for the event.

**Comment by akhmerov** [comment]
OK, the event page is now live. @giulia-pacchioni for the next steps:

- [ ] Please add to the registration form the request to confirm that the participants agree to the attendee guide, a question how they heard from us, and whether they want to hear about new events
- [ ] If you want the event to be announced to the VSF mailing list, please add the announcement text in `/texts` folder (the location isn't perfect, but should be good enough for now).
- Shall I also link the poster registration form from the VSF page?
