### ISSUE TITLE
Open Colloquium Speaker Suggestions

### ISSUE THREAD

**Issue by babaks77** [virtualscienceforum/virtualscienceforum#79]
If we decide to continue the colloquium series, I think it's a good idea to invite speaker suggestions to the community. This can be done by opening an issue using a template like it is done for event suggestions.

**Comment by babaks77** [comment]
Started a pull request to add the issue template file. Needs to be checked for correct format, etc.

**Comment by akhmerov** [comment]
I propose closing in favor of #138

**Comment by babaks77** [comment]
Agreed. Closing now.
