### ISSUE TITLE
Next meeting agenda

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#80]
In order to plan the meeting agenda in advance, I propose to use this issue.

Please respond if you want to propose an item for discussion.

I can think of #79 (proposed by @babaks77).

Also if anyone outside of the current group members wants to join, please respond here.

**Comment by akhmerov** [comment]
Also: we discussed moving the meeting to Friday or Monday. Friday is perhaps too soon, but we can also try Monday also 19:30 CEST.

Vote :+1: for Monday, :-1: to keep it as is.

**Comment by babaks77** [comment]
I think having the meeting the day before the event is good to make sure everything is on track. Otherwise, I'm good with moving it to Monday.

**Comment by akhmerov** [comment]
Two more agenda item proposals:

- Planning the rewrite of the manuals
- Group photo for the EPN

**Comment by akhmerov** [comment]
Meeting notes: https://hackmd.io/vGTTlPeVReCrpvdrv1cFtw
