### ISSUE TITLE
Registration form not shown in Chromium

### ISSUE THREAD

**Issue by antoniolrm** [virtualscienceforum/virtualscienceforum#84]
When trying to register using Chromium, instead of the registration form, I see what is shown in the screenshot below. It works just fine on Firefox.

![Screenshot from 2020-05-13 10-44-39](https://user-images.githubusercontent.com/49452874/81791706-5913c900-9507-11ea-916d-f8b95d31952a.png)

**Comment by akhmerov** [comment]
@antoniolrm thanks for reporting! Can you please open your browser developer console (should be ctrl-shift-I → console) and check if you see any errors?

**Comment by antoniolrm** [comment]
Sure! Here it is:

![Screenshot from 2020-05-13 11-03-08](https://user-images.githubusercontent.com/49452874/81793256-692ca800-9509-11ea-8a03-a2497f86bb4b.png)

**Comment by akhmerov** [comment]
Could it be that either your site settings or an extension block access? Blocking third party cookies on our site might also have this effect from what I gather.

**Comment by antoniolrm** [comment]
Allowing cookies indeed solves the problem.
