### ISSUE TITLE
Long range colloquium invitations

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#91]
## Theory

-   Joel Moore
-   Gil Refael
-   Daniel Arovas
-   Barbara Terhal
-   ~Xie Chen~
-   Atac Imamoglu
-   Barbara Kraus
-   Lenka Zdeborova
-   ~Mohammad Hafezi~
-   Allan MacDonald
-   Leonid Glazman
-   Jairo Sinova
-   Jason Alicea
-   Yaroslav Tserkovnyak
-   Oskar Vafek

## Experiment

-   Immanuel Bloch
-   ~Michel Devoret~
-   Pablo Jarillo-Herrero
-   Andrew Mackenzie
-   Markus Greiner
-   Paola Cappellaro
-   Andreas Wallraff
-   Margaret Murnane
-   ~Nathalie de Leon~
-   Jagadeesh Moodera

Wiki Page List of Speakers: https://github.com/virtualscienceforum/virtualscienceforum/wiki/speakers_list

**Comment by akhmerov** [comment]
Write here when you invite someone.

**Comment by akhmerov** [comment]
Sent an invite to Nurit Avraham for July 8.

**Comment by akamra47** [comment]
Sent an invitation to Jagadeesh Moodera for July 22nd.

**Comment by akamra47** [comment]
> Sent an invitation to Jagadeesh Moodera for July 22nd.

Declined. Too busy at the moment.

**Comment by akhmerov** [comment]
Following a discussion at the last meeting we recommend inviting new group leaders (≲10 years after PhD). PhDs and postdocs are also OK if the host has a clear expectation that they are able to deliver a good talk.

Also @virtualscienceforum a reminder: we really need to invite someone for the next open slot about now.

**Comment by vfatemi** [comment]
Sent an invitation to Nathalie de Leon for July 22nd.

**Comment by greplova** [comment]
Titus Neupert accepted the invite for August 5.

**Comment by giulia-pacchioni** [comment]
That's great about Titus :).

I have also added to the list of possible people to invite Andrea Young. I was convinced he would  speak at the ICFO school on moire materials, but this is not the case. He has a lot of cool recent results and we haven't had someone to talk about transport in twisted bilayers yet, so he can be an option.

**Comment by vfatemi** [comment]
Nathalie de Leon has accepted the invite for July 22.

**Comment by babaks77** [comment]
Mohammad Hafezi has accepted for August 19, 2020

**Comment by babaks77** [comment]
I have placed a link to the wiki page [list of speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/speakers_list). Please update the table for a more integrated view of the information on invitations, etc.

**Comment by everthemore** [comment]
Sent an invitation to John Preskill for Sept. 2nd

**Comment by vfatemi** [comment]
Michel is unavailable for Sept. 2, but is available for Sept. 16.

**Comment by vfatemi** [comment]
Michel confirms Sept. 16 and is ok with recording.

**Comment by greplova** [comment]
Natalia Ares invited for Oct 14

**Comment by vfatemi** [comment]
Brian Skinner invited and confirmed for Oct. 14

**Comment by greplova** [comment]
Natalia Ares confirmed for Oct 28. Abstract and permission for recording has been requested - waiting for replies.

**Comment by babaks77** [comment]
Sent an invite to Jennifer cano for Nov 11.

**Comment by babaks77** [comment]
Jennifer Cano accepted for Nov 11.

**Comment by greplova** [comment]
Xie Chen accepted for January 20 2021 (invited by @everthemore)
@akhmerov is inviting Leonid Levitov for February 3 2021

**Comment by everthemore** [comment]
Xie Chen postponed to Feb 17th 
Leonid Levitov invitation now for January 20th (@akhmerov)

**Comment by akhmerov** [comment]
Leonid confirmed for Jan 20. Feb 3 slot is the next available.

**Comment by akhmerov** [comment]
@vfatemi will invite Andrea Young for Feb 3.

**Comment by vfatemi** [comment]
Andrea Young accepts for Feb 3.

**Comment by vfatemi** [comment]
Andrea Young has also accepted the recording and publishing of the video, and to do the pre-LRC chat. Title and abstract forthcoming.

**Comment by babaks77** [comment]
This issue is closed and all updates is now recorded on the [LRC Speakers wiki page](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers).
