### ISSUE TITLE
Organizational meeting 2020-05-26

### ISSUE THREAD

**Issue by dvarjas** [virtualscienceforum/virtualscienceforum#92]
Here's the [zoom link](https://us02web.zoom.us/j/87267864947?pwd=cU1sRXJPQlRuOGhsL3NWYmI2WEF2Zz09). We've enabled waiting room there, so please reply here if you would like to join (and if I don't already know you).

Here's the [hackmd document](https://hackmd.io/KexWuZloS0WcoUqx8b0OoQ) with the notes.

Proposed agenda:
+ Final checks for Wednesdays's Long Range Colloquium

+ Review guide rewrite

Add your proposals for the agenda items below.

**Comment by akhmerov** [comment]
- Update on microscopy conference
- Update service account
