### ISSUE TITLE
Organizational meeting 2020-06-02

### ISSUE THREAD

**Issue by xabomon** [virtualscienceforum/virtualscienceforum#99]
Here's the [zoom link](https://us02web.zoom.us/j/87267864947?pwd=cU1sRXJPQlRuOGhsL3NWYmI2WEF2Zz09). We've enabled waiting room there, so please reply here if you would like to join (and if I don't already know you).

Here a [hackmd](https://hackmd.io/RLwM5PcrTuSOgXgKCMrXjQ) document for the minute notes.

Proposed agenda:
- Update on next Long Range colloquium
- Organizational details on chat with long range colloquium speaker
- Update on scanning probe microscopy conference
- Progress on guidelines re-writing

Comment on this issue to add more items to the agenda.

**Comment by akhmerov** [comment]
* New zoom account :)

**Comment by akamra47** [comment]
Further speakers and invitations?

**Comment by greplova** [comment]
I created PR#100 for the moderator guide.

**Comment by xabomon** [comment]
Added meeting minutes to [wiki](https://github.com/virtualscienceforum/virtualscienceforum/wiki/VSF-organization-meetin-2020-06-02).

Issue closed.
